### ISSUE TITLE
Bypass Service Worker for specific external URLs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#103]
We have a custom extension, which requests an external sevice. This request is intercepted by the service worker. See image. If I "Bypass for network" it works. Is where a way for an extension to define that an URL should be omitted?
![image](https://user-images.githubusercontent.com/3850918/43781040-4eb20c80-9a5c-11e8-9ff0-fe4477614f40.png)

**Comment by sashuk** [comment]
@mapcentia Sure, like in example https://github.com/sashuk/vidi/blob/develop/browser/service-worker/index.js#L105 for `bam.nr-data.net` requests. The `gc2.io` should be ignored for caching?

**Comment by mapcentia** [comment]
@sashuk yes, gc2.io should be ignored. But is it possible for extensions to set this for arbitrary URLs? So its possible to write an extension, which requests an external API, without the need to hardcode the URL into core Vidi?

**Comment by sashuk** [comment]
@mapcentia The Vidi service worker now accepts the URL regexp that will allow certain URLs to be ignored. Please consider the demo script that first tells service worker to ignore all URLs that have `jsonplaceholder.typicode` in it and then it actually requests the https://jsonplaceholder.typicode.com/todos/1 URL. As shown in the attached GIF, the request is performed without service worker.

```javascript
/**
 * Talking to the service worker in test purposes
 */
setTimeout(() => {
    if (navigator.serviceWorker.controller) {
        navigator.serviceWorker.controller.postMessage({
            action: `addUrlIgnoredForCaching`,
            payload: `jsonplaceholder.typicode`
        });

        setTimeout(() => {
            fetch('https://jsonplaceholder.typicode.com/todos/1').then(() => {}).then(() => {});
        }, 3000);
    } else {
        throw new Error(`Unable to invoke the service worker controller`);
    }
}, 3000);
```

This was implemented in https://github.com/sashuk/vidi/commit/6c909089d0f8d653602320901a558b10e4daa9a1

![bypass](https://user-images.githubusercontent.com/1390758/43942149-6d6c9d30-9ca9-11e8-95f5-138e70bfff1d.gif)
