### ISSUE TITLE
Different "pending" signs for Awaiting network, Awaiting log in and Error

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#106]
Right out there are two statuses on a not comitted edit:
1. Pending (Yellow)
2. Error (Red)

It could be useful to have three:
1. Awaiting network (Yellow)
1. Awaiting login (Yellow)
2. Error (Red)

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/f24e3630b1807202605b8d212621084e95a18aaf

(the **Awaiting login** label is now yellow as well)

![signs](https://user-images.githubusercontent.com/1390758/43937163-9631c954-9c8e-11e8-8d0b-01cc3e9fdd37.gif)
