### ISSUE TITLE
Vidi doesn't start with the uglified JavaScript bundle 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#107]
After "Grunt uglify processhtml" Vidi won't load completly.

Question: Will this metode force a the new file to be loaded? 
<script src="/js/build/all.min.e35f75987df6b1a9.js"></script>

**Comment by sashuk** [comment]
@mapcentia Yes, the **e35f75987df6b1a9** part of `/js/build/all.min.e35f75987df6b1a9.js` is a hash of the JavaScript code, so whenever Vidi code is changed or new JavaScript file is added, it changes.

**Comment by sashuk** [comment]
The conflicting CSS was removed https://github.com/sashuk/vidi/commit/a094bc4a258b64b623026abd4edbd245a8361eaa, now `grunt production` buils correct files
