### ISSUE TITLE
Enable a third group level in layer-tree

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#108]
In some case we need a third group level in the layer tree. I've add meta property called: meta.vidi_sub_ group with the group name. So layers with this property should be grouped the inside the layer group they belong.

![image](https://user-images.githubusercontent.com/3850918/43906287-36c811da-9bf3-11e8-851a-746e83b04783.png)

**Comment by sashuk** [comment]
@mapcentia Should be layers inside of subgroup be sortable (with storing order in state, recreating it on reload etc.)?

**Comment by mapcentia** [comment]
@sashuk It could be great if both the subgroup it self and the layers indside are sortable.

**Comment by sashuk** [comment]
Intermediate commit: https://github.com/sashuk/vidi/commit/07ed3b0c08e6dd7cef5be9d789b48677b50d87e1

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Third level in layer tree](https://trello.com/c/yOAXfGYA/1-third-level-in-layer-tree)

**Comment by sashuk** [comment]
@mapcentia Seems like access is denied

![access](https://user-images.githubusercontent.com/1390758/45201375-ac039a80-b2a7-11e8-97a9-935d5732f03a.png)

**Comment by mapcentia** [comment]
@sashuk I'm doing a Trello baord for a client and linking to issues. Its open now.

**Comment by sashuk** [comment]
@mapcentia Thank you, the access was gained

**Comment by sashuk** [comment]
@mapcentia Could you please check if the sub groups meta property is passed correctly? The meta now looks like 
```
{"single_tile": true, "vidi_layer_type": "t", "vidi_sub_ group": "Urban spatial development", "tiles_service_uri": "", "vidi_layer_editable": false, "layer_search_include": false}
```

so the `vidi_sub_ group` has a whitespace between underscore and `g` - is it okay?

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

**Comment by sashuk** [comment]
Current progress: everything is implemented, except toggling the subgroup state (open / close)

![thirdlevel](https://user-images.githubusercontent.com/1390758/45292891-27c04a00-b529-11e8-839d-acf2fd793f68.gif)

**Comment by sashuk** [comment]
@mapcentia  The third level subgroups in `layerTree` were implemented in https://github.com/sashuk/vidi/commit/618ba37c8931dcdec8a6a6b39add78245ccbfe66, https://github.com/sashuk/vidi/commit/bab7f97a735d960d57c9812377fdbae1b5bd8e07,  https://github.com/sashuk/vidi/commit/b99fbbbf320d19244e837a105ae91c67dc84ce1f
