### ISSUE TITLE
Force offline mode is default enable when starting Vidi (sometimes)

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#109]
Sometimes Force offline mode is default enable when starting Vidi.
Right now on my computer in Chrome offline mode is enabled on load, but in Firefox is disabled.
Is this due to some race condition?

![image](https://user-images.githubusercontent.com/3850918/43906668-21a4509c-9bf4-11e8-87be-751645d25c18.png)

**Comment by mapcentia** [comment]
@sashuk It seems to occur first time Vidi is loaded. Via BrowserStack I have observed this in several browsers.

**Comment by sashuk** [comment]
@mapcentia Yes, this is due to the timeout of service worker registration. I will make it update as soon as the service worker is registered.

**Comment by sashuk** [comment]
The race condition was observed for `layerTree.create()`, refactoring the whole `layerTree` creation process using the queueing

**Comment by sashuk** [comment]
@mapcentia **Force offline mode** control works like this now:
- if user have not changed the control personally (i.e. did not make a choice), then the **Force offline mode** is always enabled when app is online and is disabled when app goes offline;
- if user made a choice, then if app goes offline and then back online, then the user's choice is recreated.

So, the user's choice has the priority over internal decisions of the application.

Implemented in https://github.com/sashuk/vidi/commit/0b3ee04a55002c1ce154793ee9fe616cf58892c9
