### ISSUE TITLE
Layers added in run-time are not included in State

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#111]
If you start Vidi with an layer, which is not in Meta like this:

https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/11/39.2358/-6.8057/test.polygon

When it will be added dynamically. But when taking a snapshot, it will not be re-created.

**Comment by sashuk** [comment]
@mapcentia Could you please specify, should the any orbitrary state with `test.polygon` in it activate the `test.polygon` layer if the page was initially navigated with https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/11/39.2358/-6.8057/? Basically when the page is loaded, the `test.polygon` is absent, should it be recreated if it exists in the applied state snapshot?

**Comment by sashuk** [comment]
@mapcentia If the layer in state snapshot have not been loaded yet, it is loaded dynamically upon state snapshot activation.

Implemented in https://github.com/sashuk/vidi/commit/0e0701c605bf4fc745181bc7da280bbecccf38c7

Tested in https://github.com/sashuk/vidi/commit/633a13bb7116e89cb4a9921c0e34668fb2fb2ba5
