### ISSUE TITLE
Vidi doesn't start properly with all GC2 installations

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#114]
Just tried connecting Vidi to a GC2 installation and got an odd result.
Set GC2 host in config.js to: https://mapgc2.geoenviron.dk
Set configUrl in config.js to: "https://geoenviron.github.io/vidi_configs" 
And load: /app/geokon/?config=975.json

Only one layer is shown in the layer tree. Using the master branch all layers are rendered

**Comment by sashuk** [comment]
@mapcentia Layers are now shown correctly (implemented in https://github.com/sashuk/vidi/commit/5ade415a9cbf057536e7116794385aa0f321ad2c)

![layers](https://user-images.githubusercontent.com/1390758/44197332-e8444f00-a170-11e8-8d5c-d2ab891ed313.png)

:grey_exclamation: However, when loaded from config file (https://vidi.alexshumilov.ru/app/geokon/?config=975.json), following errors occur:
- service worker is not able to start up on first load
- the **Layers all loaded L** never happens

Resolving issues within this issue.

**Comment by sashuk** [comment]
Additional fix in https://github.com/sashuk/vidi/commit/2628a5f4c6aa4da7811fb8f14bdaa96c3cfb463f

**Comment by sashuk** [comment]
Additional `meta` validity check was added in https://github.com/sashuk/vidi/commit/92f3ed5ce972841dde03a0e8aa3337ba925edf2f
