### ISSUE TITLE
Don't write out the JSON object when there is an error. It can be quite verbose

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#116]
![image](https://user-images.githubusercontent.com/3850918/44254536-5cc7ce00-a203-11e8-9205-9db5506b2d82.png)

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/53fee6db4099a996cfc05a6715473937b78a8d81

![error](https://user-images.githubusercontent.com/1390758/44265465-3a609f80-a259-11e8-8bdc-b34b3da33520.png)
