### ISSUE TITLE
When a tile layer is not editable, don't show the edit tools in pop-up

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#117]
![image](https://user-images.githubusercontent.com/3850918/44254638-b62ffd00-a203-11e8-97e6-6f3d7d4c1a21.png)

**Comment by sashuk** [comment]
Also they should be hidden if editor is disabled

**Comment by mapcentia** [comment]
@sashuk yes

**Comment by sashuk** [comment]
@mapcentia Great, thanks!

**Comment by sashuk** [comment]
@mapcentia Could you please tell if this ts it correct confirm text?

https://github.com/sashuk/vidi/blob/47039e89f375af0a281a3388b29b17228d791a02/browser/modules/sqlQuery.js#L272

It translates as "Are you sure? Your changes will not be saved!", this confused me as changes will be saved normally.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/df377b876ea20c2614f94857ee3d21fb5bd21f67

![editing](https://user-images.githubusercontent.com/1390758/44264953-1c923b00-a257-11e8-9e12-ec6bd04188e9.gif)
