### ISSUE TITLE
Single tile broken

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#120]
In Meta where now an option for loading a layer as single tiled. Meaning it bypasses til tile cache and request the WMS directly. But in develop branch its broken. When turning on a single tiles layer Vidi goes into a loop. I've checked the layer "1982" for single tiles
![image](https://user-images.githubusercontent.com/3850918/44264827-59910a00-a224-11e8-898d-f83d5b9eb7d0.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if the correct headers are sent (CORS issue)? The problem with infinite loop still persists though, I am working on it.

`
Failed to load https://gc2.mapcentia.com/wms/aleksandrshumilov/public?&service=WMS&request=GetMap&version=1.1.1&layers=public.urbanspatial_dar_es_salaam_luse_1982&styles=&format=image%2Fpng&transparent=true&tileSize=256&srs=EPSG%3A3857&width=1112&height=823&bbox=4325189.245516699,-790817.4946384338,4410187.220969815,-727909.8203597338: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://vidi.alexshumilov.ru' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**Comment by sashuk** [comment]
Whenever the WMS layer is created which has the singleTiled enabled, the [L.NonTiledLayer.wms](https://github.com/ptv-logistics/Leaflet.NonTiledLayer) is returned, according to the GC2 

https://github.com/sashuk/vidi/blob/4f4ad2635d7ab4ec1d4de8bca4837c233a35c518/public/js/gc2/geocloud.js#L575

The returned layer does not have the `setUrl()` method (as, according to the https://github.com/ptv-logistics/Leaflet.NonTiledLayer/blob/master/src/NonTiledLayer.js#L9 , it is not extended from the `L.TileLayer` which has the `setUrl()` method), so the error when accessing the non-existing `setUrl()` method was causing the loop.

Now the check for existence of `setUrl()` is implemented in https://github.com/sashuk/vidi/commit/0e2ee2c24e30e6ade8d3996e8579478a2fa6a2f9, but this makes the cache busting for non-tiled WMS layers to be impossible. So, there is a question: does WMS always returnes the actual big tile for non-tiled layer, so the caching is not really needed for non-tiles layers?

**Comment by mapcentia** [comment]
@sashuk "does WMS always returnes the actual big tile for non-tiled layer, so the caching is not really needed for non-tiles layers?"
Thats right. There is no need for caching big tiles. These will a arbitrary extent, so caching makes no sense.

**Comment by sashuk** [comment]
@mapcentia Thanks! Then this will work like it is now. 

https://github.com/sashuk/vidi/blob/e390a786b9d9695793f2dc03f304cce581f416e6/browser/modules/switchLayer.js#L158-L163

Could you please add specific headers in order to allow requests for WMS single tile layers?

![cors](https://user-images.githubusercontent.com/1390758/44334083-30ca7800-a4a3-11e8-9ac4-86e046b1870d.png)

**Comment by mapcentia** [comment]
@sashuk the double CORS header is removed
