### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#121]
@mapcentia Could you please tell if this is the correct confirm text?

https://github.com/sashuk/vidi/blob/47039e89f375af0a281a3388b29b17228d791a02/browser/modules/sqlQuery.js#L272

It translates as "Are you sure? Your changes will not be saved!", this confused me as changes will be saved normally.

**Comment by mapcentia** [comment]
@sashuk You're right, the text is wrong. It should be an English string in __("..."). Something like:
__("Are you sure you want to delete the feature?"). I'll add it to the Danish i18n file

**Comment by sashuk** [comment]
@mapcentia Thanks a lot! Implemented in https://github.com/sashuk/vidi/commit/26f84bbff9a39b0b17581ebf1b8c12e4a4372c25
