### ISSUE TITLE
The badge with number of layers in layer tree is missing in Embed template

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#124]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/3850918/44297223-21460600-a2ce-11e8-9b68-662a9444169d.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/3850918/44297226-3327a900-a2ce-11e8-8efc-777d00fdd055.png">

**Comment by sashuk** [comment]
There was a embed-specific style rule in the template that was hiding the badges. It was removed in https://github.com/sashuk/vidi/commit/e390a786b9d9695793f2dc03f304cce581f416e6

![badges](https://user-images.githubusercontent.com/1390758/44333679-1d6add00-a4a2-11e8-95a0-4c34351184d0.png)
