### ISSUE TITLE
When re-creating a Snapshot, the vector layers are loaded two times

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#125]
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/3850918/44297287-33747400-a2cf-11e8-903f-04651c54d4b5.png">

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/0a911eca1352fe7f4e5d59f14a4148725589f2c1
