### ISSUE TITLE
Can't dock the panel when using Offline Map on small screen

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#126]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/3850918/44297388-dda0cb80-a2d0-11e8-9472-a6b408858342.png">
This is  of course also a issue on big screens, but its more necessary to be able to do it on smaller ones.

**Comment by sashuk** [comment]
@mapcentia I've tried to dock it both in Chrome debugging tools and on Safari/Chrome on iPhone, in both cases docking seems to work.

![sliding](https://user-images.githubusercontent.com/1390758/44387017-dab70c80-a556-11e8-8358-720fa0aa8bbb.gif)

However, there is an issue linked to docking but it can be observed only in `default` template (https://github.com/sashuk/vidi/issues/131)

**Comment by sashuk** [comment]
@mapcentia Could you please check now? I've tried to dock the OfflineMap panel in `embed` mode on small screen and it seems like it is working

![toggling](https://user-images.githubusercontent.com/1390758/45338776-83d6ad00-b5c1-11e8-926e-9160a8824cdd.gif)

**Comment by mapcentia** [comment]
@sashuk It seems that you can't dock while rectangle tool is active on touch device. I've only tested in Chrome developer tools. Offline map doesn't work on IOS/Safari?

**Comment by sashuk** [comment]
@mapcentia Offline map works in iOS/Safari now (fixed in https://github.com/sashuk/vidi/commit/cc55fcf8102286e7621bacd4bfde289584df001b)

The described behavior was observed, working on it

**Comment by sashuk** [comment]
Actually all buttons do not work when the drawing is enabled, the `touchstart` event is assigned to all controls on the page (`DomUtil.js@243`).

**Comment by sashuk** [comment]
@mapcentia The reason why it was not possible to hide or close the `offlineMap` panel while drawing was found - Leaflet sets the `touchstart` event handlers for all elements and the `click` event is blocked. 

What was done: the hide and close buttons now react to `touchstart` events as well, also the `offlineMap` panel is automatically hidden when the drawing starts and automatically shown when the drawing ends (as in GIF below).

Implemented in https://github.com/sashuk/vidi/commit/382cfff9eac82100f4b9f18ebc56c24c2c2edc62

![offlinemap](https://user-images.githubusercontent.com/1390758/45533469-550f3f80-b82a-11e8-996d-6e3d5268271b.gif)
