### ISSUE TITLE
New measurement tool should change style or icon between enabled/disabled

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#128]
Also there is something wrong with the styling on master branch
![image](https://user-images.githubusercontent.com/3850918/44331304-7ff3b700-a469-11e8-90c6-c498f679898f.png)

**Comment by sashuk** [comment]
Both `default` and `embed` templates have the same icon set for enabled / disabled state of the measurements tool (`fa-ruler` / `fa-ban`). Implemented in https://github.com/sashuk/vidi/commit/9efc26d14b5f29239f0f1bc816ed5e5af2cde6b6

![measurements](https://user-images.githubusercontent.com/1390758/44336277-97529480-a4a9-11e8-9c74-eaa34653bc72.gif)

**Comment by mapcentia** [comment]
@sashuk Could you update master branch with?

**Comment by sashuk** [comment]
@mapcentia The pull request was added https://github.com/mapcentia/vidi/pull/44

**Comment by sashuk** [comment]
The new look:

![measurements](https://user-images.githubusercontent.com/1390758/44728958-47f70e80-ab10-11e8-9aa5-60558c3dbe5e.gif)
