### ISSUE TITLE
String fields in editor won't accept a number

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#129]
![image](https://user-images.githubusercontent.com/3850918/44337681-bfc39a00-a47b-11e8-9ec1-fa446c6f8102.png)

**Comment by sashuk** [comment]
@mapcentia I've reconstructed this situation - the `public.test` point layer (https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.3034/-6.8409/v:public.test) now has the **String value field** which can not be NULL

When the `0` is entered in **String value field**, the server returns the `SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "stringfield" violates not-null constraint`. The strange thing is that the payload which is sent to the backend is correct (the `stringfield` is sent as string value):

```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{
  "id":"111",
  "name":"2",
  "image":null,
  "bool":null,
  "date":null,
  "namewithenumnames":null,
  "stringfield":"0"
},"geometry":{"type":"Point","coordinates":[39.225998,-6.757352]}}]}
```

If any other character is entered as `stringfield`, it works (any other number works as well). Besides the actual error with client-validation in this issue I think this moment should be discussed as well.

**Comment by sashuk** [comment]
@mapcentia Could you please provide link to the app where the form validation is broken for string fields? I've tried to recreate the settings with string field for `public.test` point layer (https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.3034/-6.8409/v:public.test), the `0` is correctly validated on client-side.

**Comment by mapcentia** [comment]
@sashuk https://vidi.gc2.io/app/vmus/public/#geodk.bright/24/9.4952/56.7919/public._2883_anlaeg_nivii

**Comment by sashuk** [comment]
@mapcentia I've tried to input number in fields, seems like it is working:

![editing](https://user-images.githubusercontent.com/1390758/44386386-ee617380-a554-11e8-815c-615f6c181622.gif)
