### ISSUE TITLE
Form validation in filters

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#134]
The filter value input should validate input (string, int, decimal). Also if you filter a string field, the list of operators should adapt (no <, > etc.)
![image](https://user-images.githubusercontent.com/3850918/44511718-b1ae8d00-a6b8-11e8-823f-d33b824979b5.png)

**Comment by sashuk** [comment]
@mapcentia Could you please clarify if only `string` and `integer` fields should be available for filtering?

**Comment by mapcentia** [comment]
@sashuk All field types should be available for filtering. But you should not be able to input a string if the field is a numeric type.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! However, do `date`, `boolean`, `bytea`, `hstore` and `geometry` fields should be used in filters, as they require custom widgets (`date` - date picker, `boolean` - checkbox etc.)?

So, the list of allowed expressions for specific data types is:

- `integer` | `decimal` : `=`, `<>`, `<`, `>`, `<=`, `>=`
- `string` : `=`, `<>`, `like`

**Comment by mapcentia** [comment]
@sashuk I guess its the base64 encoding of the SQL that does it:
With base64:
http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov?q=U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoIGRlY2ltYWx2YWx1ZSA+IDEuMjYgKSBMSU1JVCA1MDA=&base64=true
Without: 
http://gc2.mapcentia.com/api/v1/sql/aleksandrshumilov?q=SELECT%20*%20FROM%20public.test%20WHERE%20(%20decimalvalue%20%3E%201.26%20)%20LIMIT%20500

This is the decoded SQL string on the server:
SELECT * FROM public.test WHERE ( decimalvalue K��� HSRU L

We use base64 encoding to "cheat" threat filters in firewalls, which filter SQL like strings.

It may be some issue with the base64 encoding in JavaScript? Could we use some other encoding metode?

**Comment by sashuk** [comment]
@mapcentia Could you please specify if `date`, `boolean`, `bytea`, `hstore` and `geometry` fields should be used in filters, as they require custom widgets (`date` - date picker, `boolean` - checkbox etc.)?

**Comment by sashuk** [comment]
Turned out that the reason was spaces after and before parenthesis in the `WHERE` clause:

- `SELECT * FROM public.test WHERE (decimalvalue > 1.26)` works
- `SELECT * FROM public.test WHERE ( decimalvalue > 1.26 )` does not work

Fixed in https://github.com/sashuk/vidi/commit/6cbbc9a2b4ae22405a7a5a8eb14d1d31458eadf3

**Comment by mapcentia** [comment]
@sashuk date, boolean fields should also be used. For date it could be nice with a date picker

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
Seems like it is time to implement the application-wide system of controls that are selected according both to the **field type** and **meta settings** (like `<select/>` for string field)

**Comment by sashuk** [comment]
@mapcentia The Date and Boolean control was implemented in https://github.com/sashuk/vidi/commit/b008a5701a07a4c243237178e6c93f167559342c and  https://github.com/sashuk/vidi/commit/5fbb6020e3889f975776a8525ac1e716b96408ef

Testing will be implemented within the https://github.com/sashuk/vidi/issues/133 issue.

![controls](https://user-images.githubusercontent.com/1390758/44779988-77128c00-abb3-11e8-8121-837b3013795d.gif)
