### ISSUE TITLE
When printing with vector layers, it hangs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#136]
This seems to be a regression.
![image](https://user-images.githubusercontent.com/3850918/44581380-bf8a0e00-a79d-11e8-9c58-445e2452323b.png)

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/068bce507618c0035db4ba6ee86dc532ac02da31
Test was added in https://github.com/sashuk/vidi/commit/e359b196467787f7d3cb5bf82aae0a9f51b4fc0a
