### ISSUE TITLE
Base 64 encoding issue

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#137]
Consider this SQL to be sent:

`SELECT * FROM public.test WHERE (date > '2018-08-01T11:11') LIMIT 500`

This SQL is base64-encoded as:

`U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA+ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw`

However, when server receives the base64 string, it tries to URL decode it, so the `+` **becomes a whitespace**, which breaks the actual parameter as it is invalid base64 string. Server should not URL decode base64-encoded queries.

**Comment by sashuk** [comment]
@mapcentia Could you please check the if the API correctly parses passed string? The things is that the base64 string is correctly passed down to the 

https://github.com/sashuk/vidi/blob/3f2bef2bbe644740f8b313f5a82803b27cc62b44/controllers/gc2/sql.js#L20

and it seems like the `config.host + "/api/v1/sql/" + userName` does not decode this string correctly afterwards. The passed string needs to be URL decoded and then base64 decoded.

Thw flow:

Vidi front-end

`SELECT * FROM public.test WHERE (date > '2018-08-01T11:11') LIMIT 500` :arrow_right: `U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA+ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :arrow_right: `U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA%20ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :email: 

Vidi back-end

`U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA%20ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :arrow_right: `U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA+ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :arrow_right: `U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA%20ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :email: 

GC2 back-end

`U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA%20ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw` :question:

**Comment by mapcentia** [comment]
@sashuk So the GC2 should not URL decode base64 strings?

**Comment by sashuk** [comment]
@mapcentia Seems like the string is decoded twice: from **%20** to **+** and from **+** to white space

**Comment by mapcentia** [comment]
@sashuk https://github.com/mapcentia/geocloud2/blob/master/app/api/v2/Sql.php#L112

**Comment by sashuk** [comment]
If instead of 

https://github.com/sashuk/vidi/blob/3f2bef2bbe644740f8b313f5a82803b27cc62b44/controllers/gc2/sql.js#L20

the `q` parameter is encoded twice (`var postData = "q=" + encodeURIComponent(encodeURIComponent(q)) + ...`) then it works.

**Comment by sashuk** [comment]
These queries should work:

1. **GET** http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov?q=U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoIGRlY2ltYWx2YWx1ZSA%2BIDEuMjYgKSBMSU1JVCA1MDA%3D&base64=true (the `q` is encoded once)

2. **POST** http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov (the `q` is not encoded at all)

```
{
  q: "U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoZGF0ZSA+ICcyMDE4LTA4LTAxVDExOjExJykgTElNSVQgNTAw",
  base64: "true",
  srs: "4326",
  lifetime: "0",
  client_encoding: "UTF8",
  key: "null",
  format: "geojson"
}
```

3. **GET** http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov?q=SELECT%20*%20FROM%20public.test%20WHERE%20(%20decimalvalue%20%3E%201.26%20)%20LIMIT%20500 (the `q` is encoded once)

4. **POST** http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov (the `q` is not encoded at all)

```
{
  q: "SELECT * FROM public.test WHERE (date > '2018-08-01T11:11') LIMIT 500",
  base64: "true",
  srs: "4326",
  lifetime: "0",
  client_encoding: "UTF8",
  key: "null",
  format: "geojson"
}
```

However, the **1** query does not work, unless the `q` is encoded **twice**, which is not correct by API design and is not obvious. So the flollowing request works (although it should not): http://gc2.mapcentia.com/api/v2/sql/aleksandrshumilov?q=U0VMRUNUICogRlJPTSBwdWJsaWMudGVzdCBXSEVSRSAoIGRlY2ltYWx2YWx1ZSA%252BIDEuMjYgKSBMSU1JVCA1MDA%253D&base64=true

I will deploy the geocloud locally in order to test it against cases listed above

**Comment by sashuk** [comment]
@mapcentia By the way, should the `api/v2` used or the `api/v1` should be tested as well?

**Comment by sashuk** [comment]
@mapcentia The `geocloud.js` was fixed according to 

https://github.com/mapcentia/geocloud2/blob/master/app/api/v2/Sql.php#L112

in https://github.com/sashuk/vidi/commit/55112aec56cd99587c6efaa11ad501c06de91615. The necessity of inner encoding (`encodeURIComponent(sql)`) in 
https://github.com/sashuk/vidi/blob/c0cff95aa176f2c0675e5026617ce5bae3d6c2cd/public/js/gc2/geocloud.js#L248 can be reduced, however, now it corresponds to the server-side code and it works (tests were implemented in https://github.com/sashuk/vidi/commit/c0cff95aa176f2c0675e5026617ce5bae3d6c2cd


https://github.com/sashuk/vidi/blob/c0cff95aa176f2c0675e5026617ce5bae3d6c2cd/test/puppeteer/layerTree.filters.test.js#L172-L191)

![filters](https://user-images.githubusercontent.com/1390758/44850365-90890600-ac8f-11e8-8f43-b611ab287b81.png)
