### ISSUE TITLE
The groundwater measurements extension (visualizing data across the time)

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#138]
The new extension is for a company working with groundwater measurements in time series. The data is bore hole locations and measurements of chemical components in the ground water over time. There can be up to 200 different components. When you click a point in the map, a popup is shown with a list of measured component (+ water level). They need to chart the measurements on a arbitrary number of charts (x: time, y: concentration/level). So on the panel you should be able add so many charts you need. Then you will add measurements from the popup to the charts. I was thinking about some drag n drop from popup to whatever chart you will use. You should be able to plot so many time series on the same chart as you like. Also different types of measurements with different units. So the chart must handle multiple y-axis. [Plot.ly ](https://plot.ly)seems to be good choice.

Each bore hole can have multiple intakes (but typical only one). So each time series is an array of arrays. Position 0 is intake #1 (always there), position 1 is intake #2 and so on. I was think of bundling data, title and units up in a JSONB field in the database. Something like this:

The data is not yet structured this way, but I guess you can make some dummy data. I've made a skeleton extension: https://github.com/mapcentia/watsonc 
host: "https://watsonc.mapcentia.com"

![moagifmhpncolehf](https://user-images.githubusercontent.com/1390758/44778113-bbe7f400-abae-11e8-9223-bc67c20206ce.png)
![mblbfpdobabkpfke](https://user-images.githubusercontent.com/1390758/44778114-bbe7f400-abae-11e8-9115-6438dcec152a.png)

**Comment by mapcentia** [comment]
@sashuk This extension should have its own repo. It can only be used with a the clients database,

**Comment by sashuk** [comment]
@mapcentia Got it! Should the code base be private?

**Comment by mapcentia** [comment]
@sashuk No need for private repo

**Comment by sashuk** [comment]
@mapcentia Current progress:

![plotly](https://user-images.githubusercontent.com/1390758/45046345-73e23900-b0a8-11e8-9b2d-569260c3a088.gif)

Following questions have arised during integration:
- is the `x` axis always a datetime?
- are new chemical components will be new properties of measurement object (bore hole) like `zdvr90`?
- is the set of measured chemicals different for every bore hole and intake?

Proposed prototype:

![plots](https://user-images.githubusercontent.com/1390758/45047555-e99bd400-b0ab-11e8-80b9-f743b2228474.png)

**Comment by sashuk** [comment]
@mapcentia Please consider the https://vidi.alexshumilov.ru/app/watsonc/public/#stamenTonerLite/13/9.9221/57.0964/v:public.boreholes_time_series for testing

**Comment by mapcentia** [comment]
@sashuk Its seems to the way to go.

**Comment by mapcentia** [comment]
@sashuk About the questions:

- is the x axis always a datetime? **Yes**
- are new chemical components will be new properties of measurement object (bore hole) like zdvr90? **Yes**
- is the set of measured chemicals different for every bore hole and intake (so plots with user-defined axes can be kept for all measurements if they are)? **I'm not sure if they are different. But I guess its likely, that some borings doesn't have some measurements. I'll check up on that.**

**Comment by sashuk** [comment]
@mapcentia Thank you very much!

**Comment by sashuk** [comment]
@mapcentia Current progress:
- after selecting feature user can create plot, which is combintaion of `Y axes`. Initially created plot does not have `Y axes`, so user should drag-and-drop them in the feature popup;
- the feature popup displays existing plots in real-time and allows to add `Y axes` and to remove them by clicking on them inside of the plot popup panel;
- when another feature is selected, existing plots are redrawn according to selected feature data.

:grey_exclamation: Codebase is still in development and contains some bugs

Demonstration:
![plotting](https://user-images.githubusercontent.com/1390758/45090663-8a3cd300-b142-11e8-9179-76747f577080.gif)

**Comment by sashuk** [comment]
Current issues:
- conflicting with the editor extension
- popup restoration causes the loss of feature events handling

**Comment by sashuk** [comment]
@mapcentia Maybe there should be some kind of meta flag that sepcifies the preferred extension that should be used with the layer? So when `editor` and `watsonc` are used together, custom feature handling can be enabled for those layers that do need it?

**Comment by sashuk** [comment]
@mapcentia The `editor` extension is not enabled when the `watsonc` is, the popup event handling was fixed, properties that can be plotted are now detected dynamically.

Implemented in https://github.com/sashuk/watsonc/commit/74ad7a73324ac5483178111ce1271d683786b2ee, https://github.com/sashuk/watsonc/commit/d365c38c3023b562c37a796a886ef55a5b558d0c
