### ISSUE TITLE
Print doesn't keep custom layer order

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#139]
When you change the layer order in Vidi and make a print, the PDF will show the original order. I guess the order is stored in the browser. A suggestion: When hitting Print, create a temporary snapshot and create that server side. This way Print doesn't have its own state system.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/d7835234fcbb43699bdb3c5e9f9a791777c49abd (passing and applying the application state)

![order](https://user-images.githubusercontent.com/1390758/45707463-80d75000-bbb1-11e8-9b69-2e11f23263df.gif)
