### ISSUE TITLE
Edit doesn't work anymore

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#140]
Nothing happens when you click on plus-sign or the feature it self

**Comment by sashuk** [comment]
@mapcentia Could you please provide the link? If you have tested on [https://vidi.alexshumilov.ru](https://vidi.alexshumilov.ru), it could be the development bug while I was working on the `watsonc` extension, which can confict with the `editor` extension.

**Comment by mapcentia** [comment]
@sashuk Its working now
