### ISSUE TITLE
When opening table view, it loads the data from the server again

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#141]
When opening a table view, it loads the data from the server again and and puts when atop in a redish color. Its should build the table from the existing vector layer.
![image](https://user-images.githubusercontent.com/3850918/45093498-da9f3b00-b118-11e8-9e4b-6a26b2bf3567.png)

**Comment by mapcentia** [comment]
@sashuk A tentative fix: https://github.com/mapcentia/vidi/commit/6cf206b1e43a910fd91365a78005cc5cd775b206
It does only work if you switch the layer on, after Vidi is loaded. Not loading Vidi with the layer name in the URL

**Comment by sashuk** [comment]
@mapcentia Is it okay to use features of already loaded layer, so the additional data loading will be avoided (as it will use already loaded features), but keep custom vector layer for table view?

I propose to draw two vector layers with same features (the table view vector layer has the "reddish" style), as it does not mess up the feature event handling - the regular vector layer has its handlers assigned (`click` event with popup) and the table view vector layer has its handlers assigned as well (`click` event with custom popup and feature style change).

If single vector layer will be used for both feature display and table view handling, then drawn features will have less obvious event management, which probably be an overkill considering that only two modules deal with vector layer feature events (the `editor` and `layerTree`). The UX will be the same in both cases.

**Comment by mapcentia** [comment]
@sashuk The thing is that we're planning to use vector in bigger scale. Lets say we load 5.000 polygons in a layer. Thats may be the limit for the browser to handle. When the user opens the table view and the browser has 10.000 polygons to deal with. So for sake of optimization I would like only one vector layer - if its doable.

**Comment by sashuk** [comment]
@mapcentia Sure, I will implement it along with the regular vector layer processing! Indeed, even the polynomial complexity increase can be bad on large data sets.

**Comment by sashuk** [comment]
@mapcentia It is okay to reload layer after closing the table view (in order to return regular feature events handlers)? Current implementation of `gc2table.js` is suited for temporary layers like those from `sqlQuery`, so if it used for regular vector layers then the feature events processing breaks. If it is not, then I will alter the `gc2table.js`

**Comment by sashuk** [comment]
@mapcentia The table view relies entirely on existing (already loaded) vector layer.

Implemented in https://github.com/sashuk/vidi/commit/f2e1f1f0ee1602e0eb6b96de2a6bcd785cf260db
