### ISSUE TITLE
Snatshot play button never enables after re-creation

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#143]
Some times the Snatshot play button never enables after re-creation. Its seems to be an issue when having drawings. Also some times, when running a snapshot without drawings, it can load drawings from another snapshot.

1. Create snapshot with drawing.
2. Remove the drawing and create another snapshot.
3. Play the second, and the Play button gets "stuck".

It happens here: https://vidi-furesoe.mapcentia.com/app/furesoe/?config=vejstatus.json#luftfotoserier.geodanmark_2017_12_5cm/13/12.3628/55.7971/
As you can see, a JavaScript error is thrown:

![image](https://user-images.githubusercontent.com/3850918/45224367-19b8c200-b2ba-11e8-8d5d-cccc747da514.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/2fc13bc2e11ab8fbea0f9d8f3292c8506580c43a
