### ISSUE TITLE
Drawings sticks when running a snapshot

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#145]
If you have two snapshots: 1) without any drawings and 2) one with drawings.
If run number 2, the drawings are shown. When if you run number 1 the drawings are still shown.
I think the right way is to remove all existing drawings when running a snapshot.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/842f04e320ad5cb976f4ea8ed94210f646849db6

![drawing](https://user-images.githubusercontent.com/1390758/45349357-a11c7300-b5e3-11e8-800e-20d4ce86776c.gif)
