### ISSUE TITLE
Print stalls on installation with config

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#147]
Print stalls when using this:
https://dev.geofyn.dk/app/geofyn/?config=borgerkort01_dev.json

But works without config:
https://dev.geofyn.dk/app/geofyn/public

For testing:
host: https://geofyn.mapcentia.com
configUrl: "https://geofyn.github.io/mapcentia_vidi_config"

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/cd339228bee00cedbf05fe502efddfd56f90303b

Please try https://vidi.alexshumilov.ru/app/geofyn/?config=borgerkort01_dev.json for testing.
