### ISSUE TITLE
Starting Vidi with anchor and config results in no baselayer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#148]
Doesn't work:
https://dev.geofyn.dk/app/geofyn/?config=borgerkort01_dev.json#gc2_group._b_baggrundskort01.baggrundskort01/13/10.4166/55.3765/

Works OK:
https://dev.geofyn.dk/app/geofyn/public/#gc2_group._b_baggrundskort01.baggrundskort01/13/10.4166/55.3765/

This may be related to #147 

![image](https://user-images.githubusercontent.com/3850918/45348987-63522700-b5b0-11e8-974a-1d8dfab04fef.png)

**Comment by sashuk** [comment]
@mapcentia Could you please provide the `baseLayers` section of the `dev.geofyn.dk` configuration file?

**Comment by mapcentia** [comment]
"baseLayers": [
        {
            "id": "gc2_group._b_baggrundskort01.baggrundskort01", "name": "Topografisk kort", "db": "geofyn",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 21,
                "attribution": "Geofyn A/S"
            },
            "overlays": [
                {
                    "id": "tekster.tekster_samlet_wms_web", "db": "geofyn", "host": "https://geofyn.mapcentia.com",
                    "config": {
                        "attribution": "Geofyn A/S"
                    }
                },
                {
                    "id": "tekster.adgangsadresseinfo", "db": "geofyn", "host": "https://geofyn.mapcentia.com",
                    "config": {
                        "attribution": "Geofyn A/S"
                    }
                }]
        },
        {
            "id": "luftfotoserier.quickorto_2018_16cm",
            "name": "Luftfoto 2018 (foreløbig version, ikke målfast)",
            "db": "baselayers",
            "host": "https://gc2.io",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 20,
                "attribution": "&copy; SDFE & MapCentia ApS"
            }
        },
        {
            "id": "luftfotoserier.geodanmark_2017_12_5cm",
            "name": "Luftfoto 2017",
            "db": "baselayers",
            "host": "https://gc2.io",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 20,
                "attribution": "&copy; SDFE & MapCentia ApS"
            }
        },{"id": "_b_luftfotoserier.luftfoto2016", "name": "Luftfoto 2016", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2015", "name": "Luftfoto 2015", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2014", "name": "Luftfoto 2014", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2013", "name": "Luftfoto 2013", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2012", "name": "Luftfoto 2012", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2011", "name": "Luftfoto 2011", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2010", "name": "Luftfoto 2010", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2009", "name": "Luftfoto 2009", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2008", "name": "Luftfoto 2008", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2007", "name": "Luftfoto 2007", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2006", "name": "Luftfoto 2006", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2004", "name": "Luftfoto 2004", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2002", "name": "Luftfoto 2002", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1995", "name": "Luftfoto 1995", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1992", "name": "Luftfoto 1992", "db": "geofyn"},
 
        {"id": "i_gis.luftfoto_1986_88", "name": "Luftfoto 1986-88", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1981_83", "name": "Luftfoto 1981-83", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1977", "name": "Luftfoto 1977", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1968_72", "name": "Luftfoto 1968-72", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1963_65", "name": "Luftfoto 1963-65", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1954", "name": "Luftfoto 1954", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1945", "name": "Luftfoto 1945", "db": "geofyn"},
        {"id": "i_gis.digekort", "name": "Digekort", "db": "geofyn"},
 
        {"id": "osm", "name": "Open Street Map"},
        {"id": "stamenToner", "name": "Stamen Toner Dark"},
        {"id": "stamenTonerLite", "name": "Stamen Toner Light"},
        {"id": "kortforsyningen.dtk_skaermkort", "name": "Topografisk kort (Kortforsyningens skærmkort)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_skaermkort_daempet", "name": "Topografisk kort (Kortforsyningens skærmkort, dæmpet)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_skaermkort_graa", "name": "Topografisk kort (Kortforsyningens skærmkort, gråt)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_klassisk", "name": "Topografisk kort (Kortforsyningens 1:25.000, klassisk)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_daempet", "name": "Topografisk kort (Kortforsyningens 1:25.000, dæmpet)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_graa", "name": "Topografisk kort (Kortforsyningens 1:25.000, gråt)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_2cm", "name": "Topografisk kort (Kortforsyningens 1:50.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_1cm", "name": "Topografisk kort (Kortforsyningens 1:100.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d200", "name": "Topografisk kort (Kortforsyningens 1:200.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d500", "name": "Topografisk kort (Kortforsyningens 1:500.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d850", "name": "Topografisk kort (Kortforsyningens 1:850.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_lave_maalebordsblade", "name": "Topografisk kort (Kortforsyningens lave målebordsblade, 1928-1940)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_hoeje_maalebordsblade", "name": "Topografisk kort (Kortforsyningens høje målebordsblade, 1842-1899)", "db": "geofyn"}
    ],

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

**Comment by sashuk** [comment]
@mapcentia Could you please check with the latest codebase?

My config now includes provided base layers and, using these URLs:

https://vidi.alexshumilov.ru/app/geofyn/?config=borgerkort01_dev.json#gc2_group._b_baggrundskort01.baggrundskort01/13/10.4166/55.3765/

https://vidi.alexshumilov.ru/app/geofyn/public/#gc2_group._b_baggrundskort01.baggrundskort01/13/10.4166/55.3765/ 

Seems like it is working:

![check](https://user-images.githubusercontent.com/1390758/45865470-3a037900-bdb0-11e8-9512-584034b47f7e.gif)

**Comment by mapcentia** [comment]
@sashuk It working. Closing
