### ISSUE TITLE
Layer is sometimes not checked in layertree after refreshing of browser

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#150]
May be related to #142 
Before refresh
![image](https://user-images.githubusercontent.com/3850918/45360408-d028e980-b5cf-11e8-8888-7d92aaec6f13.png)
After refresh
![image](https://user-images.githubusercontent.com/3850918/45360435-e59e1380-b5cf-11e8-8dfd-091edf82b4db.png)

**Comment by sashuk** [comment]
@mapcentia After fixes in `layerTree` (https://github.com/sashuk/vidi/commit/cd339228bee00cedbf05fe502efddfd56f90303b) the https://vidi.alexshumilov.ru/app/geofyn/public/#stamenTonerLite/9/10.4494/55.2388/kb.fotos,puls.renseanlaeg,grukos.foelsommeindvindingsomraader,_l_map_generel.tekster_samlet_wms_web was refreshed multiple times without errors.
