### ISSUE TITLE
Better app version management

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#151]
The appVersion is read from a remote config json file. But some users have many config-files and some are not using remote configs. An idea is to load an appVersion file from Vidi's own public folder and create a Grunt job, which increases the version number in that file.

**Comment by sashuk** [comment]
The mechanism:
1. The version is stored in the `public/js/version.js` (JavaScript code needs to be evaluated);
2. The version is automatically stored in `version.js`, the `grunt-version` plugin automatically puts it there from `package.json`;
3. Version number is built using the **semver** standard;
4. The application check the version from publically available file on startup.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/108326e59841cb2fae859d3b92414c7ab8919f9a

**Comment by mapcentia** [comment]
@sashuk The problem is that we do a lot of updates of custom extensions. This is done by running `git pull` in a folder in the extension folder and then `grunt production`. But the grunt-version plugin requires that `version` in package.json is updated. I would like that the version number in version.json is a hash of js/bundle.js and is not tracked in Git. Can this be done?

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/69879335ec00c7e3765e8a009453d59858756e6f
