### ISSUE TITLE
watsonc module should have different behaviour

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#153]
The table has these fields:

watlevmsl
chlorid
jern
sulfat
nitrat

The first one is the water level and the next four is chemical samples. The fields are all JSON and all objects are in the form:

```javascript
{
  "unit": "mg/l",
  "title": "chlorid",
  "measurements": [[38, 39, 41], [29], [17]],
  "timeOfMeasurement": [["2009-08-19T08:25:00+00:00", "2013-05-28T13:20:00+00:00", "2017-05-08T12:23:57+00:00"], ["2016-12-29T13:18:00+00:00"], ["2016-12-29T13:55:00+00:00"]]
}
```

These are the ones we need to plot. But there will be coming more chemicals than the four, so it may be an idea not to hard code the fields names, but put then in the config.js

For the extension so far: You click at borehole A and drag some data to plot. When you click at borehole B and the plot changes for data at B.

This is not the behavior they want, but: The plots should stick. So you click at borehole A and plot. When you click at borehole B and the drag-area is empty. You then drag to plot and you can compare hole A and B. Either in the same plot or in two plots.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if there were any changes made to the schema, as the `GET https://vidi.alexshumilov.ru/api/meta/watsonc/public` results in empty meta?

**Comment by mapcentia** [comment]
@sashuk A borehole can have multiple "intakes". But most have only one.
The one in your example has three intakes. The outer array has three elements - one for each intake.

`timeOfMeasurement` and `timeofmeas` should be the same. My idea is to bundle an object with both time and measurements for plot. While `timeofmeas` can be used for overall filtering. That said, I can see the objects lacks `boreholeno`. It should be:
```
"chlorid": {
    "**boreholeno**": "1",
    "unit": "mg/l",
    "title": "chlorid",
    "measurements": [[38, 39], [29]],
    "timeOfMeasurement": [["1 Jan 2018", "2 Jan 2018"], ["2 Jan 2018"], ["3 Jan 2018"]]
  }
```
I'll add it

**Comment by mapcentia** [comment]
@sashuk A correction: `timeOfMeasurement` and `timeofmeas` in the objects **are not** the same.
timeOfMeasurement is for waterlevel only. I'll drop the field so timeseries are only encapsulated in the objects.

**Comment by sashuk** [comment]
@mapcentia Thank you very much for clarification!

**Comment by sashuk** [comment]
@mapcentia Am I correct that number of intakes should be the same for all measurements?

**Comment by mapcentia** [comment]
@sashuk I'm not sure. I have to ask the water guys

**Comment by sashuk** [comment]
@mapcentia Current progress:
- the plot now accepts multiple `x` and `y` axes, so one plot can contain data from multiple boreholes;
- plots are stored in the internal application state, so they are recreated after reload (not carrying the actual data in state, only the `gid` of corresponding borehole);
- different intakes are taken into account and are displayed when creating plots (intake index goes after the `#` sign);
- user is free to choose either to compare data from different boreholes using one or multiple plots.

![boreholes](https://user-images.githubusercontent.com/1390758/45832290-16025200-bd34-11e8-8b99-aa57c19e1115.gif)

Demo at https://vidi.alexshumilov.ru/app/watsonc/geus/#stamenTonerLite/15/9.9159/57.0722/v:geus.boreholes_time_series_with_chemicals

There are still some minor issues and edge case left, going to cover them tomorrow.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the `unit` check should be performed (for example, prohibiting user to put chlorid concentration and water level on the same plot)?

**Comment by mapcentia** [comment]
@sashuk You should be able to plot data with different units. In this case the plot should use mulitiple y-axises. Always only one x-axis (with time). This should dynamically ajust to min and max time of the ploted  data.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/20f01d0fe09ce924f7673db75432b342668278b8

`watlevmsl`, `chlorid`, `jern`, `sulfat` and `nitrat` are displayed (as well as any other measurement with correct data structure, measurements are not hard-coded), `minofbottom` and `maksoftop` were removed.

![chlorid](https://user-images.githubusercontent.com/1390758/45862740-b3499e80-bda5-11e8-86a4-f7ce1e09ce0b.gif)
