### ISSUE TITLE
Sub-layers group shows collapsed state after init, but sub-layer is shown 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#154]
Vidi is started and the sub-layer group is collapsed, but layers is shown:
![image](https://user-images.githubusercontent.com/3850918/45613605-2c27be00-ba67-11e8-9bff-93a994997953.png)

After toggling the sub-layer group, its works as expected:
![image](https://user-images.githubusercontent.com/3850918/45613608-2f22ae80-ba67-11e8-868c-181464a9bb22.png)

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/2fde7ab0756646debce2b6390dc86b94b0cc6c74

**Comment by sashuk** [comment]
@mapcentia While working on initially collapsed state, I am wondering about the arrows direction - I totally agree with you, but aren't they work like this already?

![arrows](https://user-images.githubusercontent.com/1390758/45697244-eae2fb80-bb97-11e8-931f-8e0b2a77bd0d.gif)

**Comment by sashuk** [comment]
@mapcentia Initially collapsed state implemented in https://github.com/sashuk/vidi/commit/f324a4fe9b99cf756b93f7c46889b86e4562dd8e

![collapse](https://user-images.githubusercontent.com/1390758/45697919-74df9400-bb99-11e8-96b6-273067d33264.gif)

**Comment by mapcentia** [comment]
@sashuk It looks right. I'm closing this
