### ISSUE TITLE
Refresh after sorting of layer tree with sub-layer-group fails

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#155]
Load Vidi with a sub-layer-group. Drag and drop sort any layer. Refresh browser and Vidi doesn't start. This is logged:
![image](https://user-images.githubusercontent.com/3850918/45614017-604fae80-ba68-11e8-8f6f-fc401b21350d.png)

**Comment by sashuk** [comment]
@mapcentia Could you please provide link to the errored application? Testing on https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/13/39.2963/-6.8335/ does not cause any errors, unfortunately.

**Comment by mapcentia** [comment]
@sashuk Right now is it only my local install. But I tried to log `notSortedLayersAndSubgroupsForCurrentGroup` out and the issue is clear. The code access a `layer` property, but its not set for one of the objects.

![image](https://user-images.githubusercontent.com/3850918/45619682-79615b00-ba7a-11e8-8efa-f3fc62e8eae0.png)
```
if (groupOrderItem.type === GROUP_CHILD_TYPE_LAYER) {
                    console.log(notSortedLayersAndSubgroupsForCurrentGroup);
                    for (let i = (notSortedLayersAndSubgroupsForCurrentGroup.length - 1); i >= 0; i--) {
                        let layerId = notSortedLayersAndSubgroupsForCurrentGroup[i].layer.f_table_schema + '.' + notSortedLayersAndSubgroupsForCurrentGroup[i].layer.f_table_name;
                        if (groupOrderItem.id === layerId) {
                            sortedLayersAndSubgroups.push(notSortedLayersAndSubgroupsForCurrentGroup.splice(i, 1).pop());
                            break;
                        }
                    }
                }
```

**Comment by mapcentia** [comment]
@sashuk This site does it: https://dev.envirogissolutions.co.za/app/envirogis/public
https://geocloud.envirogissolutions.co.za

**Comment by sashuk** [comment]
@mapcentia Thank you very much for the details!

Fixed in https://github.com/sashuk/vidi/commit/17ad2be65a453e9e3e330a75be59f36310360ca5
