### ISSUE TITLE
JavaScript error when switching on vector layer on some installations

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#156]
On my developer setup I get this, when switching on a vector layer:

![image](https://user-images.githubusercontent.com/3850918/45615109-e28da200-ba6b-11e8-8a1b-43ef1e2e75b3.png)
![image](https://user-images.githubusercontent.com/3850918/45615194-1668c780-ba6c-11e8-8867-3a57d04339fd.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if the code base is the latest one? Right now there is a guard for checking the existence of the `onEachFeature` handler.

https://github.com/sashuk/vidi/blob/2fde7ab0756646debce2b6390dc86b94b0cc6c74/browser/modules/layerTree/index.js#L582-L586

**Comment by mapcentia** [comment]
@sashuk The code was up-to-date, but the bundle.js file was not being updated. I delete it and new one had the check. Closing the issue
