### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#159]
On one installation the Force Offline Mode and New Feature controls are not shown. But on my develop setup it works alright. I've not observed this elsewhere. What can cause the controls not to render? Its using a remote config. It seems if I enables the modules in the config.js it works. But again it works on my dev setup and I can't see why this should matter.

https://vidi-furesoe.mapcentia.com/app/furesoe_ekstern/public/?config=fund.json

![image](https://user-images.githubusercontent.com/3850918/45846961-a25b4780-bd29-11e8-9070-2b21a43ec210.png)
![image](https://user-images.githubusercontent.com/3850918/45846969-a7b89200-bd29-11e8-8086-d55575f4bfdf.png)

**Comment by sashuk** [comment]
@mapcentia There should be some difference in configuration files, as according to the 

https://github.com/sashuk/vidi/blob/18b06f5e201c49be0ab95ce8849f0abe93260bee/browser/modules/layerTree/index.js#L157-L159

the `Toggle offline mode` control and `+ Add feature` button appear is the `editor` is in enabled extensions in `vidiConfig`.

Could you please check if the backend config has the `editor` enabled as well?

**Comment by mapcentia** [comment]
@sashuk The config/config.js hasn't editor enabled. Only in the remote: https://furesoe.github.io/vidi_configs/fund.json
But `window.vidiConfig.enabledExtensions` has editor:
![image](https://user-images.githubusercontent.com/3850918/45864594-bf6c3680-bd7a-11e8-9a38-432d7503e768.png)

**Comment by sashuk** [comment]
@mapcentia Thanks a lot, investigating!

By the way, am I correct that there could be situation when the application is compiled without `editor` (`extensions.browser` in backend-configuration file), but the client-configuration will require it? Should the user be notified about this?

**Comment by mapcentia** [comment]
@sashuk Moving
```
if (window.vidiConfig.enabledExtensions.indexOf(`editor`) !== -1) {
            editingIsEnabled = true;
        }
```
From `set` to `init` should do it. `set` runs before  `window.vidiConfig` is set.

**Comment by mapcentia** [comment]
@sashuk About enable not compiled extensions: Yes, its a good idea to notice about this.

**Comment by sashuk** [comment]
@mapcentia At the same time your local install works correctly, right?

**Comment by sashuk** [comment]
@mapcentia According to the codebase application initializes like this (in case if the config query parameter exists):

`init.init()` :arrow_right: `loadConfig()` :arrow_right: `init.render()` :arrow_right: `init.startApp()`

However, the module and extensions initializations happens only in `startApp()`, so by the time the `.set()` is called for all extension, the `vidiConfig` is already constant.

**Comment by sashuk** [comment]
@mapcentia Seems like it is working now?

![result](https://user-images.githubusercontent.com/1390758/45865883-8bf8ce80-bdb1-11e8-8007-7fa7a521eb6c.png)

**Comment by mapcentia** [comment]
@sashuk The window.vidiConfig is set from config/config.js here: https://github.com/sashuk/vidi/blob/develop/browser/index.js#L37
And from remote config file here: https://github.com/sashuk/vidi/blob/develop/browser/modules/init.js#L38
But in between the `set` function is run here: https://github.com/sashuk/vidi/blob/develop/browser/index.js#L128

**Comment by mapcentia** [comment]
@sashuk Is work after I move the check from set to init

**Comment by sashuk** [comment]
@mapcentia Sorry, I've completely forgot that the layerTree is not an extension but a native module! Could you please check if the `gc2` is working correctly, as the `POST https://vidi.alexshumilov.ru/api/sql/aleksandrshumilov` started returning `<h1>404 Not Found</h1>` suddenly.

**Comment by sashuk** [comment]
@mapcentia Check for editor module in layerTree was moved, also the warning is logged now if the non-compiled module needs to be enabled in https://github.com/sashuk/vidi/commit/7296144f87a3e7e1ebfa0828dbbfa23165fbd2bc
