### ISSUE TITLE
New pending vector features are not shown in Safari on IOS

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#16]
If you enable Force online mode and add a new vector feature, it is not shown in the map. After refreshing the browser, it will appear.

**Comment by sashuk** [comment]
@mapcentia Could you please check it again? I've just tested on iOS Safari.

![Screenshot](https://user-images.githubusercontent.com/1390758/40500879-c9b978a2-5fb8-11e8-9146-baf792702ed6.jpg)

**Comment by mapcentia** [comment]
Its working for me now. Closing
