### ISSUE TITLE
No layers is showing in Kepler.gl

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#161]
![image](https://user-images.githubusercontent.com/3850918/45949412-1765a000-bffc-11e8-8d18-468f68ab516f.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a9bb57c7515eb9d993ab70c79fb4fc7db5675233

![keplergl](https://user-images.githubusercontent.com/1390758/46010885-bff82a80-c0f6-11e8-9f5c-9ccfa0abc4e8.gif)
