### ISSUE TITLE
Severe regression due to print changes

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#162]
The extension module conflictSearch is configuring the print module with custom data. But it is not working after https://github.com/sashuk/vidi/issues/139
```
extensions: {
    browser: [
           {conflictSearch: ["index", "reportRender", "infoClick", "controller"]}
    ],
    server: [
           {conflictSearch: ["index"]}
    ]
}
```

**Comment by sashuk** [comment]
The `conflictSearch` module stopped working after commit https://github.com/sashuk/vidi/commit/7296144f87a3e7e1ebfa0828dbbfa23165fbd2bc

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/1906d634164b069df7a77bc6be7a320473f7a935

**Comment by mapcentia** [comment]
@mapcentia Sorry for the vague issue repport. Its was not that - I figured that one out. Its after you do a conflict search and hit Print. What I can tell, a error happens here: https://github.com/sashuk/vidi/blob/develop/browser/modules/print.js#L433
 
![image](https://user-images.githubusercontent.com/3850918/46108986-a7177400-c1df-11e8-86b2-6f651e62e39a.png)

**Comment by sashuk** [comment]
@mapcentia Thank you very much for the report! 

The error was observied when using polygon for conflict search - the `serializeLayers` crashes trying to process the polygon feature, investigating this case.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/f5a2439cde9e44a9cfaf48d58a0405335500fc8a

All drawing controls of the `conflictSearch` were checked

![conflictsearch](https://user-images.githubusercontent.com/1390758/46130284-7c72fd00-c26b-11e8-8fc4-ca50be0fdff0.gif)

**Comment by mapcentia** [comment]
@sashuk Its when using this Print button:
![image](https://user-images.githubusercontent.com/3850918/46130673-29cd1d00-c23a-11e8-8dff-e472e568f6a6.png)

**Comment by sashuk** [comment]
@mapcentia Got it!

**Comment by sashuk** [comment]
@mapcentia Printing for `conflictSearch` now works, problem was that the `conflictSearch` was not calling `print()` in async way. Fixed in https://github.com/sashuk/vidi/commit/9fea4fedc887b2f1a98eccd58a87d8b8593ac12f
