### ISSUE TITLE
Opacity slider on tile layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#165]
Each tile layer should have a opacity slider.
Some like: http://lizardtechblog.github.io/Leaflet.OpacityControls/ (the slider should be horizontal)
The slider should be in an expandable panel under the layer title - just like filters on vector layers.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the opacity value should stored in state and be kept after reload?

**Comment by mapcentia** [comment]
@sashuk Yes, it would be nice if its stored in state. And reset when using the reset button.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Current progress on opacity sliders:

![slider](https://user-images.githubusercontent.com/1390758/47726094-bed99080-dc94-11e8-92fc-c17c5f3c8b0e.gif)

Commits: https://github.com/sashuk/vidi/commits/opacity-slider. Opacity sliders need some testing and then they will be completed.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/904b764b31f7193fc2a0587e4a65c8c856f5f26a and https://github.com/sashuk/vidi/commit/f823946bd330dc502f98ea70361721e12ca77181
