### ISSUE TITLE
Dynamic load strategy for vector layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#166]
Some vector layers are big and we need to load just what is inside the viewport of Vidi. The SQL store is now running `SELECT * FROM my_table`, but we need something like:

```
SELECT *
FROM   my_table
WHERE  my_geom_field
    &&
ST_Transform(
    ST_MakeEnvelope (
        {minX}, {minY}, {maxX}, {maxY},
        4326),
my_table_srid
)
```
The SQL store should when be reloaded on the  Leaflet "moveend" event (when you pan or zoom). It could be nice with some buffer in the loaded vector data, so you pan a bit without trigger a reload.

The `{minX}, {minY}, {maxX}, {maxY}` is replaced in the geocloud.js API by bounds of the viewport:
https://github.com/sashuk/vidi/blob/master/public/js/gc2/geocloud.js#L246

`my_geom_field` and `my_table_srid` should be taken from Meta.

Dynamic load vs. static load, should be an option in GC2. I've added a new Meta property:

`meta.load_strategy=s|d`

You can set this now in GC2 Meta.

**Comment by sashuk** [comment]
Current progress: vector layers with dynamic loading are loaded dynamically and the table view is updated accordingly

![dynamicquery](https://user-images.githubusercontent.com/1390758/48200047-e9180600-e398-11e8-80aa-c413c14a5535.gif)

**Comment by sashuk** [comment]
@mapcentia Could you please set the `load_strategy` for `chemicals.boreholes_time_series_with_chemicals` to be dynamic (`d`)?

**Comment by mapcentia** [comment]
@sashuk Its done. I've added a version of the layer without the chemical fields, which now amounts to about 130

**Comment by sashuk** [comment]
@mapcentia Thanks!

**Comment by sashuk** [comment]
Tested on https://vidi.alexshumilov.ru/app/jupiter/chemicals/#geodk.bright/17/12.1641/55.8206/v:chemicals.boreholes_time_series_without_chemicals, getting to buffering issues

![boreholes](https://user-images.githubusercontent.com/1390758/48243122-929edc00-e419-11e8-9d13-82eff70dd1c4.gif)

**Comment by sashuk** [comment]
@mapcentia Is it okay if offline mode controls for vector layer that are dynamically loaded will display the notification with actual bounding box which is currently cached in servicew worker?

**Comment by mapcentia** [comment]
@sashuk Yes, its OK

**Comment by sashuk** [comment]
The warning was added for dynamic layers (`Dynamic layer is cached only withing last requested bounding box`)

![warning](https://user-images.githubusercontent.com/1390758/48340789-75327200-e6a6-11e8-973f-f14b9521e2b7.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/aba4a8cb6823bfaeceb53e3c20fe01fc0c7df143, https://github.com/sashuk/vidi/commit/2eac5cdf56093dd70eb51b8689d522b53ee9eb2a, https://github.com/sashuk/vidi/commit/9ad8b456a1db63c76ae2be6009b57ef9b5aa34bc

Main features:
- vector layers with dynamic load are cached within the latest request bounding box;
- service worker is aware of bounding box and caches the requested vector layers according to requested bounding boxes (if service worker has cached reply for `1 1 -1 -1` then he will return this reply if the offline mode is enabled and the requested bounding box is `0.5 0.5 -0.5 -0.5`)
- `reset`, `stateSnapshots`, `editor` modules  and `offline mode` controls support the dynamic loading of vector layers
