### ISSUE TITLE
New map controls

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#168]
1. Home Button: This enable users to return to Default Map Extent
2. Zoom to Previous Extent Button to navigate forward and Backward

Should be done on master branch

![image](https://user-images.githubusercontent.com/3850918/47634949-867e6900-db53-11e8-8532-e734d90607e1.png)

**Comment by sashuk** [comment]
For reference: https://github.com/cscott530/leaflet-history

**Comment by sashuk** [comment]
@mapcentia The home button:
![home_button](https://user-images.githubusercontent.com/1390758/48631253-1a2bb280-e9f9-11e8-8081-33a404819bcf.gif)

The Previous / next extent control:
![extent_navigation_default](https://user-images.githubusercontent.com/1390758/48631261-1f88fd00-e9f9-11e8-8957-c5663e6ebc8f.gif)

![extent_navigation_embed](https://user-images.githubusercontent.com/1390758/48631267-2283ed80-e9f9-11e8-8337-460532dbbd83.gif)

Implemented in https://github.com/sashuk/vidi/commit/6cc49a3a38fa54c0bcc8e196cbbbe75adeb95785 and https://github.com/sashuk/vidi/commit/9673f46a68669602f381756f6578aa704241a30c

Right now the functionality is merged with `develop`, should it be merged with `master` as well (you've mentioned that `develop` is going to be merged with the the `master` anyway soon)?

**Comment by mapcentia** [comment]
@sashuk I'll do some testing and when I think develop should be merged with master. And when call it a release.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia The feature is implemented (actually, the plugin was simple integrated) in the `develop` branch, closing issue for now
