### ISSUE TITLE
Clear Map Button

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#169]
Button to Clear Selected Records & Geometries and Info Windows and Map without resetting Map Extent.
![image](https://user-images.githubusercontent.com/3850918/47635200-77e48180-db54-11e8-8f81-07e3b18d5a62.png)

**Comment by sashuk** [comment]
@mapcentia Feature was implemented in https://github.com/sashuk/vidi/commit/b41e6699e5317057969534627c06b26f05e24e94:

![clear_map](https://user-images.githubusercontent.com/1390758/48631462-89a1a200-e9f9-11e8-98bd-13712796b2cb.gif)
