### ISSUE TITLE
In release 8, when selecting a vector feature, a info request is send to the tile layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#17]
Switch on a vector layer.
Select a feature in the map.
A SQL request is submitted to the tile version of the layer and the result is rendered.

**Comment by sashuk** [comment]
@mapcentia Am I correct that sqlQuery should not be called when the actual vector feature is clicked?

**Comment by mapcentia** [comment]
@sashuk You're correct. sqlQuery should only be called for visible tile layers.

**Comment by sashuk** [comment]
Issue is fixed, demo:

![Example](http://www.giphy.com/gifs/LTEsBEx5RJGJehpQ2S)

**Comment by sashuk** [comment]
Solved in https://github.com/sashuk/vidi/commit/5ebdab7d8ab92e2aec7da34b7626929abd2874c5

**Comment by mapcentia** [comment]
When the vector version of a layer is visible and you click besides a feature, it will still call the SQL API. This can be problem with point and line layers, which have a catchment buffer.
Try click right beside a line vector and you will get a info-click result.

**Comment by sashuk** [comment]
@mapcentia Am I correct that if both vector and tile version of the layer is displayed, then the SQL query should not work for the tile layer? As user can get feature data by clicking the actual vector feature.

**Comment by mapcentia** [comment]
Yes, you're correct.

**Comment by sashuk** [comment]
@mapcentia However, currently there can be only one type of layer displayed on the map - either tile or vector one, so showing tile and vector representation at the same layer is not possible. So, according to the previous comment, should the info click be disabled whenever at least one vector layer is displayed?

**Comment by mapcentia** [comment]
"should the info click be disabled whenever at least one vector layer is displayed?"
No

But if browser to this:
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#osm/13/39.3165/-6.8977/v:public.test_line

And click besides a line, it will send a SQL API request for the layer. It shouldn't do that because the tile version is not visible.

**Comment by sashuk** [comment]
@mapcentia Got it, thank you very much!

**Comment by sashuk** [comment]
Fixed in 30d78f41beaff55c559ea2ed09a3d5b1f37bd43e

![click](https://user-images.githubusercontent.com/1390758/40653455-cc465294-636d-11e8-9ea7-ee2f9566a302.gif)
