### ISSUE TITLE
Right align Info buttons

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#172]
Right align Info buttons and use a <button> instead of the badge. Also if a layer is only available as tile-layer, when don't show the type icon.

![image](https://user-images.githubusercontent.com/3850918/47717247-8a8ab380-dc45-11e8-8428-959286b58115.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/deb1202adfb19943f378e39f331c39a578aa5d19

Changes:
- if the layer is tile-only or vector-only, then icon is not shown;
- the `Add feature` and `Info` controls are right-aligned;
- `Info` control is `<a/>` now.

Could you please specify if vector-only layers should not have the icon as well as the tile-only ones?

![align](https://user-images.githubusercontent.com/1390758/47773300-9a2cf980-dd24-11e8-8684-87fde8ced59f.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if vector-only layers should not have the icon as well as the tile-only ones?

**Comment by mapcentia** [comment]
Its fine if vector layers doesn’t have the icon. Some users get confused about the icon

**Comment by mapcentia** [comment]
L

**Comment by mapcentia** [comment]
@sashuk 
If info is not available, the plusses are not aligned. Could you add a empty placeholder instead of "Info" so things are aligned.
Also the offline/online controls should not be shown for tile layers. Now they are just disabled.
And should the same controls not be enabled for vector layers?

![image](https://user-images.githubusercontent.com/3850918/47814074-09b6df00-dd4d-11e8-8b17-2d5f44ee49ec.png)

**Comment by sashuk** [comment]
@mapcentia Sure, I will add a placeholder and hide offline controls for tile layers. Controls for vector layers are disabled because the application has `Network status: offline`, this can be due to accessing the page via HTTP or because of service worker have not registered yet.

**Comment by sashuk** [comment]
@mapcentia Style adjustments were implemented in https://github.com/sashuk/vidi/commit/f4536e31b7af255dc0a6b9718620d87c10c034df

![style](https://user-images.githubusercontent.com/1390758/47841724-856c6680-ddf5-11e8-9deb-020d44c4b594.gif)
