### ISSUE TITLE
Offline mode is not displayed if one of layers has error in meta

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#174]
Consider https://vidi.alexshumilov.ru/app/geofyn/?config=miljoevagtfyn.json#stamenTonerLite/12/10.6897/55.3316/v:test.registrering

**Comment by mapcentia** [comment]
I see a lot of errors here: https://dev.geofyn.dk/app/geofyn/?config=miljoevagtfyn.json#gc2_group._b_baggrundskort01.baggrundskort01/8/10.4494/55.2388/
Layers should deafult to Tile.

![image](https://user-images.githubusercontent.com/3850918/47845546-a2894100-ddc5-11e8-980f-dc606b550114.png)

**Comment by sashuk** [comment]
@mapcentia Errors (red ones) were thrown because of the corresponding layer tree control could not be found in layer tree, and this is okay (all these three layer had `layergroup=null`, so now they are not processed, as they do not have corresponding layer tree controls).

The `try/catch` error was caused by missing layer type definition in the layer meta. The corresponding message is now displayed for such layers (and it is displayed only once).

All measures were taken in https://github.com/sashuk/vidi/commit/0452b5e1cef32e2b99f820e9f6d995778ffe8415
