### ISSUE TITLE
When zooming in Internet Explorer, the "ends" of a meaure line is fixed in the map

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#175]
![image](https://user-images.githubusercontent.com/3850918/47784681-98ecd400-dd06-11e8-99d5-260f082dc506.png)
![image](https://user-images.githubusercontent.com/3850918/47784735-c0dc3780-dd06-11e8-9f13-00e1ee41b2e6.png)

**Comment by sashuk** [comment]
The measurement is drawn using the SVG and its edge points are set using the `stroke-linecap="butt"` property.

```html
<svg pointer-events="none" class="leaflet-zoom-animated defs" width="1396" height="988" viewBox="-116 -82 1396 988" style="transform: translate3d(-116px, -82px, 0px);">
  <defs id="defs">
    <marker id="pathdef-145" viewBox="0 0 2 8" refX="1" refY="4" markerUnits="strokeWidth" orient="auto" class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0" fill="#ff0000" fill-opacity="1" markerWidth="4" markerHeight="4">
      <path d="M 0 0 L 0 8 L 2 8 L 2 0 z"></path>
    </marker>
  </defs>
  <g>
    <path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="1" stroke-width="4" stroke-linecap="butt" stroke-linejoin="round" fill="none" d="M353 424L508 349" marker-end="url(#pathdef-145)" marker-start="url(#pathdef-145)" stroke-dasharray="none" id="pathdef-145"></path>
  </g>
</svg>
```

**Comment by sashuk** [comment]
@mapcentia The measurement is drawn using the SVG and its edge points are set using the `stroke-linecap="butt"` property. Internet Explorer seems to mess up the edges for SVG `path`, so there are two options:
1. Do not enable `lineCap: butt` property for measurement in case of IE browsers;
2. Modify Leaflet code that is responsible for drawing shapes on the map via SVG and try to use existing workarounds for this.

```html
<svg pointer-events="none" class="leaflet-zoom-animated defs" width="1396" height="988" viewBox="-116 -82 1396 988" style="transform: translate3d(-116px, -82px, 0px);">
  <defs id="defs">
    <marker id="pathdef-145" viewBox="0 0 2 8" refX="1" refY="4" markerUnits="strokeWidth" orient="auto" class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0" fill="#ff0000" fill-opacity="1" markerWidth="4" markerHeight="4">
      <path d="M 0 0 L 0 8 L 2 8 L 2 0 z"></path>
    </marker>
  </defs>
  <g>
    <path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="1" stroke-width="4" stroke-linecap="butt" stroke-linejoin="round" fill="none" d="M353 424L508 349" marker-end="url(#pathdef-145)" marker-start="url(#pathdef-145)" stroke-dasharray="none" id="pathdef-145"></path>
  </g>
</svg>
```

Could you please specify which one is more preferrable?

**Comment by mapcentia** [comment]
@sashuk I guess this an issue for the Drawing module as well. I'm most for solution #1

**Comment by sashuk** [comment]
@mapcentia I was wrong, the reason is in `Leaflet.LineExtremities` module (they even have issue for it https://github.com/makinacorpus/Leaflet.LineExtremities/issues/10). This module is used only in one place, so the corresponding check for IE was implemented in https://github.com/sashuk/vidi/commit/fbc47a6d489c12d6b74d5643411344fc37dbafe6.
