### ISSUE TITLE
System fields starting with "gc2_" should be ignored in Editor

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#179]
GC2 added some system fields to tables. These fields start with `gc2_`
Editor should ignore these in the attribute form
![image](https://user-images.githubusercontent.com/3850918/48055237-6718b900-e1af-11e8-8da8-de5903dc9c98.png)
To add some system fields for test, you can start versioning of a table: http://mapcentia.screenstepslive.com/s/en/m/35406/l/391477-versioning-of-data-track-changes

**Comment by sashuk** [comment]
@mapcentia Could you please clarify if these fields should be displayed in quickview or anywhere else in the application, or they should be completely hidden from user?

![quickview](https://user-images.githubusercontent.com/1390758/48056845-9a7a3880-e1ed-11e8-9877-c65cd0c50548.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/e22ea2200d95147b1f8f165ee7c3bf253bfc3777
