### ISSUE TITLE
When correcting an error, other features with error is deleted

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#18]
1. Add two vector points and leave "id" field empty, so a Null violation error occurs.
2. On one feature, type in a number in "id" field and submit.
3. Now the other feature (still with error) disappear

**Comment by sashuk** [comment]
Fixed in 7cf493d2bd831e1159e985b6a7a4a81d169bc9ec

![Example](https://user-images.githubusercontent.com/1390758/40542374-85b6c80e-6052-11e8-9ae9-739caa318a31.gif)
