### ISSUE TITLE
Versioned vector layers should be loaded with WHERE clause 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#180]
Related to https://github.com/sashuk/vidi/issues/179
http://mapcentia.screenstepslive.com/s/en/m/35406/l/391477-versioning-of-data-track-changes
When a layer is versioned all changes are stored as "ended" rows in the table. When loading a versioned vector layer, it should be done with `WHERE gc2_version_end_date is null`
Meta property `versioning` tells whether the layer is versioned or not.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/e22ea2200d95147b1f8f165ee7c3bf253bfc3777
