### ISSUE TITLE
Area is calculated wrong when displaying km2

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#181]
This relates to both Measure and Drawing.
When displaying km2 the areas is wrong by x10 (1 km2 = 1.000 x 1.000 m):
![image](https://user-images.githubusercontent.com/3850918/48124090-cfcd6780-e27b-11e8-9721-8263a8665524.png)

When in m2 is right:
![image](https://user-images.githubusercontent.com/3850918/48124230-1753f380-e27c-11e8-8895-fd1b5289de2d.png)
Could you make a step in hectar (ha = 10.000 m2), which are widely used in Denmark.

**Comment by sashuk** [comment]
@mapcentia Fixed and implemented in https://github.com/sashuk/vidi/commit/a563e3145b9b2bfd24511c69d0b41e801c888db5

Area measurement `0-10000 m2`:
![measurements_m2](https://user-images.githubusercontent.com/1390758/48241670-d6daae00-e412-11e8-8470-b2931034a49f.png)

Area measurement `10000-1000000 m2`:
![measurements_ha](https://user-images.githubusercontent.com/1390758/48241668-d6daae00-e412-11e8-80a8-24fa6e57b745.png)

Area measurement `1000000-∞ m2`:
![measurements_km2_ha](https://user-images.githubusercontent.com/1390758/48241669-d6daae00-e412-11e8-98d2-357cfb7ee397.png)
