### ISSUE TITLE
If service worker doesn't start Vidi hangs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#188]
When a new version hash is generated Vidi will refresh. But I experience that the Service Worker doesn't start after the refresh and Vidi hangs

![image](https://user-images.githubusercontent.com/3850918/48539575-dda46d80-e8b7-11e8-93b8-d19ace2a0cf6.png)

**Comment by sashuk** [comment]
@mapcentia The reason of the error was that sometimes the `layerTree` was requesting the infromation from the service worker when he was already `registered` but not `activated` yet. Additonal checks were added in https://github.com/sashuk/vidi/commit/34b8cadd342cd1a7db353f85fb3fbcea7d64f9d7
