### ISSUE TITLE
Editing of polygon tile layers hangs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#19]
1. Switch on polygon tile layer
2. Change a feature (geom or attribute) and submit.
3. Now Vidi hangs.

Point layer works alright. Also adding a new feature to polygon works.

**Comment by sashuk** [comment]
The abortion (cancellation) of feature editing cases invalid layer reload

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/490b296c878096e208e4da64fc48103f46c461ed

![Example](https://media.giphy.com/media/7FfKLEH1Ir6fs1MTsX/giphy.gif)

**Comment by mapcentia** [comment]
@sashuk This seems to be a problem agian

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/9abe36f3eb17d0776b50f2624bef983f23e1b0dc
