### ISSUE TITLE
JS Error when using Citrix client

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#191]
Some users are using a Citrix client for accessing Vidi. I got a report, that when using Citrix, Vidi doesn't load and throws an error. The site in question is behind a cĺosed firewall, but I have access through a VPN. But I can't recreate the error and therefore I guess its something to do with Citrix.
The site doesn't use SSL and it seems that a Vidi site with SSL does work through Citrix.
The image shows the error from Chrome 70 in a Citrix client. Can you get a hint about whats wrong?
![image](https://user-images.githubusercontent.com/3850918/48760573-a282af80-eca6-11e8-9ad9-703f9a958e31.png)

**Comment by sashuk** [comment]
@mapcentia Seems like errors are caused by non-SSL connection (so, no service worker, including offline mode, layer caching, offline maps etc.). I will test Vidi in non-SSL environment so it will load normally, but without features that depend on service workers.

**Comment by mapcentia** [comment]
@mapcentia But Vidi does work without SSL. Here is what I see when I load the site (not using Citrix)
![image](https://user-images.githubusercontent.com/3850918/48763112-c8ab4e00-ecac-11e8-91e3-4162be8d4c7a.png)

**Comment by sashuk** [comment]
@mapcentia Assuming that SSL enabled, seems like the service worker is not activated correctly.

The only call of `getRegistrations()` in `layerTree` module is sorrounded with service worker checks 

```
if (`serviceWorker` in navigator && navigator.serviceWorker.controller) {
  navigator.serviceWorker.getRegistrations().then(registrations => { ... });
}
```

so it seems like either the codebase is stalled (checks were added not so long ago) or there are some security limitations or errors with SSL certificate, but this is highly unlikely.

So, the Citrix Receiver (https://www.citrix.com/products/receiver.html) is used to have remote connection to the virtual machine that has Google Chrome 70 onboard? Is the `vidi` hostname used for SSL connection as well?

**Comment by mapcentia** [comment]
@sashuk I just got a report about the error also happens outside Citrix. I aks the user to click on the links to bundle.js and take screenshot. The codebase is updated and Vidi works for me when I try.

![image](https://user-images.githubusercontent.com/3850918/48827227-f8218f80-ed6c-11e8-889b-ae1ec5273ba6.png)

**Comment by mapcentia** [comment]
@sashuk I'm closing this one. The user don't see the error this morning, so I guess its something regarding a stall codebase
