### ISSUE TITLE
Service Workers on map.gc2.io

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#192]
When using the get GeoJSON or Excel button on this site: https://map.gc2.io/app/demo_c/public/#osm/11/39.3287/-6.8191/public.roads
I get an error. If I `Bypass For Network` it works, so I guess its SW related. But Info Click is POSTing to the same SQL API and that works?

![image](https://user-images.githubusercontent.com/3850918/48768401-3fe6df00-ecb9-11e8-80bf-188cd95f5d33.png)

**Comment by sashuk** [comment]
@mapcentia Seems like it does not depend on the hostname, investigating

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/dd9b054a7dac553e6c80436a260ffd7b4ab0b988
