### ISSUE TITLE
Vidi doesn't start in IE11

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#193]
![image](https://user-images.githubusercontent.com/3850918/48827108-82b5bf00-ed6c-11e8-8a7d-8a2036524b3c.png)
But it does start in Edge 16, which also doesn't support SW
![image](https://user-images.githubusercontent.com/3850918/48827578-e5f42100-ed6d-11e8-8aa0-02917cc2f604.png)

**Comment by sashuk** [comment]
For reference: https://map.gc2.io/app/demo_c/public/

**Comment by mapcentia** [comment]
@sashuk I think its the Kepler.gl modul. We may have to pull that out and make a repo on its own

**Comment by sashuk** [comment]
@mapcentia The error was in setting the read-only property in strict mode (as it was suggested in first screenshot), fixing it now along with other errors in second screenshot

**Comment by sashuk** [comment]
@mapcentia The https://map.gc2.io/app/demo_c/public/ (https://vidi.alexshumilov.ru/app/demo_c/public/) now loads without errors (fixes in https://github.com/sashuk/vidi/commit/68eaa8e0531880bf510e8b1723e23ad2e67df3dd and https://github.com/sashuk/vidi/commit/ce7754a379013393064ec4e393cc24a9905f0516)

![k0dkxe5e48](https://user-images.githubusercontent.com/1390758/48859712-d1f60100-edf9-11e8-8fd2-1cea5c67ccd6.png)

The creation of KeplerGL in separate repo is in separate issue (#196)
