### ISSUE TITLE
After version hash is changes Vidi refreshes, but SW doesn't start after refresh

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#194]
SW starts after you hit F5. This is observed in Chrome. In FF it started in second attempt.
![image](https://user-images.githubusercontent.com/3850918/48829693-31f59480-ed73-11e8-8c03-3c5e306f5ab6.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if the `map.gc2.io` is currently up? I've checked the same configuration on the development host and it seems working, wanted to check if on the actual host:

![sw](https://user-images.githubusercontent.com/1390758/48894370-96047f80-ee7d-11e8-9ced-e15a6506f2a4.gif)

![502](https://user-images.githubusercontent.com/1390758/48894358-913fcb80-ee7d-11e8-8e59-f1a313d1ce15.png)

**Comment by mapcentia** [comment]
@sashuk its up again

**Comment by sashuk** [comment]
@mapcentia Thanks!

**Comment by mapcentia** [comment]
@sashuk Yes, indeed I get this
![image](https://user-images.githubusercontent.com/3850918/49002968-436ae200-f161-11e8-81db-4234118435e4.png)
Closing
