### ISSUE TITLE
KeplerGL should reside in separate repo

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#196]

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plugins virker ikke i IE](https://trello.com/c/viN1CMFZ/109-plugins-virker-ikke-i-ie)

**Comment by sashuk** [comment]
@mapcentia Is it okay to have separate submodules files (`.gitmodules`, the preferred Git way)? Right now there are two records:

```
[submodule "extensions/keplergl"]
	path = extensions/keplergl
	url = https://github.com/sashuk/keplegl.git
[submodule "extensions/watsonc"]
	path = extensions/watsonc
	url = https://github.com/sashuk/watsonc.git
```

The repo with KeplerGL was created at https://github.com/sashuk/keplegl

**Comment by mapcentia** [comment]
@sashuk Yes, its alright. Closing

**Comment by mapcentia** [comment]
@sashuk Your repo is called `keplegl`. Its should be `keplergl`

**Comment by sashuk** [comment]
@mapcentia Sorry, I will fix it right away!

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/799f1b57fe9846badf1fc85f995aa2385164b998
