### ISSUE TITLE
The layer offline/online remain disabled i Safari om both MacOS and IOS

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#197]
difficulties
![image](https://user-images.githubusercontent.com/3850918/48861472-ed461980-edc3-11e8-9074-065709354a59.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/653af90174ad4e7c973f40b343d06b8b4506b3a5
