### ISSUE TITLE
Editor seems not to handle decimal types

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#198]
Editor seems not to handle decimal types. When have a decimal type in a table, the value you put in the attribut form doesn't stick after you Submit
![image](https://user-images.githubusercontent.com/3850918/48861918-11eec100-edc5-11e8-8380-6aa8430b7c82.png)

**Comment by sashuk** [comment]
@mapcentia Both cases were checked - when user is logged in the `Awaiting login` case, both times the value entered in decimal field was remembered (either stored on a client-side in queue or saved on the server-side) (the `5.123` value was used, the `5,123` value (comma-separated) results in error, which is correct). Could you please provide the information if any error is displayed in the `layerTree` or provide temporary write access for user `aleksandrshumilov` for the `demo_c/public`?

The values is kept:

![error](https://user-images.githubusercontent.com/1390758/48896044-9dc62300-ee81-11e8-89d3-710544505b98.png)

Working with decimals in another theme:

![decimal](https://user-images.githubusercontent.com/1390758/48896057-a6b6f480-ee81-11e8-9c76-c22ed0e324e4.gif)

**Comment by mapcentia** [comment]
@sashuk Its working now. Can a input field be validate to decimal? Right now you can input a string and you'll get a database error

**Comment by sashuk** [comment]
@mapcentia Sure, I will implement the validation

**Comment by sashuk** [comment]
@mapcentia Decimals validation was implemented in https://github.com/sashuk/vidi/commit/0f7b0b4fd7c3c009a7bdeb2eeb6b536dd486bb43

![decimals](https://user-images.githubusercontent.com/1390758/48940726-a6872980-ef53-11e8-9df7-96794f097f84.gif)
