### ISSUE TITLE
When layer type is Both tile becomes default, but when checked it flips to vector

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#200]
Init
![image](https://user-images.githubusercontent.com/3850918/48866840-89781c80-edd4-11e8-974a-e32970fb18c9.png)
When checked
![image](https://user-images.githubusercontent.com/3850918/48866861-972da200-edd4-11e8-949a-37be395718b7.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/b410ec2ad6bf16e723026e2afd2c5422011ce2c1

![selector](https://user-images.githubusercontent.com/1390758/48897391-ecc18780-ee84-11e8-83d3-f2c9bc806042.gif)
