### ISSUE TITLE
You can only print one time. Second time it hangs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#201]
Second print after Node is started, the process hangs. I've also tested with the public https adresse instead of http://127.0.0.1:3000 with same result.
![image](https://user-images.githubusercontent.com/3850918/48892804-296a9000-ee3f-11e8-90f0-c0469d31f326.png)

**Comment by mapcentia** [comment]
@sashuk Its seems downgrading to Puppeteer 1.8.0 will fix it

**Comment by sashuk** [comment]
@mapcentia I've had to do the same thing in tests, as the latest `puppeteer@1.9.0` was resulting in `net::ERR_UNKNOWN_URL_SCHEME` errors for some network requests. I think the `puppeteer` version can be hardcoded for now as it is not used anywhere else, however, this issue will have to be resolved as part of #177

**Comment by sashuk** [comment]
Check this issue along with the #177

**Comment by sashuk** [comment]
@mapcentia The behavior described in the current issue is fixed by https://github.com/sashuk/vidi/commit/f602caf35ffdc5a2284b0d0278505aff9807b316, the test case `test page printing multiple times in a row` was added to the corresponding #177 issue
