### ISSUE TITLE
WatsonC: Some GUI changes

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#202]
- Enable Enter key for filter input fields
- Fix the height of dialog
- Align to the left
I'll get some input from a designer next week.
![image](https://user-images.githubusercontent.com/3850918/48937912-ddd3e700-ef0f-11e8-9a39-f1ab852277c7.png)

**Comment by sashuk** [comment]
@mapcentia Am I correct that the height of the dialog should have the fixed height equal to `max-height` of this dialog?

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/f482718bca4d0885c7cd98008d7976da9a8caec9 and https://github.com/sashuk/watsonc/commit/53c9f3d07da8917be7abd0e9c6729dadb5ad38bf

![styling](https://user-images.githubusercontent.com/1390758/48990635-238bec00-f16a-11e8-8a83-971660dc9630.gif)
