### ISSUE TITLE
WatsonC: new layer with boreholes

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#203]
We have another layer with boreholes. This layer should be treated like the existing one. Both layers should be visible at the same time and ploting should also work for this new one. The new one has only one measurement, which is waterlevel.
I've just added the water level for the old one (water level is not in the compund list and is now hardcoded): https://github.com/sashuk/watsonc/commit/65c1830e31528e4e625b0d69f89580c600f958c0
The new should have the same SVG styling as the old one regarding water level. But we need a indicator in the symbol showing this is from another layer.

The layer is `sensor.sensordata_without_correction` in the `watsonc` database

**Comment by sashuk** [comment]
@mapcentia Am I correct that it is required to add the layer from another database? As far as I understand, right now Vidi is able to add layers from another scheme of the same database, so the functionality of adding layers from another database should be added?

Also could you please tell  check if the ungrouped layers be displayed anyway in `layerTree` (all layers from the `sensor` scheme in `watsonc` database (https://vidi.alexshumilov.ru/api/meta/watsonc/sensor) have `layergroup=null`)?

**Comment by mapcentia** [comment]
@sashuk You're right - its in another database. I'll make it a foreign table in the jupiter database.

**Comment by sashuk** [comment]
@mapcentia Thanks!

**Comment by sashuk** [comment]
@mapcentia Thanks! Could you please set the layer for this meta to make it vector as well (not the `meta` is empty)?

**Comment by mapcentia** [comment]
@sashuk done

**Comment by sashuk** [comment]
@mapcentia Different display for layers was implemented in https://github.com/sashuk/watsonc/commit/331b32fee2f42fa3e564c87bd07786d38d03bdc9

![markers](https://user-images.githubusercontent.com/1390758/49060757-d41ced00-f249-11e8-99b9-b9c28dcc0426.gif)
