### ISSUE TITLE
Change Markers to Circle Marker regarding point vector layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#204]
Point layers should use circle markers instead of markers. Its becomes infective to displaying a lot of markers with shadows.
![image](https://user-images.githubusercontent.com/3850918/49069747-54cbf100-f22a-11e8-98fe-66f2b71331a0.png)
When editing point layers it should still use a marker for "handle":
![image](https://user-images.githubusercontent.com/3850918/49069896-b7bd8800-f22a-11e8-993b-6f2fa8210c88.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if `watsonc` extension should use circle markers (with different colors, though) as well?

**Comment by mapcentia** [comment]
@sashuk I don't think it can use circle markers, because the dynamic styling with the SVGs can only be done on Makers

**Comment by sashuk** [comment]
@mapcentia Vector with default markers now have `cirlceMarker` (custom vector layers like ones in `watsonc` have theirs custom representation), implemented in https://github.com/sashuk/vidi/commit/902676284cac26afa7ff6644b91030d0aefc1e98
