### ISSUE TITLE
Apply filters on vector layers before the layer is loaded

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#206]
Filters are a good way to limit the number of loaded objects. But you can only apply filters after the layer is fully loaded. Is it possible to set filters before swiching on layers?

**Comment by sashuk** [comment]
@mapcentia Sure, it will be implemented!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/13c3fe46c879a1dbeff03f269535d0ac0cfd6886

![prefiltering](https://user-images.githubusercontent.com/1390758/49137630-fc7b1900-f327-11e8-9681-6054fdaee43e.gif)
