### ISSUE TITLE
Load strategy as an option in layer tree

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#207]
You can set load strategy in GC2 Admin and that works fine. But you may want to change it while you are using Vidi. So can a widget for changing load strategy be added? Defaulting to whatever load strategy set in GC2 for the layer.

**Comment by sashuk** [comment]
@mapcentia Sure, it will be added to layers that have this option

**Comment by sashuk** [comment]
@mapcentia Could you please check if "Load strategy" translates as "Laad strategie"?

**Comment by sashuk** [comment]
For reference: https://github.com/sashuk/vidi/tree/optional-load-strategy

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/e101d0be5ed6b29ec35fb57d4efdfed59acc32d7, https://github.com/sashuk/vidi/commit/cc83527f4d949779b2de9c233b7ba6e8fbd7adf9

![dynamictoggle](https://user-images.githubusercontent.com/1390758/49876139-9d82cd00-fe1a-11e8-86ec-4ea70aaaa600.gif)

**Comment by mapcentia** [comment]
@sashuk The switch in layer tree only shows when layer is set to Dynamic. Its should also be possible to do it the other way around. Set the layer to Static and change to Dynamic

**Comment by sashuk** [comment]
@mapcentia So, any vector layer can be dynamic?

**Comment by mapcentia** [comment]
@sashuk Yes, the setting in GC2 is just the default when starting Vidi

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Load strategy is available for all vector layers, implemented in https://github.com/sashuk/vidi/commit/160bf867b825a1ff972a582178505b91ad085b2e
