### ISSUE TITLE
Editor depends on Service Workers. Warn users if they start editing in browser without support for SW

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#208]
If browser doesn't support SW you can still make edits. But you can't submit them to server, because layers will stay "offline". Warn users if they attempt editing in browsers without support for SW.

**Comment by sashuk** [comment]
@mapcentia Check was added in https://github.com/sashuk/vidi/commit/ad1879768f1eddb0508c7f7193cf1dbcbd35138e

<img width="1154" alt="screenshot 2018-11-28 at 15 47 10" src="https://user-images.githubusercontent.com/1390758/49136596-0b140100-f325-11e8-9121-edb7874f21a1.png">
