### ISSUE TITLE
New mode for double base-layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#209]
We have side-by-side baselayers. But we also need overlay base-layers, where the opacity of the top one can be changed. So if this mode is enabled the base-layer with option checked to the right will be on top and a with a slider the user can change the opacity.

**Comment by sashuk** [comment]
@mapcentia Am I correct that this option will be set in `meta` for base layer? Also, opacity should be applied only for the right-sided base layer?

**Comment by mapcentia** [comment]
@sashuk Both modes should be available always. So the user can choose between "side-by-side" or "overlay" in the base-layer dialog. So no meta info regarding this.
I don't mean the "right-sided" base layer but the one with the right option box checked. The two choosen base layers should be put under and over each other. The user can then change the opacity on the one on top. The idea is to compare to base layers - usually two arial ortho photos from different years. Hope is makes sense.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
UI prototype:

![proto](https://user-images.githubusercontent.com/1390758/49156038-5c3ce880-f357-11e8-9d83-683249af88a4.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/ff2607454a602dba91688aba31e66abeae2886af, https://github.com/sashuk/vidi/commit/2265103dfda9c58716bfaaef115c4f3c1cf26354, https://github.com/sashuk/vidi/commit/f27368473bc7e58ba95e9a1ba5ad82c2f97eb4ce, https://github.com/sashuk/vidi/commit/d9078cfcf61bdf6d6102f46df7c216ed62306329

![twolayersatonce](https://user-images.githubusercontent.com/1390758/49270937-83560000-f4a6-11e8-81cb-f6c73e6e722f.gif)
