### ISSUE TITLE
In Safari on IOS the green Online is not changing to red Offline when in Fly mode

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#21]

**Comment by mapcentia** [comment]
Strange. I'll try to upgrade IOS to latest. I suspect some issue with my device.

**Comment by sashuk** [comment]
@mapcentia Hope that helps! My device is iPhone 6, iOS 11.3.1

**Comment by mapcentia** [comment]
Still no luck with on my iPhone 7 with 11.3.1. I'll try on another iPhone. Closing
