### ISSUE TITLE
React error is when Vidi is build for production

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#210]
grunt production

![image](https://user-images.githubusercontent.com/3850918/49154249-36442380-f318-11e8-95fa-4c0da98475d6.png)

**Comment by sashuk** [comment]
@mapcentia Could you please present results of `npm list --depth=0` and `npm list -g --depth=0` commands for the host where it fails?

**Comment by mapcentia** [comment]
`npm list --depth=0`
+-- @turf/turf@5.1.6
+-- arrive@2.4.1
+-- async@2.6.0
+-- babel-cli@6.26.0
+-- babel-plugin-transform-object-rest-spread@6.26.0
+-- babel-preset-es2015@6.24.1
+-- babel-preset-react@6.24.1
+-- babel-preset-stage-0@6.24.1
+-- babelify@7.3.0
+-- backbone@1.3.3
+-- base64-js@1.2.3
+-- base64-url@1.3.3
+-- body-parser@1.18.2
+-- bootstrap@3.3.7
+-- bootstrap-select@1.12.4
+-- browserify@16.1.1
+-- browserify-fs@1.0.0
+-- bulk-require@1.0.1
+-- chai@4.1.2
+-- circular-functions@0.0.3
+-- cookie-parser@1.4.3
+-- cors@2.8.4
+-- crypto-browserify@3.12.0
+-- detect-browser@2.4.0
+-- dom-shims@0.1.4
+-- elasticsearch@12.1.3
+-- es6-promise@4.2.4
+-- express@4.16.3
+-- express-session@1.15.6
+-- fetch@1.1.0
+-- geojson-multiply@1.0.3
+-- UNMET PEER DEPENDENCY grunt@1.0.3
+-- grunt-bower-task@0.5.0
+-- grunt-browserify@5.3.0
+-- grunt-cache-bust@1.6.0
+-- grunt-contrib-cssmin@1.0.2
+-- grunt-contrib-handlebars@1.0.0
+-- grunt-contrib-less@1.4.1
+-- grunt-contrib-uglify@2.3.0
+-- grunt-contrib-uglify-es@3.3.0 (github:gruntjs/grunt-contrib-uglify#ccb95a70cad6a4e9e902d3bd5d0e38a4de09a1e1)
+-- grunt-contrib-watch@1.0.0
+-- grunt-env@0.4.4
+-- grunt-git@1.0.9
+-- grunt-inline@0.3.6 extraneous
+-- grunt-processhtml@0.4.1
+-- grunt-shell@1.3.1
+-- grunt-templates-hogan@0.3.0
+-- grunt-version@1.2.1
+-- grunt-watchify@0.1.0
+-- handlebars@4.0.11
+-- html-react-parser@0.4.7
+-- install@0.12.1
+-- ipaddr.js@1.6.0
+-- jquery@3.3.1
+-- jrespond@1.0.0
+-- js-cookie@2.2.0
+-- jsts@1.6.0
+-- karma@2.0.2
+-- karma-chai@0.1.0
+-- karma-chrome-launcher@2.2.0
+-- karma-mocha@1.3.0
+-- kepler.gl@0.0.27
+-- load-grunt-tasks@3.5.2
+-- localforage@1.7.1
+-- lz-string@1.4.4
+-- md5@2.2.1
+-- mocha@5.1.1
+-- moment@2.22.2
+-- mustache@2.3.0
+-- mutationobserver-shim@0.3.2
+-- nouislider@8.5.1
+-- npm@6.3.0
+-- nyc@12.0.2
+-- pg-escape@0.2.0
+-- plotly.js@1.40.1
+-- pretty-units@0.1.0
+-- proj4@2.4.4
+-- prop-types@15.6.2
+-- puppeteer@1.7.0
+-- react@16.5.1
+-- react-addons@0.9.1-deprecated
+-- react-bootstrap@0.32.4
+-- react-dnd@6.0.0
+-- react-dnd-html5-backend@6.0.0
+-- react-dom@16.5.1
+-- react-dropzone@5.1.0
+-- react-jsonschema-form@1.0.4
+-- react-plotly.js@2.2.0
+-- reactify@1.1.1
+-- reproject@1.2.0
+-- request@2.85.0
+-- require-globify@1.4.1
+-- semver@5.5.1
+-- serialijse@0.0.17
+-- showdown@1.8.6
+-- snackbarjs@1.1.0
+-- snapshot@0.0.0
+-- socket.io@1.7.4
+-- socket.io-client@1.7.4
+-- terraformer@1.0.8
+-- terraformer-wkt-parser@1.1.2
+-- underscore@1.8.3
+-- urijs@1.19.1
+-- utf8@3.0.0
`-- uuid@3.3.2

npm ERR! peer dep missing: grunt@~0.4.1, required by grunt-watchify@0.1.0
npm ERR! extraneous: grunt-inline@0.3.6 /root/vidi/node_modules/grunt-inline
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
npm ERR! peer dep missing: grunt@~0.4.1, required by grunt-watchify@0.1.0
npm ERR! peer dep missing: react@0.14.x - 15.x, required by deck.gl@4.1.6
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-tooltip@3.3.0
npm ERR! peer dep missing: react-dom@0.14.x - 15.x, required by deck.gl@4.1.6
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by react-tooltip@3.3.0

`npm list -g --depth=0`
/usr/lib
+-- grunt-cli@1.2.0
`-- npm@6.4.1

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

**Comment by sashuk** [comment]
@mapcentia Could you please specify if it is observed on all installations or on the specific one?

**Comment by mapcentia** [comment]
@sashuk I see it on more like these ones:
https://dev.geofyn.dk/app/test/public
https://map.gc2.io/app/demo_c/public

module.exports = {
    backend: "gc2",
    brandName: "Geo Fyn",
    gc2: {
        host: "https://geofyn.mapcentia.com"
    },
   print: {
        templates: {
            "geofyn": {
                A4: {
                    l: {
                        mapsizePx: [1060, 730],
                        mapsizeMm: [280, 192]
                    },
                    p: {
                        mapsizePx: [730, 1060],
                        mapsizeMm: [192, 280]
                    }
                },
                A3: {
                    l: {
                        mapsizePx: [1525, 1065],
                        mapsizeMm: [401, 282]
                    },
                    p: {
                        mapsizePx: [1065, 1525],
                        mapsizeMm: [282, 401]
                    }
                },
                A2: {
                    l: {
                        mapsizePx: [2185, 1525],
                        mapsizeMm: [576, 400]
                    },
                    p: {
                        mapsizePx: [1525, 2185],
                        mapsizeMm: [400, 576]
                    }
                },
                A1: {
                    l: {
                        mapsizePx: [3120, 2185],
                        mapsizeMm: [820, 576]
                    },
                    p: {
                        mapsizePx: [2185, 3120],
                        mapsizeMm: [576, 820]
                    }
                },
                A0: {
                    l: {
                        mapsizePx: [4430, 3120],
                        mapsizeMm: [1173, 825]
                    },
                    p: {
                        mapsizePx: [3120, 4430],
                        mapsizeMm: [825, 1173]
                    }
                }
            },
            "_conflictPrint": {
                A4: {
                    p: {
                        mapsizePx: [700, 500],
                        mapsizeMm: [190, 120]
                    }
                }
            }
        },
        scales: [200, 250, 500, 1000, 2000, 3000, 4000, 5000, 7500, 10000, 15000, 25000, 50000, 100000],
    },

    searchModules: ["google", "danish"],
    enabledSearch: "danish",
    searchConfig: {
        komkode: ["461", "420", "430", "440", "482", "410", "480", "450", "479", "492"],
        esrSearchActive: true,
        sfeSearchActive: true
    },

    extensions: {
        browser: [
		{conflictSearch: ["index", "reportRender", "infoClick", "controller"]},
                {vectorLayers: ["index"]},
                {skolevej: ["index", "controller"]},
		{coordinates: ["index"]},
		{streetView: ["index"]},
                {layerSearch: ["index", "controller"]},
                {ejendom: ["index"]},
                {session: ["index"]},
                {languages: ["index"]},
                {editor: ["index"]}

	],
        server: [
		{conflictSearch: ["index"]},
                {layerSearch: ["index", "indexInEs"]},
                {skolevej: ["index"]},
                {session: ["index"]}
	]
    },
    configUrl: "https://geofyn.github.io/mapcentia_vidi_config",

    enabledExtensions: [
		"coordinates",
                "streetView"
	],
    enabledPrints: ["geofyn"],
    aboutBox: "<h3>Velkommen til Geo Fyns Webkort, som er baseret på MapCentia GC2</h3><p>Det er her muligt at se en række baggrundskort, fx topografiske kort og historiske luftfoto-serier.</p><p>Ligeledes er det muligt at se en masse korttemaer, læse informationer om disse, samt udskrive kort.</p><p>For træk af data henvises til Geo Fyns dataportal: <a target='_blank' href='http://dataportal.geofyn.dk'>dataportal.geofyn.dk</a></p><p>Med Geo Fyns Webkort og Dataportal ønsker Geo Fyn at understøtte sin Vision 2018:</p><p>»Geo Fyn vil være det fælles brændpunkt i den strategiske brug af (geo)data på tværs af sektorerne i kommunerne og udstille data til gavn for borgere, uddannelsessteder, virksomheder, myndigheder, m.fl., så der skabes optimal samfundsmæssig nytte af kommunernes data.«</p><p>Geo Fyn er ikke ansvarlig for misbrug af oplysninger eller for fejl i de oplysninger, der stilles til rådighed.</p>",

   "baseLayers": [
        {
            "id": "gc2_group._b_baggrundskort01.baggrundskort01", "name": "Topografisk kort", "db": "geofyn",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 21,
                "attribution": "Geofyn A/S"
            },
            "overlays": [
                {
                    "id": "tekster.tekster_samlet_wms_web", "db": "geofyn", "host": "https://geofyn.mapcentia.com",
                    "config": {
                        "attribution": "Geofyn A/S"
                    }
                },
                {
                    "id": "tekster.adgangsadresseinfo", "db": "geofyn", "host": "https://geofyn.mapcentia.com",
                    "config": {
                        "attribution": "Geofyn A/S"
                    }
                }]
        },
        {
            "id": "luftfotoserier.quickorto_2018_16cm",
            "name": "Luftfoto 2018 (foreløbig version, ikke målfast)",
            "db": "baselayers",
            "host": "https://gc2.io",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 20,
                "attribution": "&copy; SDFE & MapCentia ApS"
            }
        },
        {
            "id": "luftfotoserier.geodanmark_2017_12_5cm",
            "name": "Luftfoto 2017",
            "db": "baselayers",
            "host": "https://gc2.io",
            "config": {
                "maxZoom": 21,
                "maxNativeZoom": 20,
                "attribution": "&copy; SDFE & MapCentia ApS"
            }
        },
        {"id": "_b_luftfotoserier.luftfoto2016", "name": "Luftfoto 2016", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2015", "name": "Luftfoto 2015", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2014", "name": "Luftfoto 2014", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2013", "name": "Luftfoto 2013", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2012", "name": "Luftfoto 2012", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2011", "name": "Luftfoto 2011", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2010", "name": "Luftfoto 2010", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2009", "name": "Luftfoto 2009", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2008", "name": "Luftfoto 2008", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2007", "name": "Luftfoto 2007", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2006", "name": "Luftfoto 2006", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2004", "name": "Luftfoto 2004", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto2002", "name": "Luftfoto 2002", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1995", "name": "Luftfoto 1995", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1992", "name": "Luftfoto 1992", "db": "geofyn"},
 
        {"id": "i_gis.luftfoto_1986_88", "name": "Luftfoto 1986-88", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1981_83", "name": "Luftfoto 1981-83", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1977", "name": "Luftfoto 1977", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1968_72", "name": "Luftfoto 1968-72", "db": "geofyn"},
        {"id": "i_gis.luftfoto_1963_65", "name": "Luftfoto 1963-65", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1954", "name": "Luftfoto 1954", "db": "geofyn"},
        {"id": "_b_luftfotoserier.luftfoto1945", "name": "Luftfoto 1945", "db": "geofyn"},
        {"id": "i_gis.digekort", "name": "Digekort", "db": "geofyn"},
 
        {"id": "osm", "name": "Open Street Map"},
        {"id": "stamenToner", "name": "Stamen Toner Dark"},
        {"id": "stamenTonerLite", "name": "Stamen Toner Light"},
        {"id": "kortforsyningen.dtk_skaermkort", "name": "Topografisk kort (Kortforsyningens skærmkort)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_skaermkort_daempet", "name": "Topografisk kort (Kortforsyningens skærmkort, dæmpet)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_skaermkort_graa", "name": "Topografisk kort (Kortforsyningens skærmkort, gråt)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_klassisk", "name": "Topografisk kort (Kortforsyningens 1:25.000, klassisk)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_daempet", "name": "Topografisk kort (Kortforsyningens 1:25.000, dæmpet)", "db": "geofyn"},
        {"id": "kortforsyningen.topo25_graa", "name": "Topografisk kort (Kortforsyningens 1:25.000, gråt)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_2cm", "name": "Topografisk kort (Kortforsyningens 1:50.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_1cm", "name": "Topografisk kort (Kortforsyningens 1:100.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d200", "name": "Topografisk kort (Kortforsyningens 1:200.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d500", "name": "Topografisk kort (Kortforsyningens 1:500.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_d850", "name": "Topografisk kort (Kortforsyningens 1:850.000)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_lave_maalebordsblade", "name": "Topografisk kort (Kortforsyningens lave målebordsblade, 1928-1940)", "db": "geofyn"},
        {"id": "kortforsyningen.dtk_hoeje_maalebordsblade", "name": "Topografisk kort (Kortforsyningens høje målebordsblade, 1842-1899)", "db": "geofyn"}
    ],


    extensionConfig: {
        layerSearch: {
            host: "172.17.0.4:9200"
        },
        conflictSearch: {
            startBuffer: -2,
            getProperty: true
        },
        skolevej: {
            host: "https://gc2.io",
            db: "dk",
            table: "fot.skoler"
        },
        "languages": {
   	    "da_DK": {
       	       "txt": "Dansk"
    	    },
    	    "en_US": {
               "txt": "Engelsk"
            }
        }
    }

};

**Comment by sashuk** [comment]
@mapcentia Thank you!

**Comment by sashuk** [comment]
@mapcentia Could you please confirm that you do observe the error on hosts `https://dev.geofyn.dk/app/test/public` and `https://map.gc2.io/app/demo_c/public`? I've checked them with Chrome 72 and the application loading happens as regular.

<img width="644" alt="screenshot 2018-11-30 at 09 52 04" src="https://user-images.githubusercontent.com/1390758/49263515-e6836a80-f485-11e8-8007-b1a91e478c12.png">
<img width="871" alt="screenshot 2018-11-30 at 09 51 34" src="https://user-images.githubusercontent.com/1390758/49263517-e6836a80-f485-11e8-8506-8237b637be9a.png">

**Comment by mapcentia** [comment]
@sashuk I just tried it with Chromium, which doesn't display the error. Its coming from the React plugin for Chrome. I guess its something we need to address, but for now I'm closing the issue.
