### ISSUE TITLE
When a layer type is set to Both, filters doesn't show

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#212]
This must be a regression after https://github.com/sashuk/vidi/issues/206
![image](https://user-images.githubusercontent.com/3850918/49205379-2297cc00-f3af-11e8-8d40-8806724efea8.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/665a600ba09f0995066255ccbdf498c090d0fc22
