### ISSUE TITLE
Offline layers stays offline between refreshes, but the widget shows Online

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#213]
This is after refresh
![image](https://user-images.githubusercontent.com/3850918/49291078-3de70200-f4a9-11e8-8f2a-06669c55d41d.png)
I think this is a regression bug

**Comment by sashuk** [comment]
For reference: only happens to dynamic layers

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/e7414ed3d4780306ab4592b0880293189ba175dd

![reload](https://user-images.githubusercontent.com/1390758/49632317-2de29b80-fa30-11e8-9470-d19a604fc4d4.gif)
