### ISSUE TITLE
Store in snapshot if a layer is offline or online layer 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#216]
Its seems that retsoring a snapshot will always try to load a vector from network.

**Comment by sashuk** [comment]
Restoring snapshot that has vector layer **Test** set as an offline:
1. Check if the cache has this layer cached:
1.1 If layer is cached, then set it initially offline
1.2 If layer is not cached, emit console warning that layer does not exist in cache, so it needs to be requested from the network and set to be offline afterwards

**Comment by sashuk** [comment]
@mapcentia The feature was implemented in https://github.com/sashuk/vidi/commit/fcbf20c0ed701728c4c7a0a3a6d7db367506f14d

![offlinemodeinsnapshot](https://user-images.githubusercontent.com/1390758/49779453-e72bc480-fd01-11e8-8753-5a3386abd11d.gif)
