### ISSUE TITLE
When removing a filter it removes the one above

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#217]
Here I want to remove gid=16 
![image](https://user-images.githubusercontent.com/3850918/49612688-c849cd00-f9a5-11e8-918a-c63946912896.png)
But its actual gid=14 that is removed
![image](https://user-images.githubusercontent.com/3850918/49612690-cbdd5400-f9a5-11e8-9da2-302e348bd63c.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/fb48c26e386ddfa9ad00bee1d58fcb1dd88cd45a

![filters](https://user-images.githubusercontent.com/1390758/49632774-e2c98800-fa31-11e8-9093-94b3eb451635.gif)
