### ISSUE TITLE
Edge 18: Assignment  to read-only property.... error

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#219]
Happens when applying filters. Consol output is not giving much:
![image](https://user-images.githubusercontent.com/3850918/49732802-0b46c180-fc80-11e8-8611-b49970f1bcc4.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if it can be observed somewhere? I've tried the **Edge 18**, vector filters seem to work

![edge](https://user-images.githubusercontent.com/1390758/49788381-1ef63480-fd21-11e8-82f3-e25e1d221236.gif)

**Comment by mapcentia** [comment]
@sashuk I get it here: https://map.gc2.io/app/demo_c/public/
Maybe its only after `grunt production`

**Comment by mapcentia** [comment]
@sashuk Works now in Edge
