### ISSUE TITLE
Warn when editing tile layers in Force offline mode

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#22]
Editing tile layers without network gives a warning. This warning should also be shown when in "Force offline mode"

**Comment by sashuk** [comment]
Implemented in f3b5adcb5a0f70d25530ba23d67a19665875e802

![confirmation](https://user-images.githubusercontent.com/1390758/40614216-7c5ba4d2-62b4-11e8-91bd-6c44330354e5.gif)
