### ISSUE TITLE
Tile filters throws uncaught error if filter doesn't include a "="

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#221]
This works:
```json
{
"Boliger": "anvgen=11"
}
```
This doesn't
```json
{
"Boliger": "anvgen>11"
}
```
A filter could be any valid SQL where clause

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/bc11c765d4443a588ea8767fc43d6a2bb01fc0ea, check was removed
