### ISSUE TITLE
Something stops script execution in Tile filters

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#222]
In this demo you see the Tile filter button at the layer "2002". This layers doesn't have any filters applied or is in "Single tile mode". The button is dead.

https://map.gc2.io/app/demo_c/public/#osm/12/39.2358/-6.8057/public.urbanspatial_dar_es_salaam_luse_2002

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/c93d054eb5465593d41ab17263a55eb83efc1c5c
