### ISSUE TITLE
Vidi doesn't start without Service Workers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#223]
Regression?: https://github.com/sashuk/vidi/issues/193
![image](https://user-images.githubusercontent.com/3850918/49876442-b479ed00-fe23-11e8-8709-82bdf1fcb6f3.png)

**Comment by sashuk** [comment]
@mapcentia Issue was fixed, but it will be closed after implementing tests for this issue.

**Comment by sashuk** [comment]
@mapcentia Test was added in https://github.com/sashuk/vidi/commit/98e00ca7c35e5f28d871ba3f54c125fa41b31124
