### ISSUE TITLE
Tile Filters are send to WMS back-end unaltered

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#224]
The filters:
```json
{
  "Filter A": "foo=1",
  "Filter B": "foo=2",
  "Filter C": "foo=3"
}
```
are send as:
`filters={"Filter A":"foo=1","Filter B":"foo=2","Filter C":"foo=3"}`
instead of:
`filters={"layer_name":["foo=1","foo=2","foo=3"]}`

**Comment by sashuk** [comment]
@mapcentia Sorry, forgot about it, fixed in https://github.com/sashuk/vidi/commit/c3781f7e842fd8574cde8ed3392d2b418fce035a
