### ISSUE TITLE
Save queries as "virtual" layers 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#226]
After you have made a query with the sqlQuery module, is should be possible to store the query as a new "virtual" layer. The new layer should be a vector layer, which acts like any other vector layer. But only with a selection of controls. All virtual layers is grouped in one group. See mock-up.
The virtual layers are ordinary layers with the same WHERE clause as used the sqlQuery. So if data are changed the virtual layer changes. Unless its offline. Virtual layers should be stored in snapshots.
I've made an  "exclude" function in `gc2table.js` where you can exclude results by unchecking rows in the table. (se mock-up). Its activated here: https://github.com/sashuk/vidi/blob/develop/browser/modules/sqlQuery.js#L213
If the user exclude a row, the WHERE clause should be append a `AND [key]<>[number]` or similar.

![image](https://user-images.githubusercontent.com/3850918/50074608-b3a6d980-01dc-11e9-9cea-f43fe322204a.png)

![image](https://user-images.githubusercontent.com/3850918/50074297-c240c100-01db-11e9-92f4-73eb734172b6.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the correct translation of "Create virtual layer" will be "Opret virtuelt lag"?

**Comment by sashuk** [comment]
@mapcentia Should application track enabled virtual layers in URL and allow enabling them from URL (for example, navigating to `https://somevidihost.com/app/test/public/#.../v:virtual_layer.abc123`)?

**Comment by sashuk** [comment]
Current progress:

![virtuallayers](https://user-images.githubusercontent.com/1390758/50136530-07262f80-0290-11e9-860b-b52ad95b490b.gif)

To do/test:
- creation of virtual layers, treating them as regular vector layers :white_check_mark: 
- multiple virtual layers
- page reload
- saving in snapshot
- offline and online mode

**Comment by mapcentia** [comment]
@sashuk "Opret virtuelt lag" is correct.
Virtual layers should be tracked in URL

**Comment by sashuk** [comment]
@mapcentia Please consider the following situation: advanced query was performed on two raster layers (screenshot below). Could you please specify if a single virtual layer has to contain features from both layers or every found layer should have a separate vector layer (`Polygon (t)` and `Test`)?

The thing is that the whole concept of the Vidi **layer** assumes that data is fetched from a single table in the database (in vector or tile form). So, fetching data from multiple layers will require major changes in the codebase (changing the way `geocloud.js`, `gc2table` etc. work). However, if we stick with the rule **one virtual layer - query to a single table in the database** then it will only require some changes in way offline mode is processed in service workers.

![query](https://user-images.githubusercontent.com/1390758/50322199-0843a080-04cc-11e9-96cd-0aadadc25d59.png)

**Comment by mapcentia** [comment]
@sashuk A virtual layer should only contain features from one layer. So the "Create Virtual Layer" button in a result tab is only for the specfic layer. The two other buttons (GeoJSON and Excel) work also only on the specific layer.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by mapcentia** [comment]
@sashuk Virtual layers should use the same `fieldconf` object as the parent layer. I believe it doesn't because pop-up and table is blank?
![image](https://user-images.githubusercontent.com/3850918/50341239-626d5180-051e-11e9-93ab-8918f4997f16.png)

**Comment by sashuk** [comment]
@mapcentia Got it, the `fieldconf` will be recreated

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/a1beab2bca312dc65eabc6d6bbc1eb9d051865cd, https://github.com/sashuk/vidi/commit/8d8e934bae40ced2e39fbf4dd1fb9f064f47b908, https://github.com/sashuk/vidi/commit/d9be5daa3ee6da240e2daa5e64955e6b0a2d5f65

![virtuallayers](https://user-images.githubusercontent.com/1390758/50355317-3665c680-0546-11e9-871d-4790622ec79e.gif)
