### ISSUE TITLE
Click on Clear Map button propagates to map and cause an Info click 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#230]
![image](https://user-images.githubusercontent.com/3850918/50214677-25b82380-0381-11e9-955b-dcf04dccc584.png)

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clear Map Button](https://trello.com/c/ZsWNCOhG/15-clear-map-button)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/272a3f5bf77da153dc773d7bd2cb556e84964419
