### ISSUE TITLE
If started with a non-existing basemap, Vidi will stall

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#231]
Start with something like this:
/app/mydb/public/#dummy/12/9.9186/57.052/

Vidi will then redirect to:
/app/mydb/public/
And stalls.

If you then refresh th browser Vidi will start alright

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/5083f63ce2ca7360fe021e3830d2cf0eaf598a97

![baselayers](https://user-images.githubusercontent.com/1390758/50278553-3333e300-043f-11e9-8020-86acdcf2f026.gif)
