### ISSUE TITLE
Clear map buttons doesn't clear out pop-up and vector from map

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#235]
![image](https://user-images.githubusercontent.com/3850918/50342893-415c2f00-0525-11e9-95a6-6054b35d5561.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check out the latest codebase? Seems like it works:

![clearmap](https://user-images.githubusercontent.com/1390758/50356147-e6d4ca00-0548-11e9-9497-f9ae78ac3212.gif)

**Comment by mapcentia** [comment]
@sashuk It works alright when `Activate advanced query` is on. But if you just click in map for info it doesn't work.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/75a9bbc1340994fd3bab1b1182339082e8ba5c72

![infoclick](https://user-images.githubusercontent.com/1390758/50775577-70490380-128e-11e9-86b0-f2cac30a301f.gif)
