### ISSUE TITLE
One click activation scheme 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#236]
Some modules - Draw and Print in standard, Streetview in extensions and a lot of custom ones - have a two click activation scheme: First (1) you click the Tab and then switch on the activation button: 
![image](https://user-images.githubusercontent.com/3850918/50791922-9a68e880-12c3-11e9-9eb2-c9da25b92f43.png)
New scheme to implement: One click activation scheme, the module is activated when clicking the Tab:
![image](https://user-images.githubusercontent.com/3850918/50792397-1c0d4600-12c5-11e9-8f6f-8fc47012eb77.png)
When clicking the tab the `reset:all` event should be fired and all modules, which can be activated, must do whatever necessary to reset state (because they can't no longer be manual reset).
Activatable modules should implement a standard method, which is called when their tab is clicked. Something like this:
```javascript
module.exports = {
   set: function (o) {},
   init: function () {
       backboneEvents.get().on("reset:all", function(){
           // Reset state
       };
   },
   activate: function() {
   // Empty for non-activatable modules
  }
}
```
This should be developed in a new branch.

**Comment by sashuk** [comment]
@mapcentia Please consider the following scenario:
1. The `draw` module is opened (= activated) and some features are drawn on the map;
2. The `print` module is opened (= activated) and `draw` module is reset, so all drawings are lost

Am I correct that drawings should not be deleted when the `print` module is activated as it is implemented now? The `reset:all` should not be called, the `deactivate:all` will be implemented instead. The typical module will look like this:

```javascript
module.exports = {
  set: function (o) {},
  init: function () {
    // Reset state and clear any effects of the module
    backboneEvents.get().on("reset:all", () => {});

    // Stop listening to any events, deactivate controls, but keep effects of the module until they are deleted manually or reset:all is emitted
    backboneEvents.get().on("deactivate:all", () => {});
  }

  activate: () => { /* Enable module controls (only for activatable modules) */ }
  deactivate: () => { /* Disable module controls (only for activatable modules) */ }
  reset: () => { /* Disable module controls and clean up any effects */}
}
```

**Comment by sashuk** [comment]
For reference: https://github.com/sashuk/vidi/commits/new-module-activation-system

**Comment by mapcentia** [comment]
@sashuk Using only events is a good idea. This way its also easier for a module to activate another - no need to `require`

**Comment by sashuk** [comment]
@mapcentia New module activation system was implemented in https://github.com/sashuk/vidi/commit/bce07a7399b923068eba524989d49f4754290f10, https://github.com/sashuk/vidi/commit/3ce8b2fc36ecf90ff01bbef6626045ef63ae31b7, https://github.com/sashuk/vidi/commit/826ef50aad70d87bb46448286fabcb462548a05e; test was added in https://github.com/sashuk/vidi/commit/881eb70816d69159a129e9cca92fc26175def47f.

Codebase was merged with `develop`.

![activation](https://user-images.githubusercontent.com/1390758/50879174-e86c1200-13d1-11e9-9d2f-7fbeedb6689c.gif)
