### ISSUE TITLE
New Info click scheme

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#237]
Simple Info click is default on (just point and click). When activating a module, which conflicts with Info click (like Draw), Info click is turned off.

New Info click scheme: Info click should behave like any other module, meaning it should not be default activated, but be activated when clicking the Info tab (referred to https://github.com/sashuk/vidi/issues/236) 
It should still have a switch between Simple and Advanced:
![image](https://user-images.githubusercontent.com/3850918/50793448-807dd480-12c8-11e9-85e1-8d49efe2c880.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/bce07a7399b923068eba524989d49f4754290f10

![activation](https://user-images.githubusercontent.com/1390758/50879179-ebff9900-13d1-11e9-9820-c916b9ad39d4.gif)
