### ISSUE TITLE
The config activateMainTab doesn't work any more

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#238]
There is a (not so much used) config called `activateMainTab`, which tells Vidi to activate a tab on startup. But I don't think it works in the new Vidi. Could you test it? And it should of course also activate the module now: https://github.com/sashuk/vidi/issues/236 

https://github.com/sashuk/vidi/blob/develop/browser/modules/init.js#L57

**Comment by sashuk** [comment]
@mapcentia The `activateMainTab` option support was checked (https://github.com/sashuk/vidi/commit/35167fd8b2ccaec1156f8ce7f16da4da3b681a84) and test was implemented (https://github.com/sashuk/vidi/commit/d2afcd3290d582eb8ea96ebed78f0c0fee463cfa)
