### ISSUE TITLE
When switching a Static layer to Dynamic in GUI, layer doesn't load new features

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#239]
When switching a Static layer to Dynamic in GUI, layer doesn't load new features when panning zooming.
If layer is set to Dynamic in GC2 it works.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/fee536a8b7f98d9cc84036924c7d4cb1dca7abee

![dynamicload](https://user-images.githubusercontent.com/1390758/50834986-60dcbf80-134d-11e9-99cf-041fa47eb8d4.gif)
