### ISSUE TITLE
Offline map should handle TMS layers and not only Google XYZ

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#24]
Try this:
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#geodk.bright/14/9.9021/57.0301/

And request a small area to cache. It will request something like this:
https://gc2.io/mapcache/baselayers/tms/1.0.0/geodk.bright/18/138284/-47506.png

It should be something like this:
https://gc2.io/mapcache/baselayers/tms/1.0.0/geodk.bright/18/138288/181872.png

TMS is the same as Google XYZ but with reversed y-axis

**Comment by sashuk** [comment]
Linked issue https://github.com/Leaflet/Leaflet/issues/6176

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/cbaf801989f76da5697825ac926c622a5318f0bd

Related issue https://github.com/Leaflet/Leaflet/issues/6176 is closed

![tiles](https://user-images.githubusercontent.com/1390758/42431649-71a126bc-8379-11e8-9a91-32ce7300df5e.gif)

**Comment by sashuk** [comment]
Tests are completed
