### ISSUE TITLE
WebGL layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#243]
Is it possible to add GeoJSON (and Vector tiles) as WebGL layers.
There is a Leaflet plugin for GeoJSON here: https://github.com/robertleeplummerjr/Leaflet.glify
And for Vector tiles MapBox has something: https://github.com/mapbox/mapbox-gl-js
For GeoJSON, is there any limitations compared to SVG render? Like no support for multipolygons with holes.
If it can be done (with or without limitations) an idea is an option for enabling WebGL on layers.

**Comment by sashuk** [comment]
@mapcentia According to the documentation the https://github.com/robertleeplummerjr/Leaflet.glify does not support lines, however, the [Mapbox GL library](https://github.com/mapbox/mapbox-gl-js) seems to be more mature and widely used (there are binding for Leaflet available https://github.com/mapbox/mapbox-gl-leaflet), however, it requires the Mapbox account.

I think that it will be better to start with https://github.com/robertleeplummerjr/Leaflet.glify, as the support for lines is expected soon and it is pretty lightweight and easy-to-use.

**Comment by mapcentia** [comment]
@sashuk Are you able to add line support to Leaflet.glify?

**Comment by sashuk** [comment]
@mapcentia Sure, the line support will be added!

**Comment by sashuk** [comment]
Lines are rendered now, but not multiple ones at the same time (https://github.com/sashuk/Leaflet.glify/commit/de38440827f6f9cf3145fcf7cc31248a71c7ddcc), working on it.

![linesandpolygons](https://user-images.githubusercontent.com/1390758/51557362-a786f980-1eb7-11e9-959f-60a617923f97.png)

**Comment by sashuk** [comment]
@mapcentia Line support was added (pull request https://github.com/robertleeplummerjr/Leaflet.glify/pull/20). While waiting for pull request approval moving to #244

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/7ebe74a690e352203d56fb71a0b628bdcb857459

![webgl](https://user-images.githubusercontent.com/1390758/53473854-7eedb300-3aa6-11e9-961a-3585406c7420.gif)
