### ISSUE TITLE
Snapping is not enable before you start editing an existing feature

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#246]
1) Create a new feature. Snapping is not enabled.
2) Start editing an existing feature. Snapping is enabled. But with is seems to use gridlines https://github.com/makinacorpus/Leaflet.Snap/#leafletsnapgridlines ?
3) Create a new feature. Snapping is now enabled - without gridlines?

**Comment by sashuk** [comment]
@mapcentia Snapping initialization was fixed when features are added in https://github.com/sashuk/vidi/commit/16b10157b7a2e7be38a867f605307545ca16130f

![snapping](https://user-images.githubusercontent.com/1390758/51320721-c2163880-1a9b-11e9-82ef-b89c14b32a7a.gif)
