### ISSUE TITLE
Protected tile layers requests routing

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#248]
Protected WMS layers requests result in `401` being routed through the WMS backend. The authentication mechanism has to be implemented in order to request protected WMS layers correctly.

Also, the caching has to be disabled when filters are set for the layer, consider

https://github.com/sashuk/vidi/blob/8910b65e0a69215ef3b35de8738e3297896f3d03/browser/modules/layers.js#L216

Implement test for this case

**Comment by mapcentia** [comment]
@sashuk Yes, I think the WMS understands the PHP session.

**Comment by sashuk** [comment]
@mapcentia Great, thanks!

**Comment by sashuk** [comment]
@mapcentia The proxy was created (only for authenticated users and for URLs that are targeted to the `config.host`) in https://github.com/sashuk/vidi/commit/3b2cae4aaf1bd5ba2c3420bc46bad2d67c54f72e

Tests are pending

![mapproxy](https://user-images.githubusercontent.com/1390758/51329917-69519a80-1ab1-11e9-85a7-78c5d827359e.gif)

**Comment by sashuk** [comment]
@mapcentia The proxy was created (only for authenticated users and for URLs that are targeted to the config.host) in https://github.com/sashuk/vidi/commit/3b2cae4aaf1bd5ba2c3420bc46bad2d67c54f72e, test was added in https://github.com/sashuk/vidi/commit/2535e8af541bda7647be70dd003cf35e9ad6ae15.
