### ISSUE TITLE
No filters at all on Tile layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#250]
![image](https://user-images.githubusercontent.com/3850918/51332887-e1519d80-1a7c-11e9-9bc2-9d26a5aaeb8f.png)
![image](https://user-images.githubusercontent.com/3850918/51332901-e9114200-1a7c-11e9-9c82-9af7df8f08d5.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/d8eb035ba361529598947eabc7e86acb22d13515
