### ISSUE TITLE
Service Workers error then clicking for info on a point layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#251]
Service Workers error then clicking for info on a point layer. It works when using Advanced Query. I guess its because the SELECT SQL for point and line layers is different than for polygon.

![image](https://user-images.githubusercontent.com/3850918/51346938-28508a80-1a9f-11e9-8749-3492e31c832c.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/d556ab132763ebe7e15a2cfa8b873f58f5818507

![sw](https://user-images.githubusercontent.com/1390758/51387690-e89ea700-1b61-11e9-9f51-7207889270ac.gif)
