### ISSUE TITLE
Vector tile base layers

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#252]
The most typical use case of vector tiles is its use as base layers (#242)

**Comment by sashuk** [comment]
@mapcentia Am I correct that the only setting that specifies if the layer should be the base one is the one below?

<img width="835" alt="screenshot 2019-01-25 at 14 10 32" src="https://user-images.githubusercontent.com/1390758/51728670-02814200-20ac-11e9-8def-4562a05ad699.png">

**Comment by mapcentia** [comment]
@sashuk Most users are defining base layers in a Vidi config json. Like here: https://github.com/mapcentia/vidi_configs_common/blob/master/roenland_gl_fabrik.json#L17-L26
But the setting you refer to will be used if the `baseLayers` object lacks in the config. https://github.com/mapcentia/vidi_configs_common/blob/master/roenland_gl_fabrik.json#L16

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
For reference: https://github.com/sashuk/vidi/tree/mvt-as-base-layers

Current issues:
- the event emission is broken for MVT base layers (starts working normally after first zoom change) (check the https://github.com/Leaflet/Leaflet.VectorGrid/issues/171);
- MVT base layers mess up with regular layers.

**Comment by sashuk** [comment]
Events seem to work fine when the MVT layer is the base layer and loaded from the very beginning

[demo.zip](https://github.com/sashuk/vidi/files/2892175/demo.zip)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/04d32756a248ff156ff2115a92ba6d7158e65f8a and https://github.com/sashuk/vidi/commit/7659bea073deaf9f7ec953c4c38bdb1246ee8372

Example URL: https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#mvt:public.points/4/37.5732/3.4257/v:public.points

![mvtbase](https://user-images.githubusercontent.com/1390758/53217664-e3b6a100-3693-11e9-8c5f-27247517ad24.gif)
