### ISSUE TITLE
Optimizing layer tree rendering

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#253]
When having a lot of layers in Vidi, startup time becomes slow. This is also an issue then the layer tree has to be re-rendered (e.g. after login or creating a virtual layer). I believe its the layer tree that slows things down. There is a lot of widgets, like filters, which have to be created and rendered. Can this be optimized? An idea is to wait with the widgets until they are requeted by the user. E.g. wait with rendering of the filter widget until the user clicks the filter button. 

An example with lot of layers:
https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c4.json

**Comment by sashuk** [comment]
@mapcentia The main reason why layers are loaded in a synchronous way is that the `layerTree.create()` can be called from multiple places - the Vidi core itself and modules like `editor`, `watsonc` etc., so the whole loading process is lined up (as in #142). However, the idea of lazy widget rendering is great, it should be surely implemented!

The application loading process could be probably optimized as well, keeping in mind the synchronous nature of `layerTree.create()`, I will check this as well.

**Comment by mapcentia** [comment]
@sashuk Could you prioritize this issue?

**Comment by sashuk** [comment]
@mapcentia Sure, I will start on this one then!

**Comment by sashuk** [comment]
@sashuk  For reference: https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c4.json#bingRoad/6/25.5981/-26.2974/public.nlcov14_1,public.gcap17v,public.fcbnds17,public.pparks,public.nparks,public.veg,public.gullies,public.wetlands_,public.rivers,public.parfarms,public.homelnds,public.homestds,public.schools,public.silos,public.abattoirs

**Comment by sashuk** [comment]
Working in https://github.com/sashuk/vidi/tree/layer-tree-optimization

**Comment by sashuk** [comment]
@mapcentia Is it okay if disabled layers of any type should not have any widgets? For now, vector layers, for example, **even disabled**, have the Offline mode, Dynamic load, and Filters widgets drawn, so maybe rule `disabled layer = no widgets` should be applied to all layer types? This way the maximum performance could be achieved.

**Comment by mapcentia** [comment]
@sashuk Yes, thats OK

**Comment by mapcentia** [comment]
@sashuk Right now it still take some time to open groups with many layers. So I guess there is still going something on besides rendering tools? I guess some introspective lookup about layer type? If we don't show any tools at all before a layer is enabled, when couldn't we postponed everything until a layer i switched on? And just rendering the title and checkbox?

**Comment by sashuk** [comment]
@mapcentia The rendering process was additionally altered as you've suggested, so if the layer is not active, then only checkbox and the name is rendered. When the layer is enabled, widgets are initialized and drawn.

The build is green at https://travis-ci.org/sashuk/vidi

Changes were implemented in last two days commits at https://github.com/sashuk/vidi/commits/develop
