### ISSUE TITLE
Error when editing an existing feature with drag/move the whole shape

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#254]
1. Click on a feature and start editing
2. Grab in the middle of the feature and drag the whole feature.
The shape will now deform.
Try here:
https://map.gc2.io/app/demo_c/public/#osm/11/39.3767/-6.2225/v:public.registration

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/710c948570b6a07e36a830ad9bd8d8f61010d858

![moving](https://user-images.githubusercontent.com/1390758/51905421-27531d80-23fc-11e9-8f2e-006ecf71283f.gif)
