### ISSUE TITLE
Adapt the GC2 dashboard to new vidi_layer_type values

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#256]

**Comment by sashuk** [comment]
@mapcentia Could you please specify if `meta` properties of the layer (for example, `vidi_layer_type`) only affects the Vidi client? For example, if the `vidi_layer_type=t`, vector representation will still be returned by backend (or any other parts of the application that could use `meta` settings)?

Currently deciding how to store multiple values in the database, so got to know if I am free to choose the format if it does not really affect anything.

**Comment by sashuk** [comment]
@sashuk Questions:
- how `metaConfig` autoload is done

**Comment by sashuk** [comment]
@mapcentia Could you also please specify where available `vidi_layer_type` values come from? I've traced the origin of the `metaConfig` to step 3, hope you could point it out (I want to change the set of options in `metaConfig` to `t`, `v`, `mvt` and `w` values).

1. Client fetches the `metaConfig` from API  https://github.com/mapcentia/geocloud2/blob/master/app/api/v1/Baselayerjs.php#L51

2. The API gets the `metaConfig` from `\app\conf\App::$param["metaConfig"]`

3. The `App::$param["metaConfig"]` is populated using the autoload in https://github.com/mapcentia/geocloud2/blob/master/app/conf/App.php.dist#L138

**Comment by mapcentia** [comment]
@sashuk Here is the standard App.php, which is used in the Docker image:'https://github.com/mapcentia/dockerfiles/blob/master/gc2core/stable/conf/gc2/App.php#L124

**Comment by mapcentia** [comment]
@sashuk Meta data like `vidi_layer_type` only affects Vidi. The idea is that Meta doesn't affects anything in the GC2 back-end, but is used to configure third party apps (including Vidi or Vidi extensions)

**Comment by sashuk** [comment]
@mapcentia So, the `App.php` is checked out from the different repo and put into the `conf` folder - great, got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Thank you very much! Could you please review the https://github.com/mapcentia/dockerfiles/pull/8 and https://github.com/mapcentia/geocloud2/pull/56?

**Comment by mapcentia** [comment]
@sashuk The two pull requests looks good.

**Comment by sashuk** [comment]
@mapcentia Thanks! I've checked merged code locally, could you please update the `test.gc2.io`?

**Comment by mapcentia** [comment]
@sashuk Done

**Comment by sashuk** [comment]
@mapcentia Thanks a lot! Closing the issue.
