### ISSUE TITLE
Errror when trying to finish shape in Advanced Query by clicking first point

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#260]
You should be able to finish shape in Advanced Query by clicking first point. But instead the shape is deleted and a single point query is performed
![image](https://user-images.githubusercontent.com/3850918/52111414-ec233b00-2603-11e9-81cc-cc639d2f16b7.png)

**Comment by sashuk** [comment]
@mapcentia Could you please try the latest code change? I was not able to recreate this behavior but noticed that when the `advancedQuery` shape is drawn, the `infoClick` is activated on every click, so now they work in a mutually exclusive way.

![advancedquery](https://user-images.githubusercontent.com/1390758/52128989-5e7e3480-2671-11e9-8273-d2211c0f6cb7.gif)

**Comment by mapcentia** [comment]
@sashuk It works, closing
