### ISSUE TITLE
When enable/disable filters on a tile layer it changes to vector

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#261]
Disable filter:
![image](https://user-images.githubusercontent.com/3850918/52162929-e9dfe000-26da-11e9-82f3-c5aa48099bb0.png)
Now the layer is vector
![image](https://user-images.githubusercontent.com/3850918/52162941-05e38180-26db-11e9-8194-a7fbcb71f9b5.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/69f55231b3904249f6afdbf0a3f821e2ed47efcc


![filter](https://user-images.githubusercontent.com/1390758/52251245-cf09a780-2936-11e9-9647-496197059e24.gif)
