### ISSUE TITLE
The Load Strategy button doesn't extent the dialog

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#264]
![image](https://user-images.githubusercontent.com/3850918/52257813-b5f3fd00-291c-11e9-990c-c3438774f25b.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/431999c3eacbceb084c2d1aa73d2fce572e68f64

![toggle](https://user-images.githubusercontent.com/1390758/52327244-67328a00-2a26-11e9-8f55-64063ab54ef3.gif)
