### ISSUE TITLE
Clear Map button doesn't clear multi-selected features

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#266]
![image](https://user-images.githubusercontent.com/3850918/52272303-a1c4f580-2946-11e9-8ccd-9d70b26b1a46.png)
![image](https://user-images.githubusercontent.com/3850918/52272323-b5705c00-2946-11e9-9b08-ab77600691ec.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/c0593eb232842cc217523bf92c01b6497a2d29ef

![clearmap](https://user-images.githubusercontent.com/1390758/52418748-b44b5480-2b29-11e9-8fa4-213e67d20180.gif)
