### ISSUE TITLE
Closing Pop-up should remove selection from map

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#267]
Should 0nly remove selection when Single Info Click is used
![image](https://user-images.githubusercontent.com/3850918/52272527-5eb75200-2947-11e9-84b5-e78734e25aef.png)
![image](https://user-images.githubusercontent.com/3850918/52272535-624ad900-2947-11e9-8a06-61f3fc9c5f0c.png)

**Comment by sashuk** [comment]
@mapcentia Following click logic was implemented:
1. If `infoClick` is active, then when the popup is closed, the actual feature and `gc2table` panel disappears;
2. If `advancedInfoClick` is active, then when popup is closed, the clicked feature only resets its style, found features and `gc2table` stay the same.

Implemented in https://github.com/sashuk/vidi/commit/d7e0ffe97bfe2fe877ff1e9e84a8fc2870a43800

![click](https://user-images.githubusercontent.com/1390758/52417393-c24ba600-2b26-11e9-8837-718cf773c223.gif)

**Comment by mapcentia** [comment]
@sashuk This has some side effects. It seems, that the selection is remove whenever the pop-up is closed. Not just when the user clicks the close-button, but also when its closed programmatically.

An example: After you have clicked a polygon it was possible to move the pop-up by clicking somewhere else on the selection. Now the pop-up will just close.

The selection should only be removed when the user clicks the close button.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/9da037f82c072b180cc346e36ac74440d27306d7 (cleaning up only on when the user clicks the `Close popup` button).

![popup](https://user-images.githubusercontent.com/1390758/53220772-33e83000-36a1-11e9-97d0-89c6c3656d80.gif)
