### ISSUE TITLE
Then changing to MVT the layer tree tools are kept from previous type

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#268]
1. Select Vecter (GeoJSON) or Raster tile.
2. Change to Vector tile.

The Vector tools is still visible. Only the search tool should be visible for now.
![image](https://user-images.githubusercontent.com/3850918/52626388-5913bc00-2eb3-11e9-9a7e-6dee47f0ed1a.png)

**Comment by sashuk** [comment]
@mapcentia Could you please provide the link to this case? The `filters` are now hidden for VectorTile anyway (implemented in https://github.com/sashuk/vidi/commit/3529c88d3f30ec06bccfb18c91f738cb992d7182)

**Comment by mapcentia** [comment]
@sashuk Its working now. Closing
