### ISSUE TITLE
When editing raster layer, the vector presentation is gone

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#269]
I guess this may be a result of #267 

![image](https://user-images.githubusercontent.com/3850918/52626775-37ff9b00-2eb4-11e9-8870-8f8a7cee24a4.png)
![image](https://user-images.githubusercontent.com/3850918/52626790-3f26a900-2eb4-11e9-93e6-fcae104b9b64.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/49dbc786ab2ecfefbe5f8569a786099087e4c44d, the reason was coming from #267 indeed

![click](https://user-images.githubusercontent.com/1390758/52634503-57bdb000-2f02-11e9-8423-4d9d85d96666.gif)
