### ISSUE TITLE
Once you have loaded a vector layer dynamic it will still request the SQL API after you change to another type

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#270]
1. Switch a layer to Vector with dynamic load.
2. Switch the layer to Raster Tiles
3. Pan the map.

Now still requests are made to the SQL API which will return an error.

![image](https://user-images.githubusercontent.com/3850918/52704385-bd508180-2f80-11e9-9712-dcaccab895fd.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/2d792f564cc6e1647043317f263da8f64bb9ff0f

![dynamicload](https://user-images.githubusercontent.com/1390758/52709399-a6814d80-2fc7-11e9-8822-3f519f3a4d1a.gif)
