### ISSUE TITLE
When deleting from a layer where the pri-key is not "gid" an error occurs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#271]
Here is the key named `id`. The key is hard coded in extensions/modules/api-bridge/index.js
![image](https://user-images.githubusercontent.com/3850918/53174483-363b8300-35ea-11e9-9ae6-95e840f3d948.png)

**Comment by sashuk** [comment]
Right now features are identified by their `gid` (during all CRUD operations), as it supposed to always exist for geometry features. According to provided screenshot the `feature.properties.gid` is not defined, so the error occurs. The `pkey` property of the layer meta should be used instead.

**Comment by sashuk** [comment]
@mapcentia The meta description of layer contains properties `pkey` and `featureid` - what should be used to identify features? If it is `pkey`, then could you please specify where it can be changed (the GC2 interface in `Table > Advanced` allows only to change the `featureid` setting).

**Comment by mapcentia** [comment]
@sashuk Its the `pkey`, which identifies the key. The `featureid` is for now disabled.
The `pkey` is not set by user, but by looking up the primary key of the table. If no primary key is defined, it will fall back to `gid`. For testing you can just rename the field. Just double click on it in the structure tab.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/30428ab76b9cbe49e2af1bbba50ff2021eeae368
