### ISSUE TITLE
Create a token with snapshot object

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#273]
Besides the snapshot id, we could use a token from where snapshot data can be retrieved. From this token a client can build Vidi, without knowing the base URL or database name. The token should be the snapshot base64 encoded:

```json
{
"id": "state_snapshot_5bf85620-39bb-11e9-95db-db7801a96f09",
"title": "test",
"database": "mydb",
"host": "https://myhost",
"config": "myconfig.json",
"snapshot": {},
"anonymous": true,
"browserId": "71da65e2-0c5a-4ca9-a7d4-0138c5d83570",
"created_at": "2019-02-26T11:40:47.618Z"
}
```
We don't need the actual `snapshot` property, which also would give a long base64 string. Property `host` is new and should be added

The token should be a part of the stored snapshot, so it and be access via the keyvalue API.

```json
{
"id": "state_snapshot_5bf85620-39bb-11e9-95db-db7801a96f09",
"title": "test",
"database": "mydb",
"host": "https://myhost",
"config": "myconfig.json",
"token": "Ly8gdGhlIGFib3ZlIGV2ZW50IHdvdWxkIHdhdGNoIGZvciBjcmVhdGlvbiBvZiBlbGVtZW50IGluIHdob2xlIGRvY3VtZW50Ci8vIGl0J3MgYmV0dGVyIHRvIGJlIG1vcmUgc3BlY2lmaWMgd2hlbmV2ZXIgcG9zc2libGUsIGZvciBleGFtcGxlCiQoIi5jb250YWluZXItMSIpLmFycml2ZSgiLnRlc3QtZWxlbSIsIGZ1bmN0aW9uKCkgewogICAgdmFyICRuZXdFbGVtID0gJCh0aGlzKTs="
}
```
The token should be displayed under the "Copy link":

![image](https://user-images.githubusercontent.com/3850918/53413143-82f8d280-39cb-11e9-9fe5-5ddc47d03fdc.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if I am correct: the state snapshot data (except `snapshot` field) should be converted to `base64` string and stored as one of state snapshot properties, so 

```javascript
var tokenString = generateToken({
  "id": "state_snapshot_5bf85620-39bb-11e9-95db-db7801a96f09",
  "title": "test",
  "database": "mydb",
  "host": "https://myhost",
  "config": "myconfig.json",
  "anonymous": true,
  "browserId": "71da65e2-0c5a-4ca9-a7d4-0138c5d83570",
  "created_at": "2019-02-26T11:40:47.618Z"
});
```

So, when user has only the `token` available, he still shoud be able to decode it and open Vidi with specific state snapshot identifier at proper location (`host` field) and with other predefined parameters?

**Comment by mapcentia** [comment]
@sashuk Yes, that's right. I've created a small embed script, so a user can embed Vidi in a web-page with something like this:
```html
<div data-vidi-id="state_snapshot_5b...." data-vidi-host="https://myhost" data-vidi-db="mydb" data-vidi-config="myconfig.json" data-vidi-width="800px" data-vidi-height="600px"></div>
```
The embed script will then select the `div` and create an iFrame with Vidi in it.

But it will be more clean just to have something like:

```html
<div data-vidi-token="Ly8gdGhlIGFib3ZlIGV2ZW50IHdvdWxkIHdhdGNoIGZvciBjcmVhdGlvbiBvZiBlbG...." data-vidi-width="800px" data-vidi-height="600px"></div>
```

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/c9c12ffc7ddb7d390ae99d4ea52441fd9810bf44

![token](https://user-images.githubusercontent.com/1390758/53563719-de73bd80-3b8f-11e9-8e3e-e99566ec76bd.gif)
