### ISSUE TITLE
Vector layer table is not popularised when layer is active from start

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#274]
When you load Vidi with a vector layer in the URL the table is not popularised. This is also the case after reload of layer tree after creating a virtual layer or logging in or out.

![image](https://user-images.githubusercontent.com/3850918/54028133-45066600-41a4-11e9-9116-3bd1f35bf3ad.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/7cb9461b5d26383b1f337b08a7a61fa16537aad9 

![tableview](https://user-images.githubusercontent.com/1390758/54194612-9a6daa80-44f7-11e9-95ae-8a5effa6a0aa.gif)
