### ISSUE TITLE
Editing of multi part geometries is broken

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#275]
![image](https://user-images.githubusercontent.com/3850918/54028459-5b60f180-41a5-11e9-8be2-73c7a317bd58.png)

**Comment by sashuk** [comment]
@mapcentia Am I correct that error is observed on `MULTI(POINT|LINESTRING|POLYGON)` layers? The https://github.com/sashuk/vidi/commit/52f213b4f54408813fc88651fc319fcdd80aabef fixes these issues, but seems like support for `MULTI` geometries is not complete (`editor`, `gc2table` etc.).

**Comment by mapcentia** [comment]
@sashuk Editing of multi part geometries is fully supported in `editor` and `gc2table`. Could you create a test layer of each type and test spend some time with thorough testing of each type? I still get some errors, which seems to occur randomly. You can use QGIS to create new parts on multi geometries.

![image](https://user-images.githubusercontent.com/3850918/54205936-9af64900-44d7-11e9-9c99-a96c052afc0a.png)

**Comment by sashuk** [comment]
@mapcentia Sure, I will check this issue!

**Comment by sashuk** [comment]
@mapcentia Could you please specify if `editor` supposed to be able to CRUD all types of multi-part geometries?

**Comment by sashuk** [comment]
The multi-feature layers were created, testing on https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/6/37.9028/-3.7875/v:public.multipolygonlayer,v:public.multipointlayer,v:public.multilinestringlayer

**Comment by sashuk** [comment]
The very first error was fixed by https://github.com/sashuk/vidi/commit/52f213b4f54408813fc88651fc319fcdd80aabef indeed, recreating the second one.

Without https://github.com/sashuk/vidi/commit/52f213b4f54408813fc88651fc319fcdd80aabef:

![error](https://user-images.githubusercontent.com/1390758/54293035-32e45780-45ea-11e9-8542-d44c87fbbc82.png)

**Comment by sashuk** [comment]
@mapcentia Could you please provide the URL where the error can be observed (I see that this happened on the `localhost` installation, but maybe it occurs somewhere else)?

Almost all combinations of (editing single feature / editing multi-feature / submitting and resulting in `500` errors / signing in) were tried (assuming that the error occurs after the feature is updated, submitted to the server and `500` response is returned, as the user is not signed in).

**Comment by mapcentia** [comment]
@sashuk The error happens here then you start with an empty layer. As soon the first feature is submitted the error goes away:
https://vidi.swarm.gc2.io/app/regionh/test/#geodk.bright/16/12.5148/55.7083/

![Peek 2019-04-03 11-15](https://user-images.githubusercontent.com/3850918/55467590-e8ab3080-5601-11e9-82fc-660b6825805e.gif)

**Comment by sashuk** [comment]
@mapcentia Thank you very much for the detailed description!

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a19497b605b99e1f25c479d46938c2b0505a1e83 (snapping plugin was accessing `undefined` properties).

![snapping](https://user-images.githubusercontent.com/1390758/55475676-241c1e00-5647-11e9-9c30-bf02aa9fc8c9.gif)
