### ISSUE TITLE
Some ES6 syntax has slipped in

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#277]
In glify, geocloud.js and gc2table.js there are ES6 syntax, which breaks Vidi in IE11 (which we still need to support). An idea is to add Babel to Grunt, so we can compile js files to old syntax.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/e49b1b8e6b527c2aca1b7616b3b8cde96e564913 (`gc2table` and `geocloud` are now pulled within the bundle and are transpiled into the ES5), also IE11 was reporting errors in `glify`, so the corresponding pull request was created as well (https://github.com/robertleeplummerjr/Leaflet.glify/pull/27).
