### ISSUE TITLE
Print is broken because the triggering console.log is ever reached

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#279]
Print is activated by this console.log:
https://github.com/sashuk/vidi/blob/develop/browser/modules/state.js#L176
But it's ever reached when printing. We need a robust way to trigger this console.log after all layers and legend is loaded.

**Comment by sashuk** [comment]
@mapcentia When printing occurs, the page is loaded in a headless browser, so it is assumed that the `Vidi is now loaded` is always fired, which is later captured and the generation of PDF begins (basically if the `Vidi is now loaded` is not logged, then something went wrong). I totally agree that the capturing of console logging is hacky, the printing module can actually listen to events that page emits, for example. So, is the issue about changing the way the page is considered ready to be printed, or there are some cases when the printing does not occur at all?

**Comment by mapcentia** [comment]
@sashuk When I request the print version of Vidi, which is something like this:
`http://127.0.0.1:3000/app/mydb/feature/?tmpl=print.tmpl&l=inline&h=none&px=1060&py=730&td=13.%20marts%202019,%208:09&d=13.%20marts%202019&k=29c884ae-2dea-4075-b2ec-d6465b999af9&t=&c=#osm/15/9.9036/57.0338/feature.multipolygon`
Then `Vidi is now loaded` is not logged:
![image](https://user-images.githubusercontent.com/3850918/54259926-a3966000-4567-11e9-8b25-65159e565d6b.png)
Maybe it's because the legend in initiated from layerTree/index.js: https://github.com/sashuk/vidi/blob/develop/browser/modules/layerTree/index.js#L846
And not state.js: https://github.com/sashuk/vidi/blob/develop/browser/modules/state.js#L175
I've recently changed legend.js, so the legend for a layer is only loaded once. Even if it is switch off/on. This change may have effected the regression: 
https://github.com/mapcentia/vidi/commit/fe6f0eeec1bff4681cb5b78b6a013231fe71884e#diff-12b3bd0c103a590b8521517b253e4326

**Comment by sashuk** [comment]
Observed into in `master` branch, checking

**Comment by sashuk** [comment]
@mapcentia The reason behind this behavior was that the Promise in legend was not aways resolving / rejecting (https://github.com/sashuk/vidi/commit/fb1fe4c9c33587091b5060cd9c8cb2a3401dfc38)

Displaying page with `print` template for `master` branch:

![test](https://user-images.githubusercontent.com/1390758/54282684-7da8a400-45d7-11e9-9cbb-d0ad30aeb403.png)
