### ISSUE TITLE
Virtual layers fails after re-creation of snap-shot

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#281]
1. Make a query
2. Create a virtual layer from query
3. Create snap shot
4. Play snap shot

Now an SQL error is alerted:

![image](https://user-images.githubusercontent.com/3850918/54346498-74562080-4645-11e9-9f53-79529f82265e.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/94752fcb7bd42f4a36ee16b01adefbb1a9e65d9f

![layers](https://user-images.githubusercontent.com/1390758/54351526-a047c500-468a-11e9-8c46-78e02673d5e9.gif)
