### ISSUE TITLE
Bug in IOS

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#282]
![image](https://user-images.githubusercontent.com/3850918/54814497-2b7b1900-4c90-11e9-9907-def5549a81d2.png)

**Comment by mapcentia** [comment]
The bug also appears in Chrome on Android

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/5a2dd946e5dccce166ae5282819b7c8a144516e9

![demo](https://user-images.githubusercontent.com/1390758/54891335-f537d680-4ee7-11e9-9878-b4f7f0368c00.png)

**Comment by mapcentia** [comment]
@sashuk I think this fix introduced a new bug. The orientation of print is not right:
![image](https://user-images.githubusercontent.com/3850918/55035328-f23c0380-5017-11e9-832a-1e5e885fc22d.png)

**Comment by sashuk** [comment]
@mapcentia Sorry totally missed it. Fixed in https://github.com/sashuk/vidi/commit/6b4ef93fbffaa8b6a40c6a159d6c7e6aeb2a58f5

![print](https://user-images.githubusercontent.com/1390758/55052777-0b36ca00-5095-11e9-9e0f-58eb77ce5254.gif)
