### ISSUE TITLE
Vector table is not updated when changing filters

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#283]
1) Add filter and open table.
2) Change filter. Table is not updated.
3) Open/close table and it will update.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/5f934af269387ea475cbd2e6a25a04b00f8332e1

![tableview](https://user-images.githubusercontent.com/1390758/54892123-43020e00-4eeb-11e9-8e4c-3acbf24053ae.gif)
