### ISSUE TITLE
Small ajustments to alignment of tools 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#287]
Tile tools are not aligned in center but vector tools is. The edit-plus button is also a bit off.
![image](https://user-images.githubusercontent.com/3850918/55325588-d60bec80-5485-11e9-8ffe-6a05c8864490.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/8578750fded5e517c4d0a567020763fee7b1c95c

![fix](https://user-images.githubusercontent.com/1390758/55377072-f3a08b00-5545-11e9-9478-5ab1d38d35e0.gif)
