### ISSUE TITLE
Vector tool is showing when using raster tiles

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#288]
![Peek 2019-04-03 08-24](https://user-images.githubusercontent.com/3850918/55457530-80048980-55ea-11e9-8a97-7b56d7a375f3.gif)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/444c4ac1edfe31d626735155aeecb1e45725634e
