### ISSUE TITLE
Setup filter condition beforehand

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#289]
Some users need to create the same filter conditions over and over again. So we need a Meta config for setting up conditions on beforehand. So when the filter panel is expanded, it should look like some like this:
![image](https://user-images.githubusercontent.com/3850918/56574991-e9adfd00-65c4-11e9-9b3e-0bf7ae0db21d.png)
I've created a new Meta config for holding a JSON string to control this called `filter_config`:
![image](https://user-images.githubusercontent.com/3850918/56575404-ea935e80-65c5-11e9-8c76-ef02dfbf6665.png)

It available on http://gc2.mapcentia.com

The JSON object for a layer could look like this:
```json
[
      {
         "field": "broendtype",
         "operator": "="
      },
      {
         "field": "fot_id",
         "operator": ">"
      },
      {
         "field": "fot_id",
         "operator": "<"
      }
]
```

**Comment by sashuk** [comment]
@mapcentia Preset filters were implemented along with the tests in https://github.com/sashuk/vidi/commit/19ca34003b4edee7853da59fea20a513a212cc66 and https://github.com/sashuk/vidi/commit/dcf6b6aaa2bcb44f88bbd112ba66ea17ca5180f2

Given preset filters:

```
[{
  "field": "id",
  "operator": ">"
},{
  "field": "stringfield",
  "operator": "="
}]
```

The following interface is generated:

![preset](https://user-images.githubusercontent.com/1390758/56645058-7fbe5200-66af-11e9-8de6-79f584551fb7.gif)
