### ISSUE TITLE
In filters, create a drop down widget when a field has restriction on input

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#291]
GC2 Meta data can now have a new property for `fields` called `restriction`:
![image](https://user-images.githubusercontent.com/3850918/56894673-e44e2800-6a86-11e9-8717-db0723802a21.png)
If this property is present, when create a select input field in filters. `restriction.value` is the value, which should be used in the filter and `restriction.alias` is the text, which should be displayed for the user.
Test: https://swarm.gc2.io/api/v1/meta/test4/public.routes

![image](https://user-images.githubusercontent.com/3850918/56894954-ca611500-6a87-11e9-8e66-c499871f6a04.png)

**Comment by sashuk** [comment]
@mapcentia The select control for fields with `restriction` was implemented in https://github.com/sashuk/vidi/commit/f84981173d8f6765dad5bcda956ec54e2ea9b941

![select](https://user-images.githubusercontent.com/1390758/56959565-666e4780-6b80-11e9-9c62-05ccc06e6c6b.gif)
