### ISSUE TITLE
Static map API

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#294]
We need an API, which can create a PNG image from a snapshot.

Now we can get the Vidi client like this:
`https://vidi.swarm.gc2.io/app/horsens/?state=state_snapshot_d669c360-7162-11e9-8149-c378481f80dc`

New API should look like this:
`https://vidi.swarm.gc2.io/api/static/horsens/?state=state_snapshot_d669c360-7162-11e9-8149-c378481f80dc`

The API should just use Puppeteer for request the Vidi client and returning a PNG image.

We need a "blank" template for the static image. So Puppeteer should request something like:
`https://vidi.swarm.gc2.io/app/horsens/?tmpl=blank.tmpl&state=state_snapshot_d669c360-7162-11e9-8149-c378481f80dc`

Where `blank.tmpl` is a new template with only the map element and on padding/margin on the body.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the quick link to the PNG should be available at the state snapshots block?

![statesnapshot](https://user-images.githubusercontent.com/1390758/57429338-59c3b080-725e-11e9-8ca9-08008d5f5d58.png)

**Comment by mapcentia** [comment]
@sashuk Yes, it could be useful to have the link in the snapshot block. The size has to be set the URL like `&width=800&height=600`. So there could be some way to input this in GUI.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/edd574a1a08944fc1edd26741364a2420d31bafb and https://github.com/sashuk/vidi/commit/ab6f1d6ded8b1619a8630ab18e18f8d1935c6de1, users can select the desired image size using the `<select/>` box or manually right in the URL

![pngur](https://user-images.githubusercontent.com/1390758/57442300-43c5e800-727e-11e9-9f95-ed11c3ad1cf9.gif)
