### ISSUE TITLE
A notice modal view

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#295]
I some cases we need to inform users of e.g. changes in Vidi or layers.
In config/config.js or in a remote config.js file a new property called `startUpModal` should trigger the opening of a modal view when Vidi i called. The value of `startUpModal` should the HTML for the modal view. The modal should look like the existing About modal:
![image](https://user-images.githubusercontent.com/3850918/57363817-26135880-7182-11e9-9350-403b594ecc16.png)
After the user has dismissed the modal, it should not reappear (cookie?)

**Comment by sashuk** [comment]
@mapcentia Maybe also the cookie should store the hash of the last `startUpModal`, so whenever the `startUpModal` changes (i.e. new information has to be shown to the user), the modal is shown anyway (as the user has closed actually the previous version of the modal)?

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/69ddca74cf6d19138bfeca7f8eb60de7dc926ec0

![modal](https://user-images.githubusercontent.com/1390758/57429166-d1dda680-725d-11e9-98b8-dfdc5e32c76a.gif)
