### ISSUE TITLE
Info button on base layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#296]
On layers we have a `info` button:
![image](https://user-images.githubusercontent.com/3850918/57369699-7bedfd80-718e-11e9-9d2d-712f80f26060.png)

We need that also on base layers. 

The HTML should come from a property called `abstract` on the base layer definition:

```JSON
{
    "baseLayers": [
        {
            "id": "osm",
            "name": "OSM",
            "abstract": "<p>Some base layer</p>"
        }
   ]
}
```

Mark down should also be supported as it is when using `meta.meta_desc`

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/f3453b7014c0dc5bd6d15e4a850374c73d3d5619

![baselayers](https://user-images.githubusercontent.com/1390758/57428028-0e5ad380-7259-11e9-81c2-9314982cd43a.gif)
