### ISSUE TITLE
Startup modal must not show in print

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#298]
![image](https://user-images.githubusercontent.com/3850918/57526391-9c07f300-732d-11e9-80c3-a20951bbc72b.png)

**Comment by sashuk** [comment]
@mapcentia The startup modal is not shown for machine-used templates like `blank.tmpl` (PNG generation) and `print.tmpl` (PDF generation), fixed in https://github.com/sashuk/vidi/commit/bb81ca1d086b882037cfc18718209afec0591793

**Comment by mapcentia** [comment]
@sashuk We need another way of detecting machine-used templates because its common to use a custom templates for print. Like `print_geofyn.tmpl`

**Comment by sashuk** [comment]
@mapcentia The additional setting was defined in https://github.com/sashuk/vidi/commit/1a2b9e36e7c0a0df12a4b8d349b327018d73f5d8 (presented values are also the default ones when the `startupModalSupressionTemplates` is not specified):

```
    // ===============================================================
    // Startup modal supression templates.
    // Setting contains list of templates, where the startup modal is
    // disabled. Can be a plain template name or the RegExp
    // ===============================================================

    "startupModalSupressionTemplates": ["print.tmpl", "blank.tmpl", {
        regularExpression: true,
        name: "print_[\\w]+\\.tmpl"
    }],
```
