### ISSUE TITLE
Switch between old and new legend behavior

### ISSUE THREAD

**Issue by lossoE** [sashuk/vidi#299]
The current state of vidi is not removing switched off layers from the legend, which makes the legend impossible to work with when you have many layers with many classes.

**Comment by mapcentia** [comment]
This is the excepted behavior, which was implemented in https://github.com/sashuk/vidi/commit/fe6f0eeec1bff4681cb5b78b6a013231fe71884e#diff-6d4f866cfc596738d9a57ed786e6b1de
We need a flag in `config/config.js` so the legend is switched back to the old behavior

**Comment by sashuk** [comment]
@mapcentia @lossoE The `removeDisabledLayersFromLegend` config setting was added in https://github.com/sashuk/vidi/commit/36d40baeef0818a1984cb8cea8eec090e9140804.

![legend](https://user-images.githubusercontent.com/1390758/57692633-caf9ce00-7679-11e9-83a8-ed538aaae905.png)
