### ISSUE TITLE
Get feature info for tile layer

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#3]
You can't click-for-info on the tile layer, if a vector layer is visible. Its doesn't send the request to the server.

**Comment by sashuk** [comment]
@mapcentia Maybe it should stay like this? I think that user is expecting some action from actual vector when the vector layer is clicked (vector layer is always over the tile one). If the information should be fetched anyway, then it can be fetched for the actual vector feature.

**Comment by mapcentia** [comment]
Try this:

Reset
Switch on polygon tile
Swich on point vector
Click on a polyon (you get info)
Refresh browser 
Click on a polyon (you don't get info)

When refreshing the hash change from:
v:public.test,public.test_poly
to:
public.test_poly,v:public.test

**Comment by sashuk** [comment]
@mapcentia Thank a lot!

**Comment by sashuk** [comment]
Closed in https://github.com/sashuk/vidi/commit/2f57d9ec69921c494a3f95a586e7423e58d51628
