### ISSUE TITLE
Add Second Subgroup function to display on Vidi

### ISSUE THREAD

**Issue by lossoE** [sashuk/vidi#300]
This request seeks the addition of a second subgrouping making it in a total of 3 categories on the layer tree.  The aim is to be able to add a subgroup on subgroup1 as illustrated below

Parentgroup : |- Country
Subgroup 1                 | - - : Provinces
Subgroup 2                               | -- - : Distrticts

**Comment by mapcentia** [comment]
@sashuk @lossoE 
I'm not sure about the best way to implement this. A suggestion is to set `vidi_sub_group` to `subgroup1/subgroup2`. So if we have two layer:
- Layer1 > vidi_sub_group = subgroup1
- Layer2 > vidi_sub_group = subgroup1/subgroup2

Layer1 will act as current (placed in subgroup1) and Layer2 will be placed in a subgroup to subgroup1.

**Comment by sashuk** [comment]
@mapcentia The proposed variant looks good! But maybe to use the `:` as a separator, as I think the slash will be more common in the layer group names.

**Comment by mapcentia** [comment]
@sashuk maybe we should avoid any unwanted second subgroup and use a pipe `|`

**Comment by sashuk** [comment]
@mapcentia Sound good!

**Comment by sashuk** [comment]
@mapcentia @lossoE Implemented in https://github.com/sashuk/vidi/commit/01d8fd1f55e4fa8ba87f02602aa04c9d2afe24e8 and https://github.com/sashuk/vidi/commit/4b7c7ea0e36adeed3cb65ed2f1d748aa23154ec5

Demo:

![sorting](https://user-images.githubusercontent.com/1390758/58113525-47675080-7c28-11e9-95e0-66097fbff26f.gif)

**Comment by lossoE** [comment]
Hi Martin,
                Please, kindly push changes to our production. I have you
have also done the testing.

I have also submitted the 3rd issue so that you can allocate Alex.

I appreciate this committment to get it sorted.

Regards,

Losso

**Comment by lossoE** [comment]
@mapcentia @sashuk 
Just a bit of an oversight from my end.  While doing the implementation, i just noticed i missed the fact that was a  thrid sub group that was hidden on the desktop application. Can it be extended as indicated below?

Subgroup1 | Subgroup2 | Subgroup

Sorry about the back and forth. 

Thx

**Comment by sashuk** [comment]
@lossoE Could you please specify if there should be another, deeper level?

**Comment by lossoE** [comment]
@sashuk That's correct!

**Comment by sashuk** [comment]
@lossoE Got it, thanks!

**Comment by lossoE** [comment]
@sashuk  Did you manage to add the extra level?
Thx

**Comment by sashuk** [comment]
Hello, @lossoE! Unfortunately, it is still in progress.

**Comment by lossoE** [comment]
@sashuk Noted with thanks!

**Comment by sashuk** [comment]
@mapcentia @lossoE In order to avoid code duplication there was a major code refactoring, so the infinite layer group nesting was implemented in https://github.com/sashuk/vidi/commit/f82d9b44108b2c0fe041c06f7757bfa9128d4161.

:link: Demo: https://vidi.alexshumilov.ru/app/aleksandrshumilov_dev/public/#stamenTonerLite/8/39.2349/-6.8064/public.layer_2_2_1_2

Screencast with **4 levels** depth (`Layer Group` + `Subgroup 2 | Subgroup 22 | Subgroup 221`):

![layers](https://user-images.githubusercontent.com/1390758/58729493-2bc82b00-841c-11e9-95b0-ba532b4b817c.gif)

Screenshot of **5 levels** depth (`Layer Group` + `Subgroup 2 | Subgroup 22 | Subgroup 221 | Subgroup 2211`):

![levels](https://user-images.githubusercontent.com/1390758/58729509-3a164700-841c-11e9-87c6-da4dea00883d.PNG)

**Comment by lossoE** [comment]
@sashuk @mapcentia   This is great! Thank You!
M H  Please, push changes on production.
Thx

**Comment by lossoE** [comment]
@sashuk  @mapcentia  Please, check the sort order from 3 level going deeper.  The layers /Subgroups state still remain reverse order.
Thx!
![Layer Orders](https://user-images.githubusercontent.com/49659496/58770801-454eab80-85b1-11e9-8da7-c3b74bcca18b.PNG)

**Comment by sashuk** [comment]
@mapcentia @lossoE Fix was implemented in https://github.com/sashuk/vidi/commit/273e35517c38d948f8a5ad180aa53f79da87ff7c

Screenshot:
![sort](https://user-images.githubusercontent.com/1390758/58796041-bbddbe80-862e-11e9-88ab-b7b2c1d9ad95.PNG)

**Comment by lossoE** [comment]
@sashuk @mapcentia  Thanks for applying the fix.
