### ISSUE TITLE
Limit drag handle to the right side sumbol in layer tree

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#301]
As for now the whole layer/group panel is a handle for draging. But this is a problem on touch: When you just want to scroll the tree you will instead drag the panels. So way to deal with this is to limit the drag handle area to the right side symbole:
![image](https://user-images.githubusercontent.com/3850918/57754702-56fa0d00-76ef-11e9-97e9-fb0e5b850c42.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/80ea5e03442c4d72e5b2621dd8485cb3ba37a16b

![sorting](https://user-images.githubusercontent.com/1390758/57762025-49657700-7731-11e9-9357-53f8a0bb96c0.gif)
