### ISSUE TITLE
Fields of type "timestamp with time zone" is omitted in filters

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#303]
Fields of type "timestamp with time zone" is not showing in filters:
https://nt.admin.gc2.io/api/v1/meta/nt/udstilling.aktuelle_ruter

**Comment by sashuk** [comment]
@mapcentia The `timestamp with time zone` was added as a Date control type, but the whole request was not tested (probably the `timestamp with time zone` requires separate formatting when the condition is sent to the server) as requests to the host `nt.admin.gc2.io` are randomly failing with 408 and 404 errors. Is it a temporary condition or it should be recreated locally? It if it should be recreated, could you please tell how to create a column with `timestamp with time zone` type in GC2?

**Comment by mapcentia** [comment]
@sashuk Try to set the `SQL_QUERY_LIMIT` way lower: https://github.com/sashuk/vidi/blob/develop/browser/modules/layerTree/constants.js#L19
I think the fails are caused by out-of-mem isssues.
You create a `timestamp with time zone` through GC2 Admin. It has to be done directly in the database.

**Comment by sashuk** [comment]
@mapcentia Thanks for the suggestion! Fixed in yesterday commit https://github.com/sashuk/vidi/commit/56bac3e1e0e994190a00b7c78e7c76518592b93f

![filter](https://user-images.githubusercontent.com/1390758/57910221-5b712200-78b7-11e9-99d2-8b87e281463f.gif)
