### ISSUE TITLE
Filter is not applied on child layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#304]
Try this connection in Vidi: `https://nt.admin.gc2.io`

The layer `udstilling.aktuelle_ruter` is setup with this reference to `udstilling.aktuelle_stoppesteder`:

```json
[
	{
		"rel": "udstilling.aktuelle_stoppesteder",
		"parent_column": "linename",
		"child_column": "linename"
	}
]
```

But `udstilling.aktuelle_stoppesteder` doesn't get a filter applied. It does reload when applying filters on  `udstilling.aktuelle_ruter`

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/ed85746bbf5cb25543f5aeb4a638c6aec42e7827
