### ISSUE TITLE
Filters are not applied on vector child layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#305]
Parent filters works fine on child raster layers:
![image](https://user-images.githubusercontent.com/3850918/58164567-5ed52680-7c86-11e9-8f12-20789b6b54a5.png)

But not on vector child layers:
![image](https://user-images.githubusercontent.com/3850918/58164596-6eed0600-7c86-11e9-8b5d-3bc51e140e96.png)

**Comment by sashuk** [comment]
@mapcentia Could you please clarify if whenever the filter `A` is applied, assuming that there is already filter from a parent layer `B`, should the filters be applied as `A OR B` or `A AND B`? Right now filters are sent like

```
filters={
  "udstilling.aktuelle_stoppesteder":[
    "(name like '%a%')",
    "linename IN (SELECT linename FROM udstilling.aktuelle_ruter WHERE (linename = '50'))"
  ]
}
```

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/3fef4f0fed611064b51541aa9b757f71eb8ed76f

![vectorparentfilter](https://user-images.githubusercontent.com/1390758/58256861-5540e100-7da2-11e9-8d10-951c97f0d082.gif)
