### ISSUE TITLE
Adding Filter on Layer tree Parent Category

### ISSUE THREAD

**Issue by lossoE** [sashuk/vidi#306]
The function request is an enhancement on vidi to be able to apply a filter on based on the available parent categories on layer of content. This will ease the visualisation of adjacent dataset that are group per parent category. A good example is when data is grouped per provinces the user wants to have a seamless view across two provinces that share a common spatial boundary.
This function should be as follows :
1. Be modular with a switch to enable/ disable on the config
2. The filter should allow the vidi user to Toggle ON a max of two  Parent categories at a time
3. The Filter, upon activation should load all Parent Category on the Filter panel while keeping   layers within the parent categories &  subgroups unchecked
The overall intention is to be able to visualise many layers on the same vidi instance optimally.

I have attached some mockups.

Thanks
![Layer Tree Filter Control](https://user-images.githubusercontent.com/49659496/58173826-a1096280-7c9c-11e9-8019-805b6e239019.PNG)
![Layer Tree Filter](https://user-images.githubusercontent.com/49659496/58173827-a1096280-7c9c-11e9-9714-2725abc8614e.PNG)

**Comment by sashuk** [comment]
@lossoE Could you please specify if the filtering is basically showing and hiding the first-level layer groups? So, for example, when the filter is applied then all layers from non-filtered groups are turned off and vice-versa.

**Comment by lossoE** [comment]
Yes that is correct.

**Comment by mapcentia** [comment]
@lossoE @sashuk Will filters and groups always corospond? Meaning that the number and names of filters will always be the same as numbers and names of groups?

The max of two groups at the same time should be an option (e.g. an input field). But I don't see the meaning of this limitation?

**Comment by sashuk** [comment]
@mapcentia @lossoE I think yes, the `layerTree` shows only those layer groups that are selected in the filter (however, some cases like what to do when parent filter is in shows category, and the child filtered layer is in the hidden one should still be processed).

**Comment by lossoE** [comment]
@mapcentia @sashuk  You are correct the max should an input value. To better explain it this, the names used or reference on the toggle list should be a list of first layer groups names that are loaded on the layer panel tree. We just want to toogle to hide / show first layer groups..  
This function is also to limit the user from loading all +- 600 layers for all nine provinces. I'll appreciate suggestions of a better way to implement this.

**Comment by mapcentia** [comment]
@lossoE @sashuk The proposed idea makes it possible to filter groups arbitrarily. But if the user always looks at one province at a time, it could be done with nine config JSON files and a way of switching between configs in Vidi. Like having a list of configs, which can be clicked. Then clicking a config, the layertree will be rebuild with layers defined in the specific config.

**Comment by sashuk** [comment]
@mapcentia Probably this is the same thing that we have discussed during https://github.com/sashuk/dashboard discussion - some Vidi module that allows switching between publicly available configs fetched via GC2 configurations API.

**Comment by lossoE** [comment]
@mapcentia @sashuk 
That seems like a better approach to implement it.

**Comment by mapcentia** [comment]
@lossoE New issue added #308 Closing this one
