### ISSUE TITLE
When a vector layer is filtered by parent, the table/map relation doesn't work

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#307]
1. Apply filter on parent
2. Show table on child and click on row.

A JS error is thrown. Tested on point child layer.

![image](https://user-images.githubusercontent.com/3850918/58348452-145bd180-7e61-11e9-8dc4-c9a3cb83b487.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a96a35acfb583921cf61a0fe9e91f90d58b4231a

![demo](https://user-images.githubusercontent.com/1390758/58426577-82a5cb80-80cf-11e9-80f2-71e0b99befdd.gif)
