### ISSUE TITLE
Config switcher

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#308]
We need a module for switching between configs (the json files). Because a config can set brand name, enable extensions and more, a refresh of browser is needed (I believe). But it is possible to load Meta and re-render layer tree without refresh. So the config switcher should be able to switch in two modes:
- Full with browser refresh
- Layer tree only without browser refresh

The new config switcher needs to know which configs are available. So the Dashboard has to expose a API, which returns configs. For starters, we can just have an array of configs in config.js 

 This issue makes #306 redundant

**Comment by sashuk** [comment]
@mapcentia For now the Dashboard provides the API for fetching configurations of the certain user (as an example, Dashboard has a special page with published configurations that use this API at http://vidi.alexshumilov.ru:8080/dashboard/configuration/published/sashuk), so the extension could be implemented using the API. Could you please specify the following details:
1. Should the configurations API provide all published configurations created by any user of the GC2 installation or only for the specific user name?
2. Should the Vidi user be able to specify the URL of another API where he can fetch the list of configurations?

**Comment by mapcentia** [comment]
@sashuk Good questions.

If the user is NOT logged into Vidi, all published configs from the current database should shows. So if you're on /app/sashuk/public... you should see the same as  /dashboard/configuration/published/sashuk 

If the user is logged into Vidi, same as above + the unpublished configs of the user.

**Comment by sashuk** [comment]
@mapcentia Got it, thank you!

**Comment by sashuk** [comment]
@mapcentia Seems like the partial applying of the configuration will require at least to reload `meta` and recreate a `layerTree` (so, other modules will have a correct understanding of current meta). However, the application initialization almost consists of these two operations as in

https://github.com/sashuk/vidi/blob/94efcf686d5ba45aa92281b0182b4cbbead6096c/browser/modules/init.js#L300-L309

, so maybe only the Full page reload should be left for now?

Demo:
https://vidi.alexshumilov.ru/app/sashuk/public/?tmpl=default.tmpl#stamenTonerLite/5/20.2808/53.9173/ (login `sashuk` and password `qewadszcx`).

Screencast:
![switcher](https://user-images.githubusercontent.com/1390758/59091922-f3a47900-8942-11e9-88f6-d92aa8c09443.gif)

**Comment by mapcentia** [comment]
@sashuk That fine for me and Losso can get going

**Comment by sashuk** [comment]
@mapcentia Great! Minor changes were applied in https://github.com/sashuk/vidi/commit/3ccbc653ff13bd85cf2d9eafdaea18353bdd867b

**Comment by lossoE** [comment]
@sashuk @mapcentia  Apologies i did receive notification. How do i go about testing it?

**Comment by lossoE** [comment]
@sashuk @mapcentia  I am getting a this eror : 404 Not Found when i try to test with the URL provided above. Thx

**Comment by sashuk** [comment]
Hello, @lossoE! The above URL has already changed, but you can test this on your local installation - please enable `configSwitcher` (this is the id of the new extension) and make sure that the GC2 host you are testing against has the latest codebase (that actually provided access to the configurations).
