### ISSUE TITLE
Static map API should support config files

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#309]
A static map URL looks like this:

`http://127.0.0.1:3000/api/static/test1/my_schema/?state=state_snapshot_fd175e80-869f-11e9-bef7-8dd09d30d94e&width=800&height=600`

It should be possible to provide a config file:

`http://127.0.0.1:3000/api/static/test1/undefined/?state=state_snapshot_fd175e80-869f-11e9-bef7-8dd09d30d94e&width=800&height=600&config=my_config.json`

The used config should also be added in the snapshot link dialog like the Vidi link:
![image](https://user-images.githubusercontent.com/3850918/58862725-9b0a7d00-86b1-11e9-996e-a7cc46938725.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/9cd1f3068fcd25f0ed2c18f7340d0d7a30a8290b. The `api/static` controller was modified not to cache any loaded resource when generating the image. Tested with the configuration file, where on every image generation the set of base layers was different.

![config](https://user-images.githubusercontent.com/1390758/58890288-ead25e00-871c-11e9-88ee-0593122084ed.png)
