### ISSUE TITLE
Image field keeps image between edits

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#31]
1) Edit a point and add image
2) Submit or not submit edit.
3) Edit another point. Now the image from 1) is still there

**Comment by sashuk** [comment]
@mapcentia Could you please check if the image is correctly stored on the backend?

When the image is saved,

![aaj5wdtbh5](https://user-images.githubusercontent.com/1390758/41097605-24de7a02-6a8b-11e8-8bc6-3aeae40dada0.png)

the server returns `0` as an `image` field value

![692jsvk9w0](https://user-images.githubusercontent.com/1390758/41097609-2848ec40-6a8b-11e8-8460-5bffc57c8867.png)

The actual attribute form resetting is implemented in https://github.com/sashuk/vidi/commit/0ddc5a2075080e3038bcc2f3cda43c2a0e8171d0

**Comment by mapcentia** [comment]
Its was a bug in GC2. The SQL API now returns the base64 string.
