### ISSUE TITLE
Set max feature count from GC2

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#310]
I've added a meta.max_features property to https://gc2.mapcentia.com

This should override https://github.com/sashuk/vidi/blob/develop/browser/modules/layerTree/constants.js#L19 for the specific layer

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/7ad132637d6ff2425c85845f77116bb43d4d86aa
