### ISSUE TITLE
Enable default setting of all/any in filter for specific layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#311]
I've added `meta.default_match` at https://gc2.mapcentia.com

This property should control default setting of all/any in filters for the specific layer.
 
![image](https://user-images.githubusercontent.com/3850918/58872142-b3839300-86c3-11e9-8752-46acc29a0da1.png)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/716323ca0c64b1a346907076f69e251ee7a84ade

![match](https://user-images.githubusercontent.com/1390758/58885899-95df1980-8715-11e9-8bb9-827ba2b2900a.gif)
