### ISSUE TITLE
Error when printing

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#313]
I get a `UnhandledPromiseRejectionWarning: TypeError: headless.getBrowser(...).newPage is not a function` when printing. I'm on Nodejs v12.4.0 and puppeteer@1.7.0
![image](https://user-images.githubusercontent.com/3850918/59598240-03b71800-90fc-11e9-916e-19d3842f1109.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if it is the latest code base? This error was fixed as part of the https://github.com/sashuk/vidi/commit/eb4fab6420fad7e3c4ad8a10e316d69aff161bc9

**Comment by mapcentia** [comment]
@sashuk Its works. You've changed the port to 3001 ?

**Comment by sashuk** [comment]
@mapcentia Great! Yes, I've accidentally pushed it from staging deployment (https://github.com/sashuk/vidi/commit/669982c2601cba046cea1cb5a03f9d540305d7ea), now it is changed back in https://github.com/sashuk/vidi/commit/06335eaa03dbbdb5023a9b1e0afe76bd89e62e97
