### ISSUE TITLE
Session based snapshots from other sessions are always listed

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#314]
Snapshots from others sessions are listed. How to replicate:
1. Create a snapshot
2. Delete cookie
3. Refresh browser

Now you can see the snapshot is still listed. But you can't delete it, which is expected:
![image](https://user-images.githubusercontent.com/3850918/59625687-3a138800-913a-11e9-8824-4e52a91f03ed.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the state snapshots panel should only display the snapshots *owned* by the current user (anonymous and/or authorized), but when the state snapshot is requested by its id (for example, when sharing Vidi link with specified snapshot), then it should be returned even if the requesting client is not an actual owner?

**Comment by mapcentia** [comment]
@sashuk Yes, that right.

**Comment by sashuk** [comment]
@mapcentia Got it, thank you!

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/3ef2cca56702e27ce0c9ec671d15aa485630bb4b - state snapshot module now receives only owned (either by the browser or authenticated user) state snapshots.
