### ISSUE TITLE
Enable use of snapshots in configs

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#315]
Now we have three ways of selecting which layers should be load in layertree:
```json
{
"schemata": [
    "my_schema",
    "my_shama.my_layer",
    "tag:my_tag"
]
}
```

We need also to ne able to use a snapshot. My idea is to use a special property, which will override `schemata`:

```json
{
"snapshot": "state_snapshot_f4730010-90f7-11e9-abb8-57680d16d9e2"
}
```

**Comment by sashuk** [comment]
@mapcentia Following was implemented - if the `snapshot` parameter is specified, the actual snapshot is requested when `meta` is initiated and the `schema` parameter is taken from the state snapshot - could you please specify if this logic is correct?

**Comment by mapcentia** [comment]
@sashuk Sounds right. I'll test

**Comment by sashuk** [comment]
@mapcentia Great! The feature was implemented in https://github.com/sashuk/vidi/commit/4d863cdc5a6673a0fe3b988984394fc130ee1cdd

**Comment by mapcentia** [comment]
@sashuk when testing, browser ends like this:
![image](https://user-images.githubusercontent.com/3850918/59847652-5f370f00-9363-11e9-8944-61def9b51ae0.png)

**Comment by sashuk** [comment]
@mapcentia The reason application was not starting up under some conditions is that the `settings` module was not receiving the correct `schemata` after correct `meta` initialization, so this was fixed in https://github.com/sashuk/vidi/commit/3fffcd5549560526c1a2fdb105d9f4452b7cb142

**Comment by mapcentia** [comment]
@sashuk I still can't get this to work. My config looks like this:
```
{
    "schemata": [
        "feature"
    ],
    "snapshot": "state_snapshot_c6419a20-98c8-11e9-9a5f-93484cfd71c6"
}
```
The snapshot looks like this:
![image](https://user-images.githubusercontent.com/3850918/60261783-00cadd00-98dd-11e9-938f-3f328db632ad.png)

When I use the config like this:
`/app/mydb/?config=/api/v2/configuration/mydb/configuration_snapshot_5d149ecd23daa413623751.json`

Vidi ignores the snapshot.

**Comment by sashuk** [comment]
Could you please specify how Vidi ignores the snapshot? Now if Vidi sees the snapshot property in the configuration (which overwrites the schemata one), then this state snapshot is requested and **only** its `schema` property is used (the code is at https://github.com/sashuk/vidi/issues/322#issuecomment-505903671). 

Maybe it is expected that Vidi will use not only the `schema`, but the entire snapshot settings?

**Comment by mapcentia** [comment]
@sashuk It is expected that Vidi uses the entire snapshot, like clicking the play button or using the state_id in the URL

**Comment by sashuk** [comment]
@mapcentia If `snapshot` parameter is specified in the configuration file, the schemata is taken from the specified snapshot (unless it is missing, in this case, the regular `schemata` is used as a fallback). Also, the configuration `snapshot` property is later used to apply the actual state snapshot.

However, if the state snapshot is specified as the query parameter (`../public?state=state_snapshot_abc123`), then the state snapshot from the query is applied, as it has higher priority than the configuration one.

Implemented in https://github.com/sashuk/vidi/commit/42f35bb0c73e18265eb92de3dc517af12c0de77d
