### ISSUE TITLE
Static map from requesting layer with filter

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#316]
We have the Static Map API like this:
`/api/static/db/schema/?state=state_snapshot_f37e18c0-90f7-11e9-abb8-57680d16d9e2&width=600&height=600`

We also need a API which has this signature:
`/api/static/db/schema/?layer=v:layer&filter=foo=bar&width=600&height=600`

The output should be a PNG with the vector layer switched on and filtered. And centered on the filtered features.

It could be a enchancement on `/api/static/` or a new API. Whatever is best. 

This for autogenerating images of single features in a layer.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if there should be UI control that triggers the PNG generation for every filter or it supposed to be called only programmatically?

**Comment by mapcentia** [comment]
@sashuk Only only programmatically.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/e35736699001f0f1a06f8bf0acc80e154ecb9fbc. Please see the https://github.com/sashuk/vidi/blob/e35736699001f0f1a06f8bf0acc80e154ecb9fbc/test/api/static.test.js for URL construction example,

**Comment by mapcentia** [comment]
@sashuk The layer is not switched on when using the filter:
![Peek 2019-06-25 09-31](https://user-images.githubusercontent.com/3850918/60078372-1947c580-972c-11e9-8c96-87fe530b0898.gif)
Used filter:
```json
{
  "feature.theme_pdk_lokalplan_vedtaget_v": {
    "match": "any",
    "columns": [
      {
        "fieldname": "planid",
        "expression": "=",
        "value": "181315",
        "restriction": false
      }
    ]
  }
}
```

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/d3c42d5de404adfd123085d70f444179b8a6e2a9

Demo:

![reload](https://user-images.githubusercontent.com/1390758/60154314-7c635600-9819-11e9-81c3-ff210eb2122d.gif)
