### ISSUE TITLE
If max features is reached when loading vector, then info user and don't render layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#317]
When loading features in a vector layer and number of loaded features eq set max features, then show a toast measage about max features is reached and user should decreased number of features using filters. And don't render the layer, because seeing not all features is confusing for the user.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/c6ea8ab64eed87660df2799f926178a6d27223ef

Demo:
![max_features](https://user-images.githubusercontent.com/1390758/59894782-771a9b80-9414-11e9-8de2-f692ad392030.gif)


Could you please specify if the layer needs to be shown for a brief moment like it is implemented now? It can not be shown at all with some modification of `geocloud.js`, though.

**Comment by mapcentia** [comment]
@sashuk The layer should stay switched on, so the user can set filters. Instead of switching the layer off, can you instead set `features` in the GeoJSON to `[]` (empty array).

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/ac5d665fedc038876140f866ceb1902b1128934f

Demo:
![features](https://user-images.githubusercontent.com/1390758/60012594-ea3f3e80-96ae-11e9-871c-eecd7ad8464a.gif)
