### ISSUE TITLE
Login dialog must handle sub-users with same name

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#319]
Dashboard handles sub-users with same name like this:
![image](https://user-images.githubusercontent.com/3850918/59827309-a22fbd00-9338-11e9-907a-e656dd1dbf62.png)
We need something similar for login in Vidi

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the user from `DATABASE_A` should be able to login to the `https://vidi_host/app/DATABASE_B/...`? The Dashboard allows to login to the multiple databases but isn't the only database to login with to Vidi is the database from the Vidi URL (`DATABASE_B`)?

**Comment by mapcentia** [comment]
@sashuk If you have a URL like `https://vidi_host/app/DATABASE_B/...` is shpuld only be users at `DATABASE_B`, which are allowed to login. So you could just take the database from the URL and not present the option of differnt databases.

**Comment by sashuk** [comment]
@mapcentia The `database` parameter is now passed along with the user name and password, the v2 API is used for authentication, implemented in https://github.com/sashuk/vidi/commit/a912a77aac6c5bb0f73207d3605d486fd299c009
