### ISSUE TITLE
Firefox is not rendering date/time input fields. Use framework instead?

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#320]
First off there is a problem with date/time input fields in Firefox:
![image](https://user-images.githubusercontent.com/3850918/59827826-dfe11580-9339-11e9-853e-4b640bfc5921.png)

As far as I know, there is only a Date/Time input type in HTML5 - not a Date only type? But we need a Date only input field, because In PostgreSQL we both have Date and Timestamp field.

So maybe we need to use some framework for Date/Time input?

**Comment by sashuk** [comment]
@mapcentia Sure, the Material `datetime` / `date` pickers will be used.

**Comment by sashuk** [comment]
@mapcentia According to the documentation the `date` input type is supported. Could you please specify if the GC2 type `Date` should have the `date`-only input and the `Timestamp` should have the `datetime` input?

Demo for `date` inputs:

![date_input_1](https://user-images.githubusercontent.com/1390758/59897092-aaadf380-941d-11e9-968e-17dda6b09468.gif)
![date_input_2](https://user-images.githubusercontent.com/1390758/59897093-aaadf380-941d-11e9-8647-09ac4666c7e2.gif)

**Comment by mapcentia** [comment]
@sashuk Yes that's correct.

**Comment by mapcentia** [comment]
https://www.postgresql.org/docs/11/datatype-datetime.html

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia `Date` and `Datetime` widgets are now used in filters, implemented in https://github.com/sashuk/vidi/commit/b0fb9b9b5f87a83ade788b17bc34bfe1f7e37694 (tested in Firefox).

Demo:
![firefox](https://user-images.githubusercontent.com/1390758/59921522-7f002d00-9460-11e9-88fa-77a0067ddbe9.gif)
