### ISSUE TITLE
default_layer_type in meta

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#321]
If a layer has more than one type (e.g. Tile and Vector) it seems Vector will be set as default in Vidi.
 We a setting for default type i Meta `default_layer_type`

**Comment by sashuk** [comment]
@mapcentia Feature was implemented in https://github.com/sashuk/vidi/commit/5d910416078645a738654b209840d95109e361bb.

The expected meta looks like this:

```
{
	"single_tile": false,
        "default_layer_type": "t", // should be "v", "t", "mvt" or "w"
	"max_features": "2",
	...
}
```

Demo:

![default_layer_type](https://user-images.githubusercontent.com/1390758/59869598-41e75c80-93c6-11e9-8833-8162e41d9a79.gif)
