### ISSUE TITLE
Can't create snapshots if URL lacks schema

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#322]
When creating a Snapshot, where is a check whether `schema` is defined in the URL:
https://github.com/sashuk/vidi/blob/develop/controllers/gc2/stateSnapshots.js#L210
But with a config, there may not be a schema definition the the URL and snapshot creation fails.
Is the check necessary?
The failing is not handled by the GUI.

**Comment by sashuk** [comment]
@mapcentia The `schema` is mandatory now as when the state snapshot is used in the configuration and it does not have the `schema`, the application initialization will fail:

https://github.com/sashuk/vidi/blob/4d863cdc5a6673a0fe3b988984394fc130ee1cdd/browser/modules/meta.js#L148-L155

However, this restriction can be removed, so whenever the application is loaded with the state snapshot in schemata, and the specified state snapshot does not have a `schema` object, the user will be notified that the state snapshot does not contain the  `schema` , so cannot be loaded - should this be implemented?

**Comment by mapcentia** [comment]
@sashuk Will this only affect the use of snapshots in configs? Not if you have something like this:

```json
{
"schemata": [
  "public",
  "tag:my_tag"
]
}
```

**Comment by sashuk** [comment]
@mapcentia Yes, the `schema` property of the state snapshot is now used only when state snapshot overwrites `schemata` in the configuration.

**Comment by mapcentia** [comment]
@sashuk the restriction should be removed

**Comment by sashuk** [comment]
@mapcentia The schema check was removed in https://github.com/sashuk/vidi/commit/1eaf6cfa6d1c7444715443b7cdbaaec212481a63
