### ISSUE TITLE
In print circle markers are also rendered as normal markers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#323]
In Vidi:
![image](https://user-images.githubusercontent.com/3850918/60171537-140d7800-980b-11e9-80fe-fe1b1218b52d.png)

In print:
![image](https://user-images.githubusercontent.com/3850918/60171489-ff30e480-980a-11e9-9956-b82edb8e47dc.png)

Expected: No markers

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/531c7bc1273b67a7bc30910039ea54d54b2e3cde

Demo:
![print](https://user-images.githubusercontent.com/1390758/60193555-76e22c00-986a-11e9-8114-bcd1feaf6bca.gif)
