### ISSUE TITLE
Vidi Performance slow with mutliple schemas data

### ISSUE THREAD

**Issue by lossoE** [sashuk/vidi#325]
@sashuk @mapcentia 
Vidi takes relatively a longer time when navigate from one parent category to another fetching data from mutiple schemas using config.  

Each parent category has at least 120 layers and this is been repeated 9x times for different geographic areas.
It sometimes crashes as well. Is there a way to implement a lazy load mode to improve user experience and performance? The server was recently upgraded with 32Gig of RAM.

Thx

**Comment by sashuk** [comment]
@lossoE Could you please provide the URL of your GC2 installation (not the Vidi one), so I could test this issue right with the actual data?

**Comment by lossoE** [comment]
@sashuk Here we go : http://geocloud.envirogissolutions.co.za

Most appreciated!

**Comment by sashuk** [comment]
@lossoE Thank you very much!

**Comment by lossoE** [comment]
@sashuk  It's a pleasure!

**Comment by lossoE** [comment]
@sashuk Here is a sample message

![image](https://user-images.githubusercontent.com/49659496/62293145-3d53a080-b468-11e9-82b2-533c00810608.png)

**Comment by sashuk** [comment]
@lossoE It is taking a long time in case of a big number of layers indeed, checking the code performance.

**Comment by lossoE** [comment]
@sashuk  Yes, see it in action here : https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c2.json#bingRoad/6/24.5544/-28.6135/
North West and select a layer then move to let say Mpumalanga it crashes.

**Comment by sashuk** [comment]
@mapcentia @lossoE Now subgroups children are not rendered until they are clicked, implemented in https://github.com/sashuk/vidi/commit/c22047bca27fcc3494c5c83fb7701e203b7cb440.

Demo:

![performance](https://user-images.githubusercontent.com/1390758/62528108-e5a1a480-b86e-11e9-8429-705d6c8ee351.gif)

**Comment by lossoE** [comment]
@sashuk This is perfect! Most appreciated! Is there anything i have to do on my side?

**Comment by sashuk** [comment]
@lossoE Happy to help! I think no, only update and rebuild the application.

**Comment by lossoE** [comment]
@sashuk I need a once off guidance on how to that. We have two rebuild pending at the moment. I will appreciate!
