### ISSUE TITLE
Search Queries using API Endpoints

### ISSUE THREAD

**Issue by lossoE** [sashuk/vidi#326]
@sashuk @mapcentia 
How can perform the following search function using GC2 RESTful API 

1. Search vector data using Elastic Search and Display results on a Map Control ( Bing Maps)
2. Save search results as Geojson
3. Search using GPS LAT / LON Coordinates and return  intersecting vector data in GeoJson format.
4. Search vector data that within specified radius / distance of a point or coordinate value.
Thx

**Comment by lossoE** [comment]
@sashuk @mapcentia  I'm trying to run a SQL Query to select points/ Features within a 5km radius of a point in LAT/LON. Any ideas on a correct approach?

http://geocloud.envirogissolutions.co.za/api/v1/sql/envirogis?q=SELECT * FROM report.sa_farmpolys_points WHERE st_distance(the_geom,'SRID=4326;POINT(29.3748220904 -25.3259617353)') < 5000;

**Comment by sashuk** [comment]
@lossoE Could you please specify what branch of the https://github.com/mapcentia/geocloud2 you are using (`master` or the `develop` one)?

**Comment by sashuk** [comment]
@lossoE Please try to run the `http://geocloud.envirogissolutions.co.za/api/v1/sql/envirogis?q=SELECT * FROM report.sa_farmpolys_points WHERE st_distance(the_geom, ST_Transform(ST_GeomFromText('POINT(29.3748220904 -25.3259617353)', 4326), THE_GEOM_SRID)) < 5000` (the SQL query you've mentioned contains the `;` inside, so it fail according to the https://github.com/mapcentia/geocloud2/blob/master/app/api/v1/Sql.php#L193

**Comment by lossoE** [comment]
@sashuk Thanks for assisting. I tried running it but it failed. I'm using the master. I can run simple select queries without issues. As seen below. But when i attempt promity analysis queries i get errors.

http://geocloud.envirogissolutions.co.za/api/v1/sql/envirogis?q=SELECT%20*%20FROM%20report.sa_farmpolys%20WHERE%20sg_code%20=%20%27T0JR00000000012400007%27

**Comment by sashuk** [comment]
@lossoE Could you please provide an example of failing query?

**Comment by lossoE** [comment]
@sashuk I had a look what you provided earlier and structured the Query below without ; at the end it got something.
 
http://geocloud.envirogissolutions.co.za/api/v1/sql/envirogis?q=SELECT * FROM report.sa_farmpolys WHERE ST_Intersects(the_geom,ST_Transform(ST_GeometryFromText('POINT(29.3748220904 -25.3259617353)', 4326), 3857));

**Comment by sashuk** [comment]
@lossoE Great!

**Comment by lossoE** [comment]
@sashuk Let me structure the search with a radius querie again. But i'm still trying to figure out how to use the Elastic search end queries. But i think i'm close. Thanks for you assistance.

**Comment by sashuk** [comment]
@lossoE Could you please specify if you are asking about API-only way of requesting data, not actually using the Vidi (the first two issues look more like a client-side problem)?

The Vidi allows requesting, viewing and exporting data as in the demo below:

![query](https://user-images.githubusercontent.com/1390758/62538994-b4cd6980-b886-11e9-8a2c-f2cc4a932d11.gif)

**Comment by lossoE** [comment]
@sashuk That's exactly what i want to achieve using the API. Our end user client wants to connect with a mobile app to execute this function. spot on.

**Comment by lossoE** [comment]
@sashuk This is not a vidi issue and it is capable. Sorry for not elaborating correctly.

**Comment by sashuk** [comment]
@lossoE So, basically the API description is required (or implementation if the functionality is not implemented yet)?

**Comment by lossoE** [comment]
@sashuk  Let me give you of context of what they want to achieve.
1. Access some layers within the production database to be used as backdrop : Possible using OGC Services
2. Search for a farm using Either Elastic or SQL API and store the results as Geojson for Manipulation or Overlay
3. They want to interact/Query GC2 without passing through Vidi
4. Most of the interaction is query and get data in Geojson.
5. Select a Farm that intersect with LAT / LON coordinates

**Comment by sashuk** [comment]
@lossoE Got it, thanks!

**Comment by lossoE** [comment]
@sashuk @mapcentia I managed tweak the the following query to search within 500meters
http://geocloud.envirogissolutions.co.za/api/v1/sql/envirogis?q=SELECT * FROM report.sa_farmpolys WHERE st_distance(the_geom, ST_Transform(ST_GeomFromText('POINT(29.3748220904 -25.3259617353)', 4326), 3857)) < 500

**Comment by lossoE** [comment]
@sashuk @mapcentia  Thanks assisting should i require further assistance i will not hesitate.
