### ISSUE TITLE
Often Service Worker will not start

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#332]
I got a lot of these:
![image](https://user-images.githubusercontent.com/3850918/62764829-16602480-ba8f-11e9-9290-d0a57996c9fd.png)

Is there a way of dealing with this issue?

**Comment by sashuk** [comment]
@mapcentia This is the known issue with Service Workers - sometimes the `api-bridge` is stopping checking for the registered Service worker after 3 tries (which have a 5 seconds timeout between each other). The solution is to increase the number of tries, which was implemented in https://github.com/sashuk/vidi/commit/d675ac9c3e3b9e090de4b38a36ae8b424ac8f6ee
