### ISSUE TITLE
Default to Tile layer in layer tree

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#39]
If property vidi_layer_type is not set (or present in the Meta object) default to Tile (now it defaults to Both)

If Tile or Vector is set, then don't show the disabled select box. Maybe show a discret symbole for Tile/Vector

**Comment by sashuk** [comment]
@mapcentia Is it okay to use such controls?

![test](https://user-images.githubusercontent.com/1390758/41351614-7df25f60-6f49-11e8-899c-5bd74abf4c01.png)

**Comment by mapcentia** [comment]
Yes, its looks good
