### ISSUE TITLE
stopEdit() in editor/browser/index.js doesn't disable the editor when canceling

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#41]
stopEdit() in editor/browser/index.js doesn't disable the editor when canceling a change on the existing feature. It does disable when creating a new one.
1) Click on feature and start edit
2) Cancel by clicking the Close X on attribute dialog.
3) Now the editable vector is still visible.

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/7acfd5447d47e14cb2aae0db574a10ace6eb06d3
