### ISSUE TITLE
Drag-and-drop sorting of layers and layer groups in layerTree

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#42]

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/4531c05e3f9e1ec59b7ca6f36065b686497391fb

**Comment by sashuk** [comment]
The order storing will be implemented in https://github.com/sashuk/vidi/issues/43

**Comment by mapcentia** [comment]
Layers in the map must also change order when the user re-orders the tree. So if the user drags Road under 2002, the roads layer must be placed under the 2002 layers. The initial order is defined by the sort_id property in the Meta object. This property can be set in GC2 Admin > Database > Sort id.

https://github.com/sashuk/vidi/blob/develop/browser/modules/layers.js#L188

https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#osm/12/39.2468/-6.8917/public.roads,public.urbanspatial_dar_es_salaam_luse_2002

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/84d4e329fb58ede0a893c6e4b39d49cd8aace003

![order](https://user-images.githubusercontent.com/1390758/41694214-c87d1122-753b-11e8-916a-b9d765f5e394.gif)
