### ISSUE TITLE
If online, can edits be put in queue instead of sending them directly to back-end

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#44]
If you're online and submit an edit, you'll wait for the back-end respons. If you're on a slow connection and submitting an image, this can take several seconds.
Could edits be put in queue and be pending? Just like if you're in Force offline mode.

**Comment by mapcentia** [comment]
When committing edits on tile layers, the reload of the layer is not timed correctly. It should be reloaded after the edits are stored in db.

**Comment by sashuk** [comment]
@mapcentia Could you please tell if you've meant the immediate tile layer update after submission? This behavior is fixed (for addition, update and deletion of features).

Fixed in https://github.com/sashuk/vidi/commit/f8ad6344cd3d8538bc0b0b320ba5eda44eae30ba

**Comment by mapcentia** [comment]
Closing
