### ISSUE TITLE
Sharing Vidi in a specific state (perma-link)

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#46]
Like this: https://vidi.alexshumilov.ru/app/aleksandrshumilov/public?state=12345678

Its important that we don't need the anchor for layers (eg. #osm/12/39.2468/-6.8917/public.roads), so we can change the state (like turning on a layer) without re-sharing the URL. Of course the state object in this case must be stored server side.

**Comment by sashuk** [comment]
@mapcentia Am I correct that if user navigates to Vidi using the permalink, then when he changes the visible layers, zooms in or out or does any changes to the interface then all these changes are automatically stored to the GC2 under this permalink?

So, it can be a scenario that **user A** asks **user B** for assistance (for example, **user A** can not add feature for layer in specific locations) and sends him a permalink. Then **user B** navigates to Vidi using this link, performs changes and when **user A** refreshes the page, then changes are displayed for **user A** as well.

**Comment by mapcentia** [comment]
**User B** should not be able to alter the a permalink made by **user A**. However a user should be able to change his own permalinks, but this should not be done automatically - but by some action.
The first use case is to present Vidi in specific states to the public. Its important that the permalink is not altered unconsciously.

**Comment by sashuk** [comment]
@mapcentia Thank you very much for clarification!

**Comment by sashuk** [comment]
Permalinks are generated for all state snapshots. Vidi can be loaded with only `state` parameter defined in URL, for example, https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/?state=93b5ea8f22de84defc338b797f8ccb1fef8305dc
