### ISSUE TITLE
Layers appear multiple times in layer tree after reload

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#57]
I'm not sure how to replicate this

![image](https://user-images.githubusercontent.com/3850918/42210970-a2add532-7eb2-11e8-9eff-4ade11e125d6.png)

**Comment by sashuk** [comment]
@mapcentia Could you please provide any additional details? For example, when have you observed this - after page reload, after modal window activation, after restoring state or after editing the page URL?

For now I've tried combinations with state activation, sign in and out, sorting layers - still no results. I will work on other issues for now hoping that this bug will show up so I will be able to fix it.

**Comment by mapcentia** [comment]
1. Switch on "Line" layer
2. Make a snapshot
3. Refresh browser.
5. Press play on Snapshot
6. Switch on "Point" layer

The layer tree when reloads and multiple Point layers appears.

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

**Comment by mapcentia** [comment]
I can still get some strange layer control. It happens when using snapshots and refreshing the browser.
![image](https://user-images.githubusercontent.com/3850918/42381746-617f6404-8132-11e8-9e23-bf1cc1b63e18.png)

**Comment by sashuk** [comment]
@mapcentia This error was observed, it happens whenever states are applied one-by-one (less than a second between pressing the `play` button).

**Comment by sashuk** [comment]
@mapcentia Now it is impossible to apply snapshot while another one is being applied.

Fixed in https://github.com/sashuk/vidi/commit/c0ac10554f48775896924fb6cc177f5f4e4314c0
