### ISSUE TITLE
Snapshots are not in list after refresh

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#59]
1. Make a snapshot
2. Refresh browser. Now thje snapshot list is empty
2. Make another snapshot. The first snapshot pops up in list

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/cd4bae19df9d1be990171e1e5f1e13f47aaaafa5

Tested in https://github.com/sashuk/vidi/commit/47b981b04c8a2faab53d45f4636e50467d647088#diff-1b7b89acf44d80fc8c124bb2f15cef81R74
