### ISSUE TITLE
Trash can button

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#6]
The "Trash can" besides the icons with edits: Its a bit confusing what its deletes. Maybe just leave that button out and let user delete by clicking the feature in the map

**Comment by sashuk** [comment]
@mapcentia Maybe it should have the **cancel** icon and when it is hovered, non-committed changes are dimmed, like in https://alexshumilov.ru/ftp_img/09u71j6pfn.png?

**Comment by mapcentia** [comment]
@sashuk Good solution. Closing
