### ISSUE TITLE
Included drawings in State

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#60]
When printing the draw-vector layer is serialised and re-created
Serialising: https://github.com/sashuk/vidi/blob/develop/browser/modules/print.js#L345
Re-create: https://github.com/sashuk/vidi/blob/develop/browser/modules/state.js#L390
I believe this system can be used to include drawings in State

**Comment by sashuk** [comment]
@mapcentia The serialization that is used in the `print` module takes all the vector data and recreates it afterwards. Am I correct that the state snapshot should contain only the identifier of the edited item and actual edited geometry and edited properties of the feature? So whenever state snapshot is applied, the specified feature **becomes edited** and changes made before (but not saved) should be **applied to it**?

**Comment by mapcentia** [comment]
Just to make clear: This is about the Draw module
![image](https://user-images.githubusercontent.com/3850918/42512221-524f02ee-8454-11e8-8be3-4f5eb538e6d7.png)
I believe you're talking about the Editor module?

**Comment by sashuk** [comment]
@mapcentia Thank you very much for clarification! I've started on the Editor module, but I will use today's codebase for the Drawing one.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/30f409fc7bcad56b8353ecf7e7fa0725c96c23fc

![draw](https://user-images.githubusercontent.com/1390758/42587916-c2e2dccc-856e-11e8-9d06-0eefbbfd5a2b.gif)
