### ISSUE TITLE
Side by side base layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#62]
The baselayer control can switch between layers with a radio button. We need a second radio button on every baselayer, so the two selected baselayers are shown side-by-side like this:
https://github.com/digidem/leaflet-side-by-side

On top in the baselayer control, where should be a toggle button, which switch this function on/off. So the second radio button are only shown when switch on.

**Comment by sashuk** [comment]
Current progress:
![sidebyside](https://user-images.githubusercontent.com/1390758/42384180-f416c062-816b-11e8-9a5b-fc5dca68ff6e.gif)

State snapshot interaction: https://github.com/sashuk/vidi/issues/63

Unmovable base layer: https://github.com/sashuk/vidi/issues/64

**Comment by sashuk** [comment]
Related issues are closed
