### ISSUE TITLE
api/legend is called for every layer on re-create a stae

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#67]
When re-creating a state, the api/legend is called once for every layer switched on. Its only necessary to call it once when all layers are switch on. Just like when Vidi is starting. See https://github.com/sashuk/vidi/pull/66
![image](https://user-images.githubusercontent.com/3850918/42566228-37ebbb92-8506-11e8-9d32-a01e853c0955.png)

https://github.com/sashuk/vidi/pull/66

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/6bf265cb6cc5c20366fab3dc62b2ce02f16c5b0a
