### ISSUE TITLE
When editor module is not enabled, the layer tree is not showning

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#68]

**Comment by sashuk** [comment]
Fixed in c4bd98cd2c905852ceafa3ee460266ccfd97a5bc

**Comment by sashuk** [comment]
`layerTree` module is now activated only externally (for example, in `editor`) or via `postInit()` method

Fixed in https://github.com/sashuk/vidi/commit/a6f14e1d52e22ad324a8814e5e5bb743493a93e0
