### ISSUE TITLE
Vidi is requesting a layer fra previous session

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#69]
I'm been testing with
 /app/mydb/feature and a layer called feature.multipoint

Now I've changed to 
/app/watsonc/public

And keep getting this error:
![image](https://user-images.githubusercontent.com/3850918/42567377-db875ace-8509-11e8-8bce-46b41810f76a.png)

I've cleared everything. The error doesn't occur in browsers not used for Vidi before

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/6f492fa06e42899c5a84db1428ba43f43d100c16

The problem was that `Queue` used the same storage for non-commited items independently of the database and scheme. Now it takes database and scheme into account.
