### ISSUE TITLE
Too big file size

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#7]
Test production build (Grunt production). Its will cut 5MB of the download.

**Comment by sashuk** [comment]
Current sizes:

```
-rw-rw-r-- 1 admin admin  3333236 May 29 08:39 all.min.js
-rw-rw-r-- 1 admin admin 11666717 May 29 08:39 all.min.js.map
-rw-rw-r-- 1 admin admin 284044 May 29 08:39 all.min.css
```

**Comment by sashuk** [comment]
Without **gzip** compression

<img width="786" alt="screen shot 2018-05-29 at 17 13 40" src="https://user-images.githubusercontent.com/1390758/40649785-5a4820ae-6364-11e8-918d-3b8ae7593f51.png">

With **gzip** compression (as Nginx module)

<img width="789" alt="screen shot 2018-05-29 at 17 17 39" src="https://user-images.githubusercontent.com/1390758/40649784-59fb64a8-6364-11e8-8bd9-51b4f3fc5320.png">

**Comment by sashuk** [comment]
@mapcentia Is this an acceptable level of compression? **gzip** is supported by all browsers.

**Comment by mapcentia** [comment]
Yes, I've added gzip now in my standard NGINX config
