### ISSUE TITLE
Drawings isn't keeping applied style changed in State

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#70]
Drawing state is working fine when creating a new drawing
![image](https://user-images.githubusercontent.com/3850918/42616656-541e3f16-85af-11e8-8fe0-7b027faa2802.png)
When I apply some changes and creating a new snapshot
![image](https://user-images.githubusercontent.com/3850918/42616698-813ecc72-85af-11e8-94b3-98611d14ede2.png)
When re-creating the new snapshot, I get the "old" style
![image](https://user-images.githubusercontent.com/3850918/42616763-add04a0e-85af-11e8-9b5a-2b4e51d86d97.png)
This only concerns the styling - not the actual shape

**Comment by sashuk** [comment]
Probably linked with https://github.com/sashuk/vidi/issues/72

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/dad77aa9c1e2402b35834f2e359ad73c8bc35c9f

![style](https://user-images.githubusercontent.com/1390758/42723079-cc12533c-8789-11e8-8e9a-519675b8540e.gif)
