### ISSUE TITLE
Baselayers bug in Vidi startup 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#71]
When calling this: https://vidi.alexshumilov.ru/app/aleksandrshumilov/public
I get this:
![image](https://user-images.githubusercontent.com/3850918/42616952-55285e36-85b0-11e8-9901-a29bc839fec9.png)

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/ce1b6fb9b509c78196565c8f072183f060f24302
