### ISSUE TITLE
Label (in draw module) after re-create state lacks visual handle

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#72]
A label can be moved:
![image](https://user-images.githubusercontent.com/3850918/42617061-b0d6ec84-85b0-11e8-93d5-fa9583181126.png)
After re-creating state, the "handle" is missing:
![image](https://user-images.githubusercontent.com/3850918/42617157-0121da1e-85b1-11e8-91cb-c52c3f10bc92.png)
But it can actual be moved.
After another snapshot and re-create, a marker symbole is showing. I guess the point, which the label is attached to, is being reset and gets default styling:
![image](https://user-images.githubusercontent.com/3850918/42617235-4a86d68c-85b1-11e8-8b41-dfa74ba329f4.png)

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/f262a97ae0904beade253f9ff4d061cb24844734

Handle now works, as the `circleMarker` is recreated on the map correctly.
