### ISSUE TITLE
 Duplicated layer in the layer tree

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#73]
I can't alway reproduce this, but on one installation it happens every time:
https://dev.envirogissolutions.co.za/app/test/sanral/#osm/16/18.4564/-33.9764/v:sanral.potholes
Start by switch to Off line mode. Create a new point:
![image](https://user-images.githubusercontent.com/3850918/42633527-0e92374a-85e1-11e8-91e0-7c2dd732ad2b.png)
Refreash browser and now the layer is dublicated in the layer tree:
![image](https://user-images.githubusercontent.com/3850918/42633537-1343dce4-85e1-11e8-9b55-a8b3dbcd21fa.png)

**Comment by sashuk** [comment]
@mapcentia I've tested the interactions with the vector point layers in usual database, as well as simulated data from the `dev.envirogissolutions.co.za` (the https://github.com/sashuk/vidi/commit/f86f65a1a54a511c9aa4bbc59f9bc991dcc54709 branch), however, the specific behaviour could not be recreated. Could you please give access to the actual host?

Probably the `dev.envirogissolutions.co.za` codebase should be updated, as the recent change https://github.com/sashuk/vidi/blob/fc7e584b22e4c891e913d39b0d226dc89f57c91d/browser/modules/layerTree.js#L203 actually deals with the race condition in the layerTree module, so I hope it will be enough to fix this error.

**Comment by sashuk** [comment]
@mapcentia Just checked the case again, seems to work correctly after reload:

![sanral](https://user-images.githubusercontent.com/1390758/43930115-56f26038-9c6a-11e8-8f0c-c5591d95a747.png)

Could you please confirm that the codebase was updated?

**Comment by mapcentia** [comment]
@sashuk Yes, it seems to work. Closing
