### ISSUE TITLE
When creating a state with side-by-side baselayer, the function is not always enabled

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#82]
This happens only occasionally

**Comment by sashuk** [comment]
Can be recreated via following steps:

- create state snapshot with side-by-side mode enabled
- navigate to one of state snapshot links (https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/?state=6de397f886d6c3121b9ddd162ca84b6e8836e6e6)
- disable the side-by-side mode
- apply previously created snapshot - the side-by-side mode is recreated
- apply previously created snapshot again - the side-by-side mode **is not recreated**

**Comment by sashuk** [comment]
Fixed in 1413869adf5e1ee37e917c7cbcfe799cd3f1aa12
