### ISSUE TITLE
Update of a snapshot

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#83]
Besides a snapshot can be "played" and "trashed", its should also have a update function, which will save the current state under the same id.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/9edd5bab5fc55dc9e2eb5f7d3385f9583c890098

![update](https://user-images.githubusercontent.com/1390758/43194347-b83fcf5c-9034-11e8-98ab-c158730296d5.gif)
