### ISSUE TITLE
Reset function should reset custom layer order, side-be-side baselayer etc.

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#85]
There is a very simple reset module:
https://github.com/sashuk/vidi/blob/develop/browser/modules/reset.js
This module should reset all session state like custom layer order etc.

![image](https://user-images.githubusercontent.com/3850918/43045495-c04117b0-8db9-11e8-9031-0f26ce1518bf.png)

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/23fe0b181f80bb4ed144fc9536541b70e4e22c8b

![reset](https://user-images.githubusercontent.com/1390758/43253349-54ed001e-90f7-11e8-98f0-acfeed132887.gif)
