### ISSUE TITLE
Another/new measure tool

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#86]
We're using this plugin for measure tool: https://github.com/ljagis/leaflet-measure
https://github.com/sashuk/vidi/blob/develop/browser/modules/cloud.js#L119
We need another, because this one will always close the line into a polygon, which are annoying when you just want to measure a distance.
Either we use another plugin or roll our own. An idea is to clone the Draw module into a Measure module and limit the shapes to line and polygon and hide the options, which will be pre-set to show measurement and has "stops" as Extremities.

![image](https://user-images.githubusercontent.com/3850918/43045668-2a6eed30-8dbd-11e8-9e90-3aa023ac6824.png)

**Comment by mapcentia** [comment]
This new tool has to work with the master branch also.

**Comment by mapcentia** [comment]
There should be multiple measurements of every kind

**Comment by mapcentia** [comment]
@sashuk The module should also be implemented in the Embed template.

**Comment by sashuk** [comment]
@mapcentia Could you please tell if the draw tool should have hard-coded feature display style or it should be configurable as in `Draw` module?

**Comment by mapcentia** [comment]
@sashuk Style should be hardcoded.
It could great if measurements are stored in state. But remember, that it also should work in master branch for now.

**Comment by sashuk** [comment]
@mapcentia Thanks for clarification! I will merge it with `master` and test upon completion.

**Comment by sashuk** [comment]
Current state of the measurements tool

![measurements](https://user-images.githubusercontent.com/1390758/43393480-e5905a00-9429-11e8-84a5-5fcdd9c8ba9a.gif)

**Comment by sashuk** [comment]
@mapcentia Does the `embed` template implementation of the **measurements** tool has to have the same set of capabilities as for the default template (editing and deleting already drawn measurements, map button controls etc.)?

**Comment by mapcentia** [comment]
@sashuk Is will be fine if the measurements tool can't edit/delete already drawn shapes. When starting a new one the current one can be deleted. It could be nice if the buttons match the style of the other butttons in Embed template

**Comment by sashuk** [comment]
@mapcentia Thanks for clarification!

**Comment by sashuk** [comment]
Current state of the measurements tool for embed mode

![embed](https://user-images.githubusercontent.com/1390758/43454698-6f73bcb4-94f0-11e8-9028-017f6e45c615.gif)
