### ISSUE TITLE
When re-creating a snapshot the baselayer is set to "undefined" every second time the play button is pressed

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#87]
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#**undefined**/11/39.2366/-6.8058/

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/da9567a451a26d88b22abaefe540f5ffa8460ece

![baselayers](https://user-images.githubusercontent.com/1390758/43193968-e18358ee-9033-11e8-87b7-0cf5c55da58e.gif)
