### ISSUE TITLE
Support of JSON object in Editor option field

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#88]
When configuring an option field in the editor, you do it with a JSON array like:
['a','c','d']

We need to support a JSON object, so we can set separate display string and value. Like:
{'First option': 1, 'Second option': 2, 'Third option': 3}

In the option field, the property names are displayed and the values are uses as values.

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/93e32bd2355078d49f9be97046e858cb00b88d5c

Also aliases for fields are now taken into account

![properties](https://user-images.githubusercontent.com/1390758/43309855-85f6870e-91b8-11e8-8508-522cf2b7196d.png)
