### ISSUE TITLE
New module: Pull data from layer(s) into kepler.gl

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#95]
Uber has open sourced kepler.gl which is a simple and effective tool for filtering and visualizing data. A client wants a module that can transfer layers into kepler, where the user can continue working with them. kepler.gl uses GeoJSON, so the data is ready to.
My idea is run kepler.gl from the public folder of Vidi. An extension list all layers (the same as in Layer Tree), where you can check layers and start kepler.gl with them.
Note: I'm not familiar with kepler.gl and don't if this can be done easily.

**Comment by sashuk** [comment]
@mapcentia Is it okay if it will be started in modal window from inside of Vidi? This way Kepler will be still a part of the Vidi and the integration between Vidi as data provider and Kepler as data processor will be easier

**Comment by baffioso** [comment]
When exporting point geometries for kepler, it would be an advantageto to append lat and lon columns to the table, since some of the vizualization demands this format. Something like: 
```sql
select *, st_x(the_geom), st_y(the_geom)
from table
```

**Comment by mapcentia** [comment]
No support for embed emplate is needed

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by baffioso** [comment]
Looks promising. Looking forward to start testing.

**Comment by sashuk** [comment]
Current state of things: Vidi layers can be imported, except point layers. In order to import point layers the information provided before by @baffioso will be used.

![importingdata](https://user-images.githubusercontent.com/1390758/44080938-0ac13c1a-9fe0-11e8-996a-8e9b0e1e7ce8.gif)

**Comment by baffioso** [comment]
Looks good

**Comment by sashuk** [comment]
@mapcentia @baffioso Point layers are now imported in the KeplerGL in CSV format (https://github.com/uber/kepler.gl/issues/177 issue), final integration implemented in https://github.com/sashuk/vidi/commit/87cc25d59af53cc6c2d5678dc858f75d07328397

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! Merged in https://github.com/sashuk/vidi/commit/137fe2c34e48d1ae3add43384561400627aec8fd
