### ISSUE TITLE
Use global translation function __() in standard modules

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#97]
In standard modules (those in browser/modules) use the global __() function instead of a private one. Like here: https://github.com/sashuk/vidi/blob/develop/browser/modules/stateSnapshots.js#L494
This way we can use the files in browser/i18n for translation.

**Comment by sashuk** [comment]
@mapcentia Is it okay to use the local dictionary variable for module or all translations should be put in the global `i18n` file? The example of local dictionary variable is at https://github.com/sashuk/vidi/blob/develop/browser/modules/stateSnapshots.js#L494

**Comment by mapcentia** [comment]
@sashuk For all modules, which are included in the source tree of Vidi, the translations should be put in global i18n file. Local translations are mainly for extension modules with own source repo.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! Then moving all translation in `browser/modules` and `extensions` to the single i18n file.

**Comment by sashuk** [comment]
Fixed in 2f3cae7775802195da34482bad947b87e8b20d85
