### ISSUE TITLE
New measurement module should react on the "reset:all" event

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#98]
When starting a drawing, advanced query and so on, other tools must in most cases be switched off. We desided that all modules should listen to the "reset:all" event and do whatever to reset/disable it self.
The new measurement tool should trigger the "reset:all" event when enabled and disable it self on the same event. Right now you can enable both measurement and e.g. drawing at the same time. Its only disabling of the drawing tools - the actual drawings should remain in the map.

backboneEvents.get().on("reset:all", function () {
                    // Disable tool
                });

**Comment by sashuk** [comment]
@mapcentia Am I correct that when all modules are reset, the `infoClick` should be enabled by default?

**Comment by mapcentia** [comment]
@sashuk yes

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

In https://github.com/sashuk/vidi/commit/e629e8e2fe63c9b0c0784e723f25a63ab317cc53 new event processing was proposed (for now only for `measurements` and `draw` modules):

- modules should know nothing about other modules, especially they should not be able to control them (like turning the `infoClick` in `draw` module) - this way the isolation of module is achieved and there is no confusion about side effects. The only way modules can alter reality - they can emit events like `module:turnedOff` or `module:turnedOn` - all the effects of these events should be processed somewhere else (in `bindEvent.js`)
- `bindEvent.js` listens to the events about turning on and off of other modules and implement complex logic that involves any existing module. The code in `bindEvent.js` can actually reset other modules, so the complex module iteraction logic is gathered in one place and scattered all over the application

Emitting module updates: https://github.com/sashuk/vidi/blob/e629e8e2fe63c9b0c0784e723f25a63ab317cc53/browser/modules/measurements.js#L186

Reacting and reseting other modules: https://github.com/sashuk/vidi/blob/e629e8e2fe63c9b0c0784e723f25a63ab317cc53/browser/modules/bindEvent.js#L273-L290

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/e629e8e2fe63c9b0c0784e723f25a63ab317cc53
