### ISSUE TITLE
When cancelling measurement tool in Embed, the drawing tool is not disabled

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#99]
1. Start a measurement.
2. Cancel/close tool before you finish the drawing.
Now the drawing tool is still active.

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/3456d8e4864a375683ce50d8f72a70ca05805511

![draw](https://user-images.githubusercontent.com/1390758/43765276-1f4f2486-9a62-11e8-8bcd-d7f298bf9f3c.gif)
